# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import allspice_client
from allspice_client.paths.repos_owner_repo_allspice_generated_json_filepath import get  # noqa: E501
from allspice_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestReposOwnerRepoAllspiceGeneratedJsonFilepath(ApiTestMixin, unittest.TestCase):
    """
    ReposOwnerRepoAllspiceGeneratedJsonFilepath unit test stubs
        Get the json blob for a cad file if it exists, otherwise enqueue a new job and return a 503 status. Note: This is still experimental and not yet recommended for critical applications.  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200
    response_body = ''


if __name__ == '__main__':
    unittest.main()
