# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import allspice_client
from allspice_client.paths.teams_id_members_username import put  # noqa: E501
from allspice_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestTeamsIdMembersUsername(ApiTestMixin, unittest.TestCase):
    """
    TeamsIdMembersUsername unit test stubs
        Add a team member  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = put.ApiForput(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 204
    response_body = ''


if __name__ == '__main__':
    unittest.main()
