# coding: utf-8

# flake8: noqa

"""
    AllSpice API.

    This documentation describes the AllSpice API.  # noqa: E501

    The version of the OpenAPI document: gitea+v1.19.2-52-gc95a358b1
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.19.3"

# import ApiClient
from allspice_client.api_client import ApiClient

# import Configuration
from allspice_client.configuration import Configuration

# import exceptions
from allspice_client.exceptions import OpenApiException
from allspice_client.exceptions import ApiAttributeError
from allspice_client.exceptions import ApiTypeError
from allspice_client.exceptions import ApiValueError
from allspice_client.exceptions import ApiKeyError
from allspice_client.exceptions import ApiException
