[tool.autopep8]
max_line_length = 100
# This should match ruff excludes.
exclude = ""

[tool.ruff]
ignore = [
  "E501", # Line length.
  "F405", # Unknown identifier usage due to import *.
]
line-length = 100
select = ["E", "F", "RUF"]
# This should match autopep8 excludes.
exclude = []

[tool.pytest.ini_options]
markers = [
  "ashub: marks tests which will fail on vanilla gitea and require ashub.",
]
