import subprocess
from pathlib import Path

GENERATED_HEADER = "# @generated by open-api-generator — do not edit by hand"
HTTP_METHODS = {"get", "put", "post", "delete", "patch"}


def ruff_fix(*paths: Path) -> None:
    """Bring the generated files up to the project's ruff config, so their diffs read like the rest of
    the codebase. Fixes first — sorting imports and stripping ones left unused by the rewrites — then
    formats, since formatting settles the final layout."""
    target_paths = [str(path) for path in paths]
    print(f"Running ruff check --fix and ruff format on {', '.join(target_paths)}")
    subprocess.run(["ruff", "check", "--fix", *target_paths], check=True)
    subprocess.run(["ruff", "format", *target_paths], check=True)
