import subprocess
from pathlib import Path

GENERATED_HEADER = "# @generated by open-api-generator — do not edit by hand"
HTTP_METHODS = {"get", "put", "post", "delete", "patch"}


def ruff_fix(*paths: Path) -> None:
    """Apply ruff's safe autofixes to the generated files — sorts imports and strips ones left
    unused by the rewrites, along with the project's other fixable rules."""
    subprocess.run(["ruff", "check", "--fix", *(str(p) for p in paths)], check=True)
