# coding: utf-8

"""
    AllSpice API.

    This documentation describes the AllSpice API.  # noqa: E501

    The version of the OpenAPI document: gitea+v1.19.2-52-gc95a358b1
    Generated by: https://openapi-generator.tech
"""

import unittest

import allspice_client
from allspice_client.model.edit_pull_request_option import EditPullRequestOption
from allspice_client import configuration


class TestEditPullRequestOption(unittest.TestCase):
    """EditPullRequestOption unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
