# Add BOM to an AllSpice Hub DR.

from argparse import ArgumentParser
import subprocess
import os

from allspice import AllSpice, DesignReview

parser = ArgumentParser()
parser.add_argument("repo", help="The name of the repo, like orgname/reponame")
parser.add_argument("dr", help="The number of the DR, like 5")

args = parser.parse_args()

allspice = AllSpice(os.environ["ALLSPICE_TOKEN"])
repo_owner, repo_name = args.repo.split("/")
dr = DesignReview.request(allspice, repo_owner, repo_name, args.dr)

# This uses the generate_bom example script to generate a BOM.
# See: https://github.com/AllSpiceIO/py-allspice/tree/main/examples/generate_bom

subprocess.run(
    [
        "python",
        "generate_bom.py",
        args.repo,
        "main.PrjPcb",
        "--source-branch",
        dr.head,
        "--output-file",
        "bom.csv",
    ]
)

# This identifier helps us find the comment in the DR that we want to replace. This means
# we can re-use the existing comment, instead of making a new comment every time.
comment_identifier = "<!-- AllSpice BOM Generated by CI -->"

comments = dr.get_comments()
comment_to_replace = None
for comment in comments:
    if comment_identifier in comment.body:
        comment_to_replace = comment
        break

if comment_to_replace is None:
    comment = dr.create_comment(comment_identifier + "\nGenerated BOM")
    comment.create_attachment(open("bom.csv", "rb"), "bom.csv")
else:
    existing_attachments = comment_to_replace.get_attachments()
    for attachment in existing_attachments:
        comment_to_replace.delete_attachment(attachment)
    comment_to_replace.create_attachment(open("bom.csv", "rb"), "bom.csv")
