# @generated by open-api-generator — do not edit by hand

from typing import Annotated

from allspice.base import (
    ApiRequest,
    FileBody,
    HeaderParam,
    JSONBody,
    PaginatedRequest,
    PathParam,
    QueryParam,
)
from allspice.schemas import (
    AddTimeOption,
    Attachment,
    Branch,
    CombinedStatus,
    Comment,
    Commit,
    CommitStatus,
    ContentsResponse,
    ContentsResponseOrList,
    CreateBranchRepoOption,
    CreateDesignReviewOption,
    CreateDesignReviewReviewOptions,
    CreateFileOptions,
    CreateHookOption,
    CreateIssueCommentOption,
    CreateIssueOption,
    CreateMilestoneOption,
    CreateOrgOption,
    CreateReleaseOption,
    CreateRepoOption,
    CreateStatusOption,
    CreateTeamOption,
    CreateUserOption,
    DeleteFileOptions,
    DesignReview,
    DesignReviewReview,
    DesignReviewReviewComment,
    DocumentOutput,
    EditAttachmentOptions,
    EditDesignReviewOption,
    EditIssueCommentOption,
    EditIssueOption,
    EditOrgOption,
    EditReleaseOption,
    EditRepoOption,
    EditTeamOption,
    EditUserOption,
    Email,
    FileDeleteResponse,
    FileResponse,
    GitEntry,
    GitTreeResponse,
    Hook,
    Issue,
    MergeDesignReviewOption,
    Milestone,
    Organization,
    ProjectData,
    Release,
    Repository,
    SearchResults,
    ServerVersion,
    StateTypeFilter,
    SubmitDesignReviewReviewOptions,
    Team,
    TopicNamesResponse,
    TrackedTime,
    TransferRepoOption,
    UpdateFileOptions,
    User,
    UserHeatmapData,
)


class AdminGetAllOrgsRequest(PaginatedRequest[list[Organization], Organization]):
    """
    List all organizations

    https://hub.allspice.io/api/swagger#/admin/adminGetAllOrgs

    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/admin/orgs"
    response_model = list[Organization]

    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class AdminSearchUsersRequest(PaginatedRequest[list[User], User]):
    """
    Search users according filter conditions

    https://hub.allspice.io/api/swagger#/admin/adminSearchUsers

    :param source_id: ID of the user's login source to search for
    :param login_name: user's login name to search for
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/admin/users"
    response_model = list[User]

    source_id: Annotated[int | None, QueryParam()] = None
    login_name: Annotated[str | None, QueryParam()] = None
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class AdminCreateUserRequest(ApiRequest[User]):
    """
    Create a user

    https://hub.allspice.io/api/swagger#/admin/adminCreateUser
    """
    method = "POST"
    request_path = "/admin/users"
    response_model = User

    body: Annotated[CreateUserOption, JSONBody()]


class AdminDeleteUserRequest(ApiRequest[None]):
    """
    Delete a user

    https://hub.allspice.io/api/swagger#/admin/adminDeleteUser

    :param username: username of user to delete
    :param purge: purge the user from the system completely
    """
    method = "DELETE"
    request_path = "/admin/users/{username}"
    response_model = None

    username: Annotated[str, PathParam()]
    purge: Annotated[bool | None, QueryParam()] = None


class AdminEditUserRequest(ApiRequest[User]):
    """
    Edit an existing user

    https://hub.allspice.io/api/swagger#/admin/adminEditUser

    :param username: username of user to edit
    """
    method = "PATCH"
    request_path = "/admin/users/{username}"
    response_model = User

    username: Annotated[str, PathParam()]
    body: Annotated[EditUserOption, JSONBody()]


class AdminCreateOrgRequest(ApiRequest[Organization]):
    """
    Create an organization

    https://hub.allspice.io/api/swagger#/admin/adminCreateOrg

    :param username: username of the user that will own the created organization
    """
    method = "POST"
    request_path = "/admin/users/{username}/orgs"
    response_model = Organization

    username: Annotated[str, PathParam()]
    body: Annotated[CreateOrgOption, JSONBody()]


class AdminCreateRepoRequest(ApiRequest[Repository]):
    """
    Create a repository on behalf of a user

    https://hub.allspice.io/api/swagger#/admin/adminCreateRepo

    :param username: username of the user. This user will own the created repository
    """
    method = "POST"
    request_path = "/admin/users/{username}/repos"
    response_model = Repository

    username: Annotated[str, PathParam()]
    body: Annotated[CreateRepoOption, JSONBody()]


class OrgGetRequest(ApiRequest[Organization]):
    """
    Get an organization

    https://hub.allspice.io/api/swagger#/organization/orgGet

    :param org: name of the organization to get
    """
    method = "GET"
    request_path = "/orgs/{org}"
    response_model = Organization

    org: Annotated[str, PathParam()]


class OrgDeleteRequest(ApiRequest[None]):
    """
    Delete an organization

    https://hub.allspice.io/api/swagger#/organization/orgDelete

    :param org: organization that is to be deleted
    """
    method = "DELETE"
    request_path = "/orgs/{org}"
    response_model = None

    org: Annotated[str, PathParam()]


class OrgEditRequest(ApiRequest[Organization]):
    """
    Edit an organization

    https://hub.allspice.io/api/swagger#/organization/orgEdit

    :param org: name of the organization to edit
    """
    method = "PATCH"
    request_path = "/orgs/{org}"
    response_model = Organization

    org: Annotated[str, PathParam()]
    body: Annotated[EditOrgOption, JSONBody()]


class OrgListMembersRequest(PaginatedRequest[list[User], User]):
    """
    List an organization's members

    https://hub.allspice.io/api/swagger#/organization/orgListMembers

    :param org: name of the organization
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/orgs/{org}/members"
    response_model = list[User]

    org: Annotated[str, PathParam()]
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class OrgIsMemberRequest(ApiRequest[None]):
    """
    Check if a user is a member of an organization

    https://hub.allspice.io/api/swagger#/organization/orgIsMember

    :param org: name of the organization
    :param username: username of the user
    """
    method = "GET"
    request_path = "/orgs/{org}/members/{username}"
    response_model = None

    org: Annotated[str, PathParam()]
    username: Annotated[str, PathParam()]


class OrgDeleteMemberRequest(ApiRequest[None]):
    """
    Remove a member from an organization

    https://hub.allspice.io/api/swagger#/organization/orgDeleteMember

    :param org: name of the organization
    :param username: username of the user
    """
    method = "DELETE"
    request_path = "/orgs/{org}/members/{username}"
    response_model = None

    org: Annotated[str, PathParam()]
    username: Annotated[str, PathParam()]


class OrgListPublicMembersRequest(PaginatedRequest[list[User], User]):
    """
    List an organization's public members

    https://hub.allspice.io/api/swagger#/organization/orgListPublicMembers

    :param org: name of the organization
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/orgs/{org}/public_members"
    response_model = list[User]

    org: Annotated[str, PathParam()]
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class OrgListReposRequest(PaginatedRequest[list[Repository], Repository]):
    """
    List an organization's repos

    https://hub.allspice.io/api/swagger#/organization/orgListRepos

    :param org: name of the organization
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/orgs/{org}/repos"
    response_model = list[Repository]

    org: Annotated[str, PathParam()]
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class CreateOrgRepoRequest(ApiRequest[Repository]):
    """
    Create a repository in an organization

    https://hub.allspice.io/api/swagger#/organization/createOrgRepo

    :param org: name of organization
    """
    method = "POST"
    request_path = "/orgs/{org}/repos"
    response_model = Repository

    org: Annotated[str, PathParam()]
    body: Annotated[CreateRepoOption, JSONBody()]


class OrgListTeamsRequest(PaginatedRequest[list[Team], Team]):
    """
    List an organization's teams

    https://hub.allspice.io/api/swagger#/organization/orgListTeams

    :param org: name of the organization
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/orgs/{org}/teams"
    response_model = list[Team]

    org: Annotated[str, PathParam()]
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class OrgCreateTeamRequest(ApiRequest[Team]):
    """
    Create a team

    https://hub.allspice.io/api/swagger#/organization/orgCreateTeam

    :param org: name of the organization
    """
    method = "POST"
    request_path = "/orgs/{org}/teams"
    response_model = Team

    org: Annotated[str, PathParam()]
    body: Annotated[CreateTeamOption, JSONBody()]


class RepoSearchRequest(PaginatedRequest[SearchResults, Repository]):
    """
    Search for repositories

    https://hub.allspice.io/api/swagger#/repository/repoSearch

    :param q: keyword
    :param topic: Limit search to repositories with keyword as topic
    :param includeDesc: include search of keyword within repository description
    :param uid: search only for repos that the user with the given id owns or contributes to
    :param priority_owner_id: repo owner to prioritize in the results
    :param team_id: search only for repos that belong to the given team id
    :param starredBy: search only for repos that the user with the given id has starred
    :param private: include private repositories this user has access to (defaults to true)
    :param is_private: show only pubic, private or all repositories (defaults to all)
    :param template: include template repositories this user has access to (defaults to true)
    :param archived: show only archived, non-archived or all repositories (defaults to all)
    :param mode: type of repository to search for. Supported values are "fork", "source", "mirror" and "collaborative"
    :param exclusive: if `uid` is given, search only for repos that the user owns
    :param sort: sort repos by attribute. Supported values are "alpha", "created", "updated", "size", "git_size", "lfs_size", "stars", "forks" and "id". Default is "alpha"
    :param order: sort order, either "asc" (ascending) or "desc" (descending). Default is "asc", ignored if "sort" is not specified.
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/repos/search"
    response_model = SearchResults
    _page_items_attr = "data"

    q: Annotated[str | None, QueryParam()] = None
    topic: Annotated[bool | None, QueryParam()] = None
    includeDesc: Annotated[bool | None, QueryParam()] = None
    uid: Annotated[int | None, QueryParam()] = None
    priority_owner_id: Annotated[int | None, QueryParam()] = None
    team_id: Annotated[int | None, QueryParam()] = None
    starredBy: Annotated[int | None, QueryParam()] = None
    private: Annotated[bool | None, QueryParam()] = None
    is_private: Annotated[bool | None, QueryParam()] = None
    template: Annotated[bool | None, QueryParam()] = None
    archived: Annotated[bool | None, QueryParam()] = None
    mode: Annotated[str | None, QueryParam()] = None
    exclusive: Annotated[bool | None, QueryParam()] = None
    sort: Annotated[str | None, QueryParam()] = None
    order: Annotated[str | None, QueryParam()] = None
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class RepoGetRequest(ApiRequest[Repository]):
    """
    Get a repository

    https://hub.allspice.io/api/swagger#/repository/repoGet

    :param owner: owner of the repo
    :param repo: name of the repo
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}"
    response_model = Repository

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]


class RepoDeleteRequest(ApiRequest[None]):
    """
    Delete a repository

    https://hub.allspice.io/api/swagger#/repository/repoDelete

    :param owner: owner of the repo to delete
    :param repo: name of the repo to delete
    """
    method = "DELETE"
    request_path = "/repos/{owner}/{repo}"
    response_model = None

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]


class RepoEditRequest(ApiRequest[Repository]):
    """
    Edit a repository's properties. Only fields that are set will be changed.

    https://hub.allspice.io/api/swagger#/repository/repoEdit

    :param owner: owner of the repo to edit
    :param repo: name of the repo to edit
    """
    method = "PATCH"
    request_path = "/repos/{owner}/{repo}"
    response_model = Repository

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    body: Annotated[EditRepoOption, JSONBody()]


class RepoGetAllSpiceJSONRequest(ApiRequest[DocumentOutput]):
    """
    Get the json blob for a cad file if it exists, otherwise enqueue a new job and return a 503 status. Note: This is still experimental and not yet recommended for critical applications.

    https://hub.allspice.io/api/swagger#/repository/repoGetAllSpiceJSON

    :param owner: owner of the repo
    :param repo: name of the repo
    :param filepath: filepath of the cad file to get JSON for
    :param ref: The name of the commit/branch/tag. Default the repository's default branch (usually main)
    :param Prefer: Set to 'respond-async' (RFC 7240) to receive a 202 Accepted response while generation is in progress, instead of 503. The 'wait' preference is not honored.
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/allspice_generated/json/{filepath}"
    response_model = DocumentOutput

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    filepath: Annotated[str, PathParam()]
    ref: Annotated[str | None, QueryParam()] = None
    Prefer: Annotated[str | None, HeaderParam()] = None


class RepoGetAllSpiceProjectRequest(ApiRequest[ProjectData]):
    """
    Get the json blob for the project referencing the file, otherwise enqueue a new job and return a 503 status. Note: This is still experimental and not yet recommended for critical applications.

    https://hub.allspice.io/api/swagger#/repository/repoGetAllSpiceProject

    :param owner: owner of the repo
    :param repo: name of the repo
    :param filepath: filepath of the cad file to get project JSON for
    :param ref: The name of the commit/branch/tag. Default the repository's default branch (usually main)
    :param Prefer: Set to 'respond-async' (RFC 7240) to receive a 202 Accepted response while generation is in progress, instead of 503. The 'wait' preference is not honored.
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/allspice_generated/project/{filepath}"
    response_model = ProjectData

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    filepath: Annotated[str, PathParam()]
    ref: Annotated[str | None, QueryParam()] = None
    Prefer: Annotated[str | None, HeaderParam()] = None


class RepoGetAllSpiceSVGRequest(ApiRequest[bytes]):
    """
    Get the svg blob for a cad file if it exists, otherwise enqueue a new job and return 503 status. Note: This is still experimental and not yet recommended for critical applications.

    https://hub.allspice.io/api/swagger#/repository/repoGetAllSpiceSVG

    :param owner: owner of the repo
    :param repo: name of the repo
    :param filepath: filepath of the cad file to get SVG for
    :param ref: The name of the commit/branch/tag. Default the repository's default branch (usually main)
    :param Prefer: Set to 'respond-async' (RFC 7240) to receive a 202 Accepted response while generation is in progress, instead of 503. The 'wait' preference is not honored.
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/allspice_generated/svg/{filepath}"
    response_model = bytes

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    filepath: Annotated[str, PathParam()]
    ref: Annotated[str | None, QueryParam()] = None
    Prefer: Annotated[str | None, HeaderParam()] = None


class RepoGetArchiveRequest(ApiRequest[bytes]):
    """
    Get an archive of a repository

    https://hub.allspice.io/api/swagger#/repository/repoGetArchive

    :param owner: owner of the repo
    :param repo: name of the repo
    :param archive: the git reference for download with attached archive format (e.g. master.zip)
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/archive/{archive}"
    response_model = bytes

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    archive: Annotated[str, PathParam()]


class RepoListBranchesRequest(PaginatedRequest[list[Branch], Branch]):
    """
    List a repository's branches

    https://hub.allspice.io/api/swagger#/repository/repoListBranches

    :param owner: owner of the repo
    :param repo: name of the repo
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/branches"
    response_model = list[Branch]

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class RepoCreateBranchRequest(ApiRequest[Branch]):
    """
    Create a branch

    https://hub.allspice.io/api/swagger#/repository/repoCreateBranch

    :param owner: owner of the repo
    :param repo: name of the repo
    """
    method = "POST"
    request_path = "/repos/{owner}/{repo}/branches"
    response_model = Branch

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    body: Annotated[CreateBranchRepoOption, JSONBody()]


class RepoGetBranchRequest(ApiRequest[Branch]):
    """
    Retrieve a specific branch from a repository, including its effective branch protection

    https://hub.allspice.io/api/swagger#/repository/repoGetBranch

    :param owner: owner of the repo
    :param repo: name of the repo
    :param branch: branch to get
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/branches/{branch}"
    response_model = Branch

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    branch: Annotated[str, PathParam()]


class RepoListCollaboratorsRequest(PaginatedRequest[list[User], User]):
    """
    List a repository's collaborators

    https://hub.allspice.io/api/swagger#/repository/repoListCollaborators

    :param owner: owner of the repo
    :param repo: name of the repo
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/collaborators"
    response_model = list[User]

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class RepoCheckCollaboratorRequest(ApiRequest[None]):
    """
    Check if a user is a collaborator of a repository

    https://hub.allspice.io/api/swagger#/repository/repoCheckCollaborator

    :param owner: owner of the repo
    :param repo: name of the repo
    :param collaborator: username of the collaborator
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/collaborators/{collaborator}"
    response_model = None

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    collaborator: Annotated[str, PathParam()]


class RepoDeleteCollaboratorRequest(ApiRequest[None]):
    """
    Delete a collaborator from a repository

    https://hub.allspice.io/api/swagger#/repository/repoDeleteCollaborator

    :param owner: owner of the repo
    :param repo: name of the repo
    :param collaborator: username of the collaborator to delete
    """
    method = "DELETE"
    request_path = "/repos/{owner}/{repo}/collaborators/{collaborator}"
    response_model = None

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    collaborator: Annotated[str, PathParam()]


class RepoGetAllCommitsRequest(PaginatedRequest[list[Commit], Commit]):
    """
    Get a list of all commits from a repository

    https://hub.allspice.io/api/swagger#/repository/repoGetAllCommits

    :param owner: owner of the repo
    :param repo: name of the repo
    :param sha: SHA or branch to start listing commits from (usually 'master')
    :param path: filepath of a file/dir
    :param stat: include diff stats for every commit (disable for speedup, default 'true')
    :param verification: include verification for every commit (disable for speedup, default 'true')
    :param files: include a list of affected files for every commit (disable for speedup, default 'true')
    :param page: page number of results to return (1-based)
    :param limit: page size of results (ignored if used with 'path')
    :param not_: commits that match the given specifier will not be listed.
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/commits"
    response_model = list[Commit]

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    sha: Annotated[str | None, QueryParam()] = None
    path: Annotated[str | None, QueryParam()] = None
    stat: Annotated[bool | None, QueryParam()] = None
    verification: Annotated[bool | None, QueryParam()] = None
    files: Annotated[bool | None, QueryParam()] = None
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None
    not_: Annotated[str | None, QueryParam(api_name="not")] = None


class RepoGetCombinedStatusByRefRequest(PaginatedRequest[CombinedStatus, CommitStatus]):
    """
    Get a commit's combined status, by branch/tag/commit reference

    https://hub.allspice.io/api/swagger#/repository/repoGetCombinedStatusByRef

    :param owner: owner of the repo
    :param repo: name of the repo
    :param ref: name of branch/tag/commit
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/commits/{ref}/status"
    response_model = CombinedStatus
    _page_items_attr = "statuses"

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    ref: Annotated[str, PathParam()]
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class RepoListStatusesByRefRequest(PaginatedRequest[list[CommitStatus], CommitStatus]):
    """
    Get a commit's statuses, by branch/tag/commit reference

    https://hub.allspice.io/api/swagger#/repository/repoListStatusesByRef

    :param owner: owner of the repo
    :param repo: name of the repo
    :param ref: name of branch/tag/commit
    :param sort: type of sort
    :param state: type of state
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/commits/{ref}/statuses"
    response_model = list[CommitStatus]

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    ref: Annotated[str, PathParam()]
    sort: Annotated[str | None, QueryParam()] = None
    state: Annotated[str | None, QueryParam()] = None
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class RepoGetContentsListRequest(ApiRequest[list[ContentsResponse]]):
    """
    Gets the metadata of all the entries of the root dir

    https://hub.allspice.io/api/swagger#/repository/repoGetContentsList

    :param owner: owner of the repo
    :param repo: name of the repo
    :param ref: The name of the commit/branch/tag. Default to the repository's default branch.
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/contents"
    response_model = list[ContentsResponse]

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    ref: Annotated[str | None, QueryParam()] = None


class RepoGetContentsRequest(ApiRequest[ContentsResponseOrList]):
    """
    Gets the metadata and contents (if a file) of an entry in a repository, or a list of entries if a dir

    https://hub.allspice.io/api/swagger#/repository/repoGetContents

    :param owner: owner of the repo
    :param repo: name of the repo
    :param filepath: path of the dir, file, symlink or submodule in the repo
    :param ref: The name of the commit/branch/tag. Default to the repository's default branch.
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/contents/{filepath}"
    response_model = ContentsResponseOrList

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    filepath: Annotated[str, PathParam()]
    ref: Annotated[str | None, QueryParam()] = None


class RepoUpdateFileRequest(ApiRequest[FileResponse]):
    """
    Update a file in a repository

    https://hub.allspice.io/api/swagger#/repository/repoUpdateFile

    :param owner: owner of the repo
    :param repo: name of the repo
    :param filepath: path of the file to update
    """
    method = "PUT"
    request_path = "/repos/{owner}/{repo}/contents/{filepath}"
    response_model = FileResponse

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    filepath: Annotated[str, PathParam()]
    body: Annotated[UpdateFileOptions, JSONBody()]


class RepoCreateFileRequest(ApiRequest[FileResponse]):
    """
    Create a file in a repository

    https://hub.allspice.io/api/swagger#/repository/repoCreateFile

    :param owner: owner of the repo
    :param repo: name of the repo
    :param filepath: path of the file to create
    """
    method = "POST"
    request_path = "/repos/{owner}/{repo}/contents/{filepath}"
    response_model = FileResponse

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    filepath: Annotated[str, PathParam()]
    body: Annotated[CreateFileOptions, JSONBody()]


class RepoDeleteFileRequest(ApiRequest[FileDeleteResponse]):
    """
    Delete a file in a repository

    https://hub.allspice.io/api/swagger#/repository/repoDeleteFile

    :param owner: owner of the repo
    :param repo: name of the repo
    :param filepath: path of the file to delete
    """
    method = "DELETE"
    request_path = "/repos/{owner}/{repo}/contents/{filepath}"
    response_model = FileDeleteResponse

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    filepath: Annotated[str, PathParam()]
    body: Annotated[DeleteFileOptions, JSONBody()]


class RepoGetTreeRequest(PaginatedRequest[GitTreeResponse, GitEntry]):
    """
    Gets the tree of a repository.

    https://hub.allspice.io/api/swagger#/repository/repoGetTree

    :param owner: owner of the repo
    :param repo: name of the repo
    :param sha: sha of the commit
    :param recursive: show all directories and files
    :param page: page number; the 'truncated' field in the response will be true if there are still more items after this page, false if the last page
    :param per_page: number of items per page
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/git/trees/{sha}"
    response_model = GitTreeResponse
    _page_items_attr = "tree"

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    sha: Annotated[str, PathParam()]
    recursive: Annotated[bool | None, QueryParam()] = None
    page: Annotated[int | None, QueryParam()] = None
    per_page: Annotated[int | None, QueryParam()] = None


class RepoListHooksRequest(PaginatedRequest[list[Hook], Hook]):
    """
    List the hooks in a repository

    https://hub.allspice.io/api/swagger#/repository/repoListHooks

    :param owner: owner of the repo
    :param repo: name of the repo
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/hooks"
    response_model = list[Hook]

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class RepoCreateHookRequest(ApiRequest[Hook]):
    """
    Create a hook

    https://hub.allspice.io/api/swagger#/repository/repoCreateHook

    :param owner: owner of the repo
    :param repo: name of the repo
    """
    method = "POST"
    request_path = "/repos/{owner}/{repo}/hooks"
    response_model = Hook

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    body: Annotated[CreateHookOption, JSONBody()]


class RepoDeleteHookRequest(ApiRequest[None]):
    """
    Delete a hook in a repository

    https://hub.allspice.io/api/swagger#/repository/repoDeleteHook

    :param owner: owner of the repo
    :param repo: name of the repo
    :param id: id of the hook to delete
    """
    method = "DELETE"
    request_path = "/repos/{owner}/{repo}/hooks/{id}"
    response_model = None

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    id: Annotated[int, PathParam()]


class IssueListIssuesRequest(PaginatedRequest[list[Issue], Issue]):
    """
    List a repository's issues

    https://hub.allspice.io/api/swagger#/issue/issueListIssues

    :param owner: owner of the repo
    :param repo: name of the repo
    :param state: whether issue is open or closed
    :param labels: comma separated list of labels. Fetch only issues that have any of this labels. Non existent labels are discarded
    :param q: search string
    :param type: filter by type (issues / pulls) if set
    :param milestones: comma separated list of milestone names or ids. It uses names and fall back to ids. Fetch only issues that have any of this milestones. Non existent milestones are discarded
    :param since: Only show items updated after the given time. This is a timestamp in RFC 3339 format
    :param before: Only show items updated before the given time. This is a timestamp in RFC 3339 format
    :param created_by: Only show items which were created by the given user
    :param assigned_by: Only show items for which the given user is assigned
    :param mentioned_by: Only show items in which the given user was mentioned
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/issues"
    response_model = list[Issue]

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    state: Annotated[StateTypeFilter | None, QueryParam()] = None
    labels: Annotated[str | None, QueryParam()] = None
    q: Annotated[str | None, QueryParam()] = None
    type: Annotated[str | None, QueryParam()] = None
    milestones: Annotated[str | None, QueryParam()] = None
    since: Annotated[str | None, QueryParam()] = None
    before: Annotated[str | None, QueryParam()] = None
    created_by: Annotated[str | None, QueryParam()] = None
    assigned_by: Annotated[str | None, QueryParam()] = None
    mentioned_by: Annotated[str | None, QueryParam()] = None
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class IssueCreateIssueRequest(ApiRequest[Issue]):
    """
    Create an issue. If using deadline only the date will be taken into account, and time of day ignored.

    https://hub.allspice.io/api/swagger#/issue/issueCreateIssue

    :param owner: owner of the repo
    :param repo: name of the repo
    """
    method = "POST"
    request_path = "/repos/{owner}/{repo}/issues"
    response_model = Issue

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    body: Annotated[CreateIssueOption, JSONBody()]


class IssueGetCommentRequest(ApiRequest[Comment]):
    """
    Get a comment

    https://hub.allspice.io/api/swagger#/issue/issueGetComment

    :param owner: owner of the repo
    :param repo: name of the repo
    :param id: id of the comment
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/issues/comments/{id}"
    response_model = Comment

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    id: Annotated[int, PathParam()]


class IssueDeleteCommentRequest(ApiRequest[None]):
    """
    Delete a comment

    https://hub.allspice.io/api/swagger#/issue/issueDeleteComment

    :param owner: owner of the repo
    :param repo: name of the repo
    :param id: id of comment to delete
    """
    method = "DELETE"
    request_path = "/repos/{owner}/{repo}/issues/comments/{id}"
    response_model = None

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    id: Annotated[int, PathParam()]


class IssueEditCommentRequest(ApiRequest[Comment]):
    """
    Edit a comment

    https://hub.allspice.io/api/swagger#/issue/issueEditComment

    :param owner: owner of the repo
    :param repo: name of the repo
    :param id: id of the comment to edit
    """
    method = "PATCH"
    request_path = "/repos/{owner}/{repo}/issues/comments/{id}"
    response_model = Comment

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    id: Annotated[int, PathParam()]
    body: Annotated[EditIssueCommentOption, JSONBody()]


class IssueListIssueCommentAttachmentsRequest(ApiRequest[list[Attachment]]):
    """
    List comment's attachments

    https://hub.allspice.io/api/swagger#/issue/issueListIssueCommentAttachments

    :param owner: owner of the repo
    :param repo: name of the repo
    :param id: id of the comment
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/issues/comments/{id}/assets"
    response_model = list[Attachment]

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    id: Annotated[int, PathParam()]


class IssueCreateIssueCommentAttachmentRequest(ApiRequest[Attachment]):
    """
    Create a comment attachment

    https://hub.allspice.io/api/swagger#/issue/issueCreateIssueCommentAttachment

    :param owner: owner of the repo
    :param repo: name of the repo
    :param id: id of the comment
    :param name: name of the attachment
    """
    method = "POST"
    request_path = "/repos/{owner}/{repo}/issues/comments/{id}/assets"
    response_model = Attachment

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    id: Annotated[int, PathParam()]
    name: Annotated[str | None, QueryParam()] = None
    file: Annotated[bytes, FileBody(api_name="attachment")]


class IssueDeleteIssueCommentAttachmentRequest(ApiRequest[None]):
    """
    Delete a comment attachment

    https://hub.allspice.io/api/swagger#/issue/issueDeleteIssueCommentAttachment

    :param owner: owner of the repo
    :param repo: name of the repo
    :param id: id of the comment
    :param attachment_id: id of the attachment to delete
    """
    method = "DELETE"
    request_path = "/repos/{owner}/{repo}/issues/comments/{id}/assets/{attachment_id}"
    response_model = None

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    id: Annotated[int, PathParam()]
    attachment_id: Annotated[int, PathParam()]


class IssueEditIssueCommentAttachmentRequest(ApiRequest[Attachment]):
    """
    Edit a comment attachment

    https://hub.allspice.io/api/swagger#/issue/issueEditIssueCommentAttachment

    :param owner: owner of the repo
    :param repo: name of the repo
    :param id: id of the comment
    :param attachment_id: id of the attachment to edit
    """
    method = "PATCH"
    request_path = "/repos/{owner}/{repo}/issues/comments/{id}/assets/{attachment_id}"
    response_model = Attachment

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    id: Annotated[int, PathParam()]
    attachment_id: Annotated[int, PathParam()]
    body: Annotated[EditAttachmentOptions, JSONBody()]


class IssueGetIssueRequest(ApiRequest[Issue]):
    """
    Get an issue

    https://hub.allspice.io/api/swagger#/issue/issueGetIssue

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the issue to get
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/issues/{index}"
    response_model = Issue

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]


class IssueEditIssueRequest(ApiRequest[Issue]):
    """
    Edit an issue. If using deadline only the date will be taken into account, and time of day ignored.

    https://hub.allspice.io/api/swagger#/issue/issueEditIssue

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the issue to edit
    """
    method = "PATCH"
    request_path = "/repos/{owner}/{repo}/issues/{index}"
    response_model = Issue

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]
    body: Annotated[EditIssueOption, JSONBody()]


class IssueListIssueAttachmentsRequest(ApiRequest[list[Attachment]]):
    """
    List issue's attachments

    https://hub.allspice.io/api/swagger#/issue/issueListIssueAttachments

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the issue
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/issues/{index}/assets"
    response_model = list[Attachment]

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]


class IssueCreateIssueAttachmentRequest(ApiRequest[Attachment]):
    """
    Create an issue attachment

    https://hub.allspice.io/api/swagger#/issue/issueCreateIssueAttachment

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the issue
    :param name: name of the attachment
    """
    method = "POST"
    request_path = "/repos/{owner}/{repo}/issues/{index}/assets"
    response_model = Attachment

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]
    name: Annotated[str | None, QueryParam()] = None
    file: Annotated[bytes, FileBody(api_name="attachment")]


class IssueDeleteIssueAttachmentRequest(ApiRequest[None]):
    """
    Delete an issue attachment

    https://hub.allspice.io/api/swagger#/issue/issueDeleteIssueAttachment

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the issue
    :param attachment_id: id of the attachment to delete
    """
    method = "DELETE"
    request_path = "/repos/{owner}/{repo}/issues/{index}/assets/{attachment_id}"
    response_model = None

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]
    attachment_id: Annotated[int, PathParam()]


class IssueEditIssueAttachmentRequest(ApiRequest[Attachment]):
    """
    Edit an issue attachment

    https://hub.allspice.io/api/swagger#/issue/issueEditIssueAttachment

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the issue
    :param attachment_id: id of the attachment to edit
    """
    method = "PATCH"
    request_path = "/repos/{owner}/{repo}/issues/{index}/assets/{attachment_id}"
    response_model = Attachment

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]
    attachment_id: Annotated[int, PathParam()]
    body: Annotated[EditAttachmentOptions, JSONBody()]


class IssueGetCommentsRequest(ApiRequest[list[Comment]]):
    """
    List all comments on an issue

    https://hub.allspice.io/api/swagger#/issue/issueGetComments

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the issue
    :param since: if provided, only comments updated since the specified time are returned.
    :param before: if provided, only comments updated before the provided time are returned.
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/issues/{index}/comments"
    response_model = list[Comment]

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]
    since: Annotated[str | None, QueryParam()] = None
    before: Annotated[str | None, QueryParam()] = None


class IssueCreateCommentRequest(ApiRequest[Comment]):
    """
    Add a comment to an issue

    https://hub.allspice.io/api/swagger#/issue/issueCreateComment

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the issue
    """
    method = "POST"
    request_path = "/repos/{owner}/{repo}/issues/{index}/comments"
    response_model = Comment

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]
    body: Annotated[CreateIssueCommentOption, JSONBody()]


class IssueTrackedTimesRequest(PaginatedRequest[list[TrackedTime], TrackedTime]):
    """
    List an issue's tracked times

    https://hub.allspice.io/api/swagger#/issue/issueTrackedTimes

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the issue
    :param user: optional filter by user (available for issue managers)
    :param since: Only show times updated after the given time. This is a timestamp in RFC 3339 format
    :param before: Only show times updated before the given time. This is a timestamp in RFC 3339 format
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/issues/{index}/times"
    response_model = list[TrackedTime]

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]
    user: Annotated[str | None, QueryParam()] = None
    since: Annotated[str | None, QueryParam()] = None
    before: Annotated[str | None, QueryParam()] = None
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class IssueAddTimeRequest(ApiRequest[TrackedTime]):
    """
    Add tracked time to a issue

    https://hub.allspice.io/api/swagger#/issue/issueAddTime

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the issue
    """
    method = "POST"
    request_path = "/repos/{owner}/{repo}/issues/{index}/times"
    response_model = TrackedTime

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]
    body: Annotated[AddTimeOption, JSONBody()]


class IssueDeleteTimeRequest(ApiRequest[None]):
    """
    Delete specific tracked time

    https://hub.allspice.io/api/swagger#/issue/issueDeleteTime

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the issue
    :param id: id of time to delete
    """
    method = "DELETE"
    request_path = "/repos/{owner}/{repo}/issues/{index}/times/{id}"
    response_model = None

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]
    id: Annotated[int, PathParam()]


class RepoGetRawFileOrLFSRequest(ApiRequest[bytes]):
    """
    Get a file or it's LFS object from a repository

    https://hub.allspice.io/api/swagger#/repository/repoGetRawFileOrLFS

    :param owner: owner of the repo
    :param repo: name of the repo
    :param filepath: path of the file to get, it should be "{ref}/{filepath}". If there is no ref could be inferred, it will be treated as the default branch
    :param ref: The name of the commit/branch/tag. Default the repository's default branch
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/media/{filepath}"
    response_model = bytes

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    filepath: Annotated[str, PathParam()]
    ref: Annotated[str | None, QueryParam()] = None


class IssueCreateMilestoneRequest(ApiRequest[Milestone]):
    """
    Create a milestone

    https://hub.allspice.io/api/swagger#/issue/issueCreateMilestone

    :param owner: owner of the repo
    :param repo: name of the repo
    """
    method = "POST"
    request_path = "/repos/{owner}/{repo}/milestones"
    response_model = Milestone

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    body: Annotated[CreateMilestoneOption, JSONBody()]


class IssueGetMilestoneRequest(ApiRequest[Milestone]):
    """
    Get a milestone

    https://hub.allspice.io/api/swagger#/issue/issueGetMilestone

    :param owner: owner of the repo
    :param repo: name of the repo
    :param id: the milestone to get, identified by ID and if not available by name
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/milestones/{id}"
    response_model = Milestone

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    id: Annotated[str, PathParam()]


class RepoListDesignReviewsRequest(PaginatedRequest[list[DesignReview], DesignReview]):
    """
    List a repo's design reviews

    https://hub.allspice.io/api/swagger#/repository/repoListDesignReviews

    :param owner: Owner of the repo
    :param repo: Name of the repo
    :param base_branch: Filter by target base branch of the design review
    :param state: State of design review
    :param sort: Type of sort
    :param milestone: ID of the milestone
    :param labels: Label IDs
    :param poster: Filter by design review author
    :param page: Page number of results to return (1-based)
    :param limit: Page size of results
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/pulls"
    response_model = list[DesignReview]

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    base_branch: Annotated[str | None, QueryParam()] = None
    state: Annotated[StateTypeFilter | None, QueryParam()] = None
    sort: Annotated[str | None, QueryParam()] = None
    milestone: Annotated[int | None, QueryParam()] = None
    labels: Annotated[list[int] | None, QueryParam()] = None
    poster: Annotated[str | None, QueryParam()] = None
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class RepoCreateDesignReviewRequest(ApiRequest[DesignReview]):
    """
    Create a design review

    https://hub.allspice.io/api/swagger#/repository/repoCreateDesignReview

    :param owner: owner of the repo
    :param repo: name of the repo
    """
    method = "POST"
    request_path = "/repos/{owner}/{repo}/pulls"
    response_model = DesignReview

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    body: Annotated[CreateDesignReviewOption, JSONBody()]


class RepoGetDesignReviewRequest(ApiRequest[DesignReview]):
    """
    Get a design review

    https://hub.allspice.io/api/swagger#/repository/repoGetDesignReview

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the design review to get
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/pulls/{index}"
    response_model = DesignReview

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]


class RepoEditDesignReviewRequest(ApiRequest[DesignReview]):
    """
    Update a design review. If using deadline only the date will be taken into account, and time of day ignored.

    https://hub.allspice.io/api/swagger#/repository/repoEditDesignReview

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the design review to edit
    """
    method = "PATCH"
    request_path = "/repos/{owner}/{repo}/pulls/{index}"
    response_model = DesignReview

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]
    body: Annotated[EditDesignReviewOption, JSONBody()]


class RepoMergeDesignReviewRequest(ApiRequest[None]):
    """
    Merge a design review

    https://hub.allspice.io/api/swagger#/repository/repoMergeDesignReview

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the design review to merge
    """
    method = "POST"
    request_path = "/repos/{owner}/{repo}/pulls/{index}/merge"
    response_model = None

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]
    body: Annotated[MergeDesignReviewOption, JSONBody()]


class RepoListDesignReviewReviewsRequest(PaginatedRequest[list[DesignReviewReview], DesignReviewReview]):
    """
    List all reviews for a design review

    https://hub.allspice.io/api/swagger#/repository/repoListDesignReviewReviews

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the design review
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/pulls/{index}/reviews"
    response_model = list[DesignReviewReview]

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class RepoCreateDesignReviewReviewRequest(ApiRequest[DesignReviewReview]):
    """
    Create a review to an design review

    https://hub.allspice.io/api/swagger#/repository/repoCreateDesignReviewReview

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the design review
    """
    method = "POST"
    request_path = "/repos/{owner}/{repo}/pulls/{index}/reviews"
    response_model = DesignReviewReview

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]
    body: Annotated[CreateDesignReviewReviewOptions, JSONBody()]


class RepoSubmitDesignReviewReviewRequest(ApiRequest[DesignReviewReview]):
    """
    Submit a pending review to an design review

    https://hub.allspice.io/api/swagger#/repository/repoSubmitDesignReviewReview

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the design review
    :param id: id of the review
    """
    method = "POST"
    request_path = "/repos/{owner}/{repo}/pulls/{index}/reviews/{id}"
    response_model = DesignReviewReview

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]
    id: Annotated[int, PathParam()]
    body: Annotated[SubmitDesignReviewReviewOptions, JSONBody()]


class RepoDeleteDesignReviewReviewRequest(ApiRequest[None]):
    """
    Delete a specific review from a design review

    https://hub.allspice.io/api/swagger#/repository/repoDeleteDesignReviewReview

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the design review
    :param id: id of the review
    """
    method = "DELETE"
    request_path = "/repos/{owner}/{repo}/pulls/{index}/reviews/{id}"
    response_model = None

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]
    id: Annotated[int, PathParam()]


class RepoGetDesignReviewReviewCommentsRequest(ApiRequest[list[DesignReviewReviewComment]]):
    """
    Get a specific review for a design review

    https://hub.allspice.io/api/swagger#/repository/repoGetDesignReviewReviewComments

    :param owner: owner of the repo
    :param repo: name of the repo
    :param index: index of the design review
    :param id: id of the review
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/pulls/{index}/reviews/{id}/comments"
    response_model = list[DesignReviewReviewComment]

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    index: Annotated[int, PathParam()]
    id: Annotated[int, PathParam()]


class RepoListReleasesRequest(PaginatedRequest[list[Release], Release]):
    """
    List a repo's releases

    https://hub.allspice.io/api/swagger#/repository/repoListReleases

    :param owner: owner of the repo
    :param repo: name of the repo
    :param draft: filter (exclude / include) drafts, if you dont have repo write access none will show
    :param pre_release: filter (exclude / include) pre-releases
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/releases"
    response_model = list[Release]

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    draft: Annotated[bool | None, QueryParam()] = None
    pre_release: Annotated[bool | None, QueryParam(api_name="pre-release")] = None
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class RepoCreateReleaseRequest(ApiRequest[Release]):
    """
    Create a release

    https://hub.allspice.io/api/swagger#/repository/repoCreateRelease

    :param owner: owner of the repo
    :param repo: name of the repo
    """
    method = "POST"
    request_path = "/repos/{owner}/{repo}/releases"
    response_model = Release

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    body: Annotated[CreateReleaseOption, JSONBody()]


class RepoGetLatestReleaseRequest(ApiRequest[Release]):
    """
    Gets the most recent non-prerelease, non-draft release of a repository, sorted by created_at

    https://hub.allspice.io/api/swagger#/repository/repoGetLatestRelease

    :param owner: owner of the repo
    :param repo: name of the repo
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/releases/latest"
    response_model = Release

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]


class RepoGetReleaseByTagRequest(ApiRequest[Release]):
    """
    Get a release by tag name

    https://hub.allspice.io/api/swagger#/repository/repoGetReleaseByTag

    :param owner: owner of the repo
    :param repo: name of the repo
    :param tag: tag name of the release to get
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/releases/tags/{tag}"
    response_model = Release

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    tag: Annotated[str, PathParam()]


class RepoGetReleaseRequest(ApiRequest[Release]):
    """
    Get a release

    https://hub.allspice.io/api/swagger#/repository/repoGetRelease

    :param owner: owner of the repo
    :param repo: name of the repo
    :param id: id of the release to get
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/releases/{id}"
    response_model = Release

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    id: Annotated[int, PathParam()]


class RepoDeleteReleaseRequest(ApiRequest[None]):
    """
    Delete a release

    https://hub.allspice.io/api/swagger#/repository/repoDeleteRelease

    :param owner: owner of the repo
    :param repo: name of the repo
    :param id: id of the release to delete
    """
    method = "DELETE"
    request_path = "/repos/{owner}/{repo}/releases/{id}"
    response_model = None

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    id: Annotated[int, PathParam()]


class RepoEditReleaseRequest(ApiRequest[Release]):
    """
    Update a release

    https://hub.allspice.io/api/swagger#/repository/repoEditRelease

    :param owner: owner of the repo
    :param repo: name of the repo
    :param id: id of the release to edit
    """
    method = "PATCH"
    request_path = "/repos/{owner}/{repo}/releases/{id}"
    response_model = Release

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    id: Annotated[int, PathParam()]
    body: Annotated[EditReleaseOption, JSONBody()]


class RepoCreateReleaseAttachmentRequest(ApiRequest[Attachment]):
    """
    Create a release attachment

    https://hub.allspice.io/api/swagger#/repository/repoCreateReleaseAttachment

    :param owner: owner of the repo
    :param repo: name of the repo
    :param id: id of the release
    :param name: name of the attachment
    """
    method = "POST"
    request_path = "/repos/{owner}/{repo}/releases/{id}/assets"
    response_model = Attachment

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    id: Annotated[int, PathParam()]
    name: Annotated[str | None, QueryParam()] = None
    file: Annotated[bytes, FileBody(api_name="attachment")]


class RepoGetReleaseAttachmentRequest(ApiRequest[Attachment]):
    """
    Get a release attachment

    https://hub.allspice.io/api/swagger#/repository/repoGetReleaseAttachment

    :param owner: owner of the repo
    :param repo: name of the repo
    :param id: id of the release
    :param attachment_id: id of the attachment to get
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}"
    response_model = Attachment

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    id: Annotated[int, PathParam()]
    attachment_id: Annotated[int, PathParam()]


class RepoDeleteReleaseAttachmentRequest(ApiRequest[None]):
    """
    Delete a release attachment

    https://hub.allspice.io/api/swagger#/repository/repoDeleteReleaseAttachment

    :param owner: owner of the repo
    :param repo: name of the repo
    :param id: id of the release
    :param attachment_id: id of the attachment to delete
    """
    method = "DELETE"
    request_path = "/repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}"
    response_model = None

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    id: Annotated[int, PathParam()]
    attachment_id: Annotated[int, PathParam()]


class RepoEditReleaseAttachmentRequest(ApiRequest[Attachment]):
    """
    Edit a release attachment

    https://hub.allspice.io/api/swagger#/repository/repoEditReleaseAttachment

    :param owner: owner of the repo
    :param repo: name of the repo
    :param id: id of the release
    :param attachment_id: id of the attachment to edit
    """
    method = "PATCH"
    request_path = "/repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}"
    response_model = Attachment

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    id: Annotated[int, PathParam()]
    attachment_id: Annotated[int, PathParam()]
    body: Annotated[EditAttachmentOptions, JSONBody()]


class RepoListStatusesRequest(PaginatedRequest[list[CommitStatus], CommitStatus]):
    """
    Get a commit's statuses

    https://hub.allspice.io/api/swagger#/repository/repoListStatuses

    :param owner: owner of the repo
    :param repo: name of the repo
    :param sha: sha of the commit
    :param sort: type of sort
    :param state: type of state
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/statuses/{sha}"
    response_model = list[CommitStatus]

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    sha: Annotated[str, PathParam()]
    sort: Annotated[str | None, QueryParam()] = None
    state: Annotated[str | None, QueryParam()] = None
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class RepoCreateStatusRequest(ApiRequest[CommitStatus]):
    """
    Create a commit status

    https://hub.allspice.io/api/swagger#/repository/repoCreateStatus

    :param owner: owner of the repo
    :param repo: name of the repo
    :param sha: sha of the commit
    """
    method = "POST"
    request_path = "/repos/{owner}/{repo}/statuses/{sha}"
    response_model = CommitStatus

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    sha: Annotated[str, PathParam()]
    body: Annotated[CreateStatusOption, JSONBody()]


class RepoTrackedTimesRequest(PaginatedRequest[list[TrackedTime], TrackedTime]):
    """
    List a repo's tracked times

    https://hub.allspice.io/api/swagger#/repository/repoTrackedTimes

    :param owner: owner of the repo
    :param repo: name of the repo
    :param user: optional filter by user (available for issue managers)
    :param since: Only show times updated after the given time. This is a timestamp in RFC 3339 format
    :param before: Only show times updated before the given time. This is a timestamp in RFC 3339 format
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/times"
    response_model = list[TrackedTime]

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    user: Annotated[str | None, QueryParam()] = None
    since: Annotated[str | None, QueryParam()] = None
    before: Annotated[str | None, QueryParam()] = None
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class UserTrackedTimesRequest(ApiRequest[list[TrackedTime]]):
    """
    List a user's tracked times in a repo

    https://hub.allspice.io/api/swagger#/repository/userTrackedTimes

    :param owner: owner of the repo
    :param repo: name of the repo
    :param user: username of user
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/times/{user}"
    response_model = list[TrackedTime]

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    user: Annotated[str, PathParam()]


class RepoListTopicsRequest(PaginatedRequest[TopicNamesResponse, str]):
    """
    Get list of topics that a repository has

    https://hub.allspice.io/api/swagger#/repository/repoListTopics

    :param owner: owner of the repo
    :param repo: name of the repo
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/topics"
    response_model = TopicNamesResponse
    _page_items_attr = "topics"

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class RepoAddTopicRequest(ApiRequest[None]):
    """
    Add a topic to a repository

    https://hub.allspice.io/api/swagger#/repository/repoAddTopic

    :param owner: owner of the repo
    :param repo: name of the repo
    :param topic: name of the topic to add
    """
    method = "PUT"
    request_path = "/repos/{owner}/{repo}/topics/{topic}"
    response_model = None

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    topic: Annotated[str, PathParam()]


class RepoTransferRequest(ApiRequest[Repository]):
    """
    Transfer a repo ownership

    https://hub.allspice.io/api/swagger#/repository/repoTransfer

    :param owner: owner of the repo to transfer
    :param repo: name of the repo to transfer
    """
    method = "POST"
    request_path = "/repos/{owner}/{repo}/transfer"
    response_model = Repository

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    body: Annotated[TransferRepoOption, JSONBody()]


class OrgGetTeamRequest(ApiRequest[Team]):
    """
    Get a team

    https://hub.allspice.io/api/swagger#/organization/orgGetTeam

    :param id: id of the team to get
    """
    method = "GET"
    request_path = "/teams/{id}"
    response_model = Team

    id: Annotated[int, PathParam()]


class OrgDeleteTeamRequest(ApiRequest[None]):
    """
    Delete a team

    https://hub.allspice.io/api/swagger#/organization/orgDeleteTeam

    :param id: id of the team to delete
    """
    method = "DELETE"
    request_path = "/teams/{id}"
    response_model = None

    id: Annotated[int, PathParam()]


class OrgEditTeamRequest(ApiRequest[Team]):
    """
    Edit a team

    https://hub.allspice.io/api/swagger#/organization/orgEditTeam

    :param id: id of the team to edit
    """
    method = "PATCH"
    request_path = "/teams/{id}"
    response_model = Team

    id: Annotated[int, PathParam()]
    body: Annotated[EditTeamOption, JSONBody()]


class OrgListTeamMembersRequest(PaginatedRequest[list[User], User]):
    """
    List a team's members

    https://hub.allspice.io/api/swagger#/organization/orgListTeamMembers

    :param id: id of the team
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/teams/{id}/members"
    response_model = list[User]

    id: Annotated[int, PathParam()]
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class OrgAddTeamMemberRequest(ApiRequest[None]):
    """
    Add a team member

    https://hub.allspice.io/api/swagger#/organization/orgAddTeamMember

    :param id: id of the team
    :param username: username of the user to add
    """
    method = "PUT"
    request_path = "/teams/{id}/members/{username}"
    response_model = None

    id: Annotated[int, PathParam()]
    username: Annotated[str, PathParam()]


class OrgRemoveTeamMemberRequest(ApiRequest[None]):
    """
    Remove a team member

    https://hub.allspice.io/api/swagger#/organization/orgRemoveTeamMember

    :param id: id of the team
    :param username: username of the user to remove
    """
    method = "DELETE"
    request_path = "/teams/{id}/members/{username}"
    response_model = None

    id: Annotated[int, PathParam()]
    username: Annotated[str, PathParam()]


class OrgListTeamReposRequest(PaginatedRequest[list[Repository], Repository]):
    """
    List a team's repos

    https://hub.allspice.io/api/swagger#/organization/orgListTeamRepos

    :param id: id of the team
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/teams/{id}/repos"
    response_model = list[Repository]

    id: Annotated[int, PathParam()]
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class OrgAddTeamRepositoryRequest(ApiRequest[None]):
    """
    Add a repository to a team

    https://hub.allspice.io/api/swagger#/organization/orgAddTeamRepository

    :param id: id of the team
    :param org: organization that owns the repo to add
    :param repo: name of the repo to add
    """
    method = "PUT"
    request_path = "/teams/{id}/repos/{org}/{repo}"
    response_model = None

    id: Annotated[int, PathParam()]
    org: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]


class UserGetCurrentRequest(ApiRequest[User]):
    """
    Get the authenticated user

    https://hub.allspice.io/api/swagger#/user/userGetCurrent
    """
    method = "GET"
    request_path = "/user"
    response_model = User


class UserListEmailsRequest(ApiRequest[list[Email]]):
    """
    List the authenticated user's email addresses

    https://hub.allspice.io/api/swagger#/user/userListEmails
    """
    method = "GET"
    request_path = "/user/emails"
    response_model = list[Email]


class UserCurrentListReposRequest(PaginatedRequest[list[Repository], Repository]):
    """
    List the repos that the authenticated user owns

    https://hub.allspice.io/api/swagger#/user/userCurrentListRepos

    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/user/repos"
    response_model = list[Repository]

    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class CreateCurrentUserRepoRequest(ApiRequest[Repository]):
    """
    Create a repository

    https://hub.allspice.io/api/swagger#/repository/createCurrentUserRepo
    """
    method = "POST"
    request_path = "/user/repos"
    response_model = Repository

    body: Annotated[CreateRepoOption, JSONBody()]


class UserListTeamsRequest(PaginatedRequest[list[Team], Team]):
    """
    List all the teams a user belongs to

    https://hub.allspice.io/api/swagger#/user/userListTeams

    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/user/teams"
    response_model = list[Team]

    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class UserGetRequest(ApiRequest[User]):
    """
    Get a user

    https://hub.allspice.io/api/swagger#/user/userGet

    :param username: username of user to get
    """
    method = "GET"
    request_path = "/users/{username}"
    response_model = User

    username: Annotated[str, PathParam()]


class UserGetHeatmapDataRequest(ApiRequest[list[UserHeatmapData]]):
    """
    Get a user's heatmap

    https://hub.allspice.io/api/swagger#/user/userGetHeatmapData

    :param username: username of user to get
    """
    method = "GET"
    request_path = "/users/{username}/heatmap"
    response_model = list[UserHeatmapData]

    username: Annotated[str, PathParam()]


class OrgListUserOrgsRequest(PaginatedRequest[list[Organization], Organization]):
    """
    List a user's organizations

    https://hub.allspice.io/api/swagger#/organization/orgListUserOrgs

    :param username: username of user
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/users/{username}/orgs"
    response_model = list[Organization]

    username: Annotated[str, PathParam()]
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class UserListReposRequest(PaginatedRequest[list[Repository], Repository]):
    """
    List the repos owned by the given user

    https://hub.allspice.io/api/swagger#/user/userListRepos

    :param username: username of user
    :param page: page number of results to return (1-based)
    :param limit: page size of results
    """
    method = "GET"
    request_path = "/users/{username}/repos"
    response_model = list[Repository]

    username: Annotated[str, PathParam()]
    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None


class GetVersionRequest(ApiRequest[ServerVersion]):
    """
    Returns the version of the AllSpice application

    https://hub.allspice.io/api/swagger#/miscellaneous/getVersion
    """
    method = "GET"
    request_path = "/version"
    response_model = ServerVersion
