# @generated by open-api-generator — do not edit by hand

from __future__ import annotations

from typing import Any, Final, Literal, NewType

from pydantic import AwareDatetime, ConfigDict

from allspice.base import InputModel, OpenEnum, ReadOnlyModel
from allspice.entities import (
    AttachmentEntity,
    BranchEntity,
    CommentEntity,
    CommitEntity,
    DesignReviewEntity,
    DesignReviewReviewEntity,
    IssueEntity,
    MilestoneEntity,
    OrganizationEntity,
    ReleaseEntity,
    RepositoryEntity,
    TeamEntity,
    UserEntity,
)

class APIError(ReadOnlyModel):
    category: Final[str | None] = None
    'Optional error category. "render" indicates a hardware render failure; omitted for uncategorized errors.'
    message: Final[str | None] = None
    url: Final[str | None] = None

class AccessMode(OpenEnum):
    UNKNOWN = 'unknown'
    none = 'none'
    read = 'read'
    write = 'write'
    admin = 'admin'
    owner = 'owner'

class AccessModeOption(OpenEnum):
    UNKNOWN = 'unknown'
    read = 'read'
    write = 'write'
    admin = 'admin'

class AddTimeOption(InputModel):
    created: AwareDatetime | None = None
    time: int
    'time in seconds'
    user_name: str | None = None
    'User who spent the time (optional)'

class Attachment(AttachmentEntity):
    browser_download_url: Final[str]
    created_at: Final[AwareDatetime]
    download_count: Final[int]
    id: Final[int]
    name: str
    size: Final[int]
    uuid: Final[str]

class CommitAffectedFiles(ReadOnlyModel):
    filename: Final[str | None] = None
    status: Final[str | None] = None

class CommitDateOptions(InputModel):
    author: AwareDatetime | None = None
    committer: AwareDatetime | None = None

class CommitMeta(ReadOnlyModel):
    created: Final[AwareDatetime | None] = None
    sha: Final[str | None] = None
    url: Final[str | None] = None

class CommitStats(ReadOnlyModel):
    additions: Final[int | None] = None
    deletions: Final[int | None] = None
    total: Final[int | None] = None

class CommitStatusState(OpenEnum):
    UNKNOWN = 'unknown'
    pending = 'pending'
    success = 'success'
    error = 'error'
    failure = 'failure'
    warning = 'warning'

class CommitUser(ReadOnlyModel):
    date: Final[str | None] = None
    email: Final[str | None] = None
    name: Final[str | None] = None

class CreateBranchRepoOption(InputModel):
    new_branch_name: str
    'Name of the branch to create'
    old_branch_name: str | None = None
    'Deprecated: true\nName of the old branch to create from'
    old_ref_name: str | None = None
    'Name of the old branch/tag/commit to create from'

class Type(OpenEnum):
    UNKNOWN = 'unknown'
    dingtalk = 'dingtalk'
    discord = 'discord'
    gitea = 'gitea'
    gogs = 'gogs'
    msteams = 'msteams'
    slack = 'slack'
    telegram = 'telegram'
    feishu = 'feishu'
    wechatwork = 'wechatwork'
    packagist = 'packagist'
CreateHookOptionConfig = dict[str, str]

class CreateIssueCommentOption(InputModel):
    body: str

class CreateIssueOption(InputModel):
    assignee: str | None = None
    'deprecated'
    assignees: list[str] | None = None
    body: str | None = None
    closed: bool | None = None
    due_date: AwareDatetime | None = None
    labels: list[int] | None = None
    'list of label ids'
    milestone: int | None = None
    'milestone id'
    ref: str | None = None
    title: str

class CreateDesignReviewOption(InputModel):
    assignee: str | None = None
    assignees: list[str] | None = None
    base: str | None = None
    body: str | None = None
    due_date: AwareDatetime | None = None
    head: str | None = None
    labels: list[int] | None = None
    milestone: int | None = None
    reviewers: list[str] | None = None
    team_reviewers: list[str] | None = None
    title: str | None = None

class CreateDesignReviewReviewComment(InputModel):
    body: str | None = None
    new_position: int | None = None
    'if comment to new file line or 0'
    old_position: int | None = None
    'if comment to old file line or 0'
    path: str | None = None
    'the tree path'
    sub_path: str | None = None

class CreateReleaseOption(InputModel):
    body: str | None = None
    draft: bool | None = None
    name: str | None = None
    prerelease: bool | None = None
    tag_name: str
    target_commitish: str | None = None

class ObjectFormatName(OpenEnum):
    UNKNOWN = 'unknown'
    sha1 = 'sha1'
    sha256 = 'sha256'

class TrustModel(OpenEnum):
    UNKNOWN = 'unknown'
    default = 'default'
    collaborator = 'collaborator'
    committer = 'committer'
    collaboratorcommitter = 'collaboratorcommitter'

class CreateRepoOption(InputModel):
    auto_init: bool | None = None
    'Whether the repository should be auto-initialized?'
    create_develop_branch: bool | None = None
    'Whether to initialize the repository with a secondary develop branch'
    default_branch: str | None = None
    'DefaultBranch of the repository (used when initializes and in template)'
    description: str | None = None
    'Description of the repository to create'
    gitignores: str | None = None
    'Gitignores to use'
    issue_labels: str | None = None
    'Label-Set to use'
    license: str | None = None
    'License to use'
    name: str
    'Name of the repository to create'
    object_format_name: ObjectFormatName | None = None
    'ObjectFormatName of the underlying git repository'
    private: bool | None = None
    'Whether the repository is private'
    readme: str | None = None
    'Readme of the repository to create'
    template: bool | None = None
    'Whether the repository is template'
    trust_model: TrustModel | None = None
    'TrustModel of the repository'

class CreateStatusOption(InputModel):
    context: str | None = None
    description: str | None = None
    state: CommitStatusState | None = None
    target_url: str | None = None

class CreateTeamOption(InputModel):
    can_create_org_repo: bool | None = None
    description: str | None = None
    includes_all_repositories: bool | None = None
    name: str
    permission: AccessModeOption | None = None
    units: list[str] | None = None
    units_map: dict[str, str] | None = None

class EditAttachmentOptions(InputModel):
    name: str | None = None

class EditIssueCommentOption(InputModel):
    body: str

class EditReleaseOption(InputModel):
    body: str | None = None
    draft: bool | None = None
    name: str | None = None
    prerelease: bool | None = None
    tag_name: str | None = None
    target_commitish: str | None = None

class EditTeamOption(InputModel):
    can_create_org_repo: bool | None = None
    description: str | None = None
    includes_all_repositories: bool | None = None
    name: str | None = None
    permission: AccessModeOption | None = None
    units: list[str] | None = None
    units_map: dict[str, str] | None = None

class Email(ReadOnlyModel):
    email: Final[str | None] = None
    primary: Final[bool | None] = None
    user_id: Final[int | None] = None
    username: Final[str | None] = None
    verified: Final[bool | None] = None

class ExternalTracker(ReadOnlyModel):
    external_tracker_format: Final[str | None] = None
    'External Issue Tracker URL Format. Use the placeholders {user}, {repo} and {index} for the username, repository name and issue index.'
    external_tracker_regexp_pattern: Final[str | None] = None
    'External Issue Tracker issue regular expression'
    external_tracker_style: Final[str | None] = None
    'External Issue Tracker Number Format, either `numeric`, `alphanumeric`, or `regexp`'
    external_tracker_url: Final[str | None] = None
    'URL of external issue tracker.'

class ExternalWiki(ReadOnlyModel):
    external_wiki_url: Final[str | None] = None
    'URL of external wiki.'

class FileCommitResponse(ReadOnlyModel):
    author: Final[CommitUser | None] = None
    committer: Final[CommitUser | None] = None
    created: Final[AwareDatetime | None] = None
    html_url: Final[str | None] = None
    message: Final[str | None] = None
    parents: Final[list[CommitMeta] | None] = None
    sha: Final[str | None] = None
    tree: Final[CommitMeta | None] = None
    url: Final[str | None] = None

class FileLinksResponse(ReadOnlyModel):
    git: Final[str | None] = None
    html: Final[str | None] = None
    self: Final[str | None] = None

class GitEntry(ReadOnlyModel):
    mode: Final[str]
    path: Final[str]
    sha: Final[str]
    size: Final[int]
    type: Final[str]
    url: Final[str]

class GitTreeResponse(ReadOnlyModel):
    page: Final[int | None] = None
    sha: Final[str | None] = None
    total_count: Final[int | None] = None
    tree: Final[list[GitEntry] | None] = None
    truncated: Final[bool | None] = None
    url: Final[str | None] = None

class Hook(ReadOnlyModel):
    active: Final[bool | None] = None
    authorization_header: Final[str | None] = None
    branch_filter: Final[str | None] = None
    config: Final[dict[str, str] | None] = None
    created_at: Final[AwareDatetime | None] = None
    events: Final[list[str] | None] = None
    id: Final[int | None] = None
    type: Final[str | None] = None
    updated_at: Final[AwareDatetime | None] = None

class Identity(InputModel):
    email: str | None = None
    name: str | None = None

class InternalTracker(ReadOnlyModel):
    allow_only_contributors_to_track_time: Final[bool | None] = None
    'Let only contributors track time (Built-in issue tracker)'
    enable_issue_dependencies: Final[bool | None] = None
    'Enable dependencies for issues and design reviews (Built-in issue tracker)'
    enable_time_tracker: Final[bool | None] = None
    'Enable time tracking (Built-in issue tracker)'

class Label(ReadOnlyModel):
    color: Final[str | None] = None
    description: Final[str | None] = None
    exclusive: Final[bool | None] = None
    id: Final[int | None] = None
    is_archived: Final[bool | None] = None
    name: Final[str | None] = None
    url: Final[str | None] = None

class Do(OpenEnum):
    UNKNOWN = 'unknown'
    merge = 'merge'
    rebase = 'rebase'
    rebase_merge = 'rebase-merge'
    squash = 'squash'
    fast_forward_only = 'fast-forward-only'
    manually_merged = 'manually-merged'

class MergeDesignReviewOption(InputModel):
    do: Do
    merge_commit_id: str | None = None
    merge_message_field: str | None = None
    merge_title_field: str | None = None
    delete_branch_after_merge: bool | None = None
    force_merge: bool | None = None
    head_commit_id: str | None = None
    merge_when_checks_succeed: bool | None = None

class PayloadUser(ReadOnlyModel):
    email: Final[str | None] = None
    name: Final[str | None] = None
    'Full name of the commit author'
    username: Final[str | None] = None

class Permission(ReadOnlyModel):
    admin: Final[bool | None] = None
    pull: Final[bool | None] = None
    push: Final[bool | None] = None

class ProjectWarning(ReadOnlyModel):
    detail: Final[str | None] = None
    file_path: Final[str | None] = None
ProjectWarnings = list[ProjectWarning]

class DesignReviewMeta(ReadOnlyModel):
    draft: Final[bool | None] = None
    html_url: Final[str | None] = None
    merged: Final[bool | None] = None
    merged_at: Final[AwareDatetime | None] = None

class RepositoryMeta(ReadOnlyModel):
    full_name: Final[str | None] = None
    id: Final[int | None] = None
    name: Final[str | None] = None
    owner: Final[str | None] = None

class ReviewStateType(OpenEnum):
    UNKNOWN = 'unknown'
    approved = 'APPROVED'
    pending = 'PENDING'
    comment = 'COMMENT'
    request_changes = 'REQUEST_CHANGES'
    request_review = 'REQUEST_REVIEW'

class ServerVersion(ReadOnlyModel):
    version: Final[str | None] = None

class StateType(OpenEnum):
    UNKNOWN = 'unknown'
    open = 'open'
    closed = 'closed'

class StateTypeFilter(OpenEnum):
    UNKNOWN = 'unknown'
    open = 'open'
    closed = 'closed'
    all = 'all'

class SubmitDesignReviewReviewOptions(InputModel):
    body: str | None = None
    event: ReviewStateType | None = None
TimeStamp = NewType('TimeStamp', int)

class TopicNamesResponse(ReadOnlyModel):
    topics: Final[list[str] | None] = None

class TransferRepoOption(InputModel):
    new_owner: str
    team_ids: list[int] | None = None
    'ID of the team or teams to add to the repository. Teams can only be added to organization-owned repositories.'

class UpdateFileOptions(InputModel):
    author: Identity | None = None
    branch: str | None = None
    'branch (optional) to base this file from. if not given, the default branch is used'
    committer: Identity | None = None
    content: str
    'content must be base64 encoded'
    dates: CommitDateOptions | None = None
    from_path: str | None = None
    'from_path (optional) is the path of the original file which will be moved/renamed to the path in the URL'
    message: str | None = None
    'message (optional) for the commit of this file. if not supplied, a default message will be used'
    new_branch: str | None = None
    'new_branch (optional) will make a new branch from `branch` before creating the file'
    sha: str
    'sha is the SHA for the file that already exists'
    signoff: bool | None = None
    'Add a Signed-off-by trailer by the committer at the end of the commit log message.'

class UserHeatmapData(ReadOnlyModel):
    contributions: Final[int | None] = None
    timestamp: Final[TimeStamp | None] = None

class VisibleType(OpenEnum):
    UNKNOWN = 'unknown'
    public = 'public'
    limited = 'limited'
    private = 'private'
Angle = NewType('Angle', float)
AttributeId = NewType('AttributeId', str)
BezierId = NewType('BezierId', str)
BitmapId = NewType('BitmapId', str)

class BorderLabelDigits(OpenEnum):
    UNKNOWN = 'unknown'
    uppercase_alphabet = 'UppercaseAlphabet'
    arabic_numeral = 'ArabicNumeral'

class BoundsTag(OpenEnum):
    UNKNOWN = 'unknown'
    angle = 'angle'
    point = 'point'

class CadDocumentType(OpenEnum):
    UNKNOWN = 'unknown'
    project = 'Project'
    pcb = 'Pcb'
    pcb_component_library = 'PcbComponentLibrary'
    schematic = 'Schematic'
    schematic_component_library = 'SchematicComponentLibrary'
Color = NewType('Color', str)

class ComponentFlags(ReadOnlyModel):
    exclude_from_bom: Final[bool | None] = None
ComponentId = NewType('ComponentId', str)

class ComponentLink(ReadOnlyModel):
    path: Final[str]
    display_text: Final[str]

class CornerRadius1(OpenEnum):
    UNKNOWN = 'unknown'
    none = 'None'

class CustomPadDrawingOption1(OpenEnum):
    UNKNOWN = 'unknown'
    filled = 'Filled'
Degree = Literal['degree']
DirectiveLabelId = NewType('DirectiveLabelId', str)
EllipseId = NewType('EllipseId', str)

class ExternalDesignBlock(ReadOnlyModel):
    id: Final[str]
    path: Final[str]
    'Relative to the project root. Uses forward slashes as path separator.'
FontId = NewType('FontId', str)

class HarnessConnectorSide(OpenEnum):
    UNKNOWN = 'unknown'
    right = 'Right'
    left = 'Left'
    up = 'Up'
    down = 'Down'
HarnessEntryId = NewType('HarnessEntryId', str)
HarnessId = NewType('HarnessId', str)

class HorizontalJustification(OpenEnum):
    UNKNOWN = 'unknown'
    left = 'Left'
    center = 'Center'
    right = 'Right'
JunctionId = NewType('JunctionId', str)
LayerId = NewType('LayerId', int)
Length = NewType('Length', float)

class LineStyle(OpenEnum):
    UNKNOWN = 'unknown'
    solid = 'solid'
    dashed = 'dashed'
    dotted = 'dotted'
    dash_dot = 'dash_dot'
    dash_dot_dot = 'dash_dot_dot'
    dense_dot = 'dense_dot'
Meters = NewType('Meters', float)
Millimeter = Literal['mm']
NetId = NewType('NetId', str)
NetLabelId = NewType('NetLabelId', str)
NoConnectSymbolId = NewType('NoConnectSymbolId', str)

class PadHoleCircle(ReadOnlyModel):
    radius: Final[Length]

class PadHoleRectangle(ReadOnlyModel):
    width: Final[Length]
    height: Final[Length]

class PadHoleShape1(ReadOnlyModel):
    model_config = ConfigDict(extra='forbid')
    circle: Final[PadHoleCircle]

class PadHoleShape3(ReadOnlyModel):
    model_config = ConfigDict(extra='forbid')
    rectangle: Final[PadHoleRectangle]

class PadHoleSlot(ReadOnlyModel):
    width: Final[Length]
    height: Final[Length]
PadId = NewType('PadId', str)

class PadShapeCircle(ReadOnlyModel):
    radius: Final[Length]

class PadShapeOctagon(ReadOnlyModel):
    width: Final[Length]
    height: Final[Length]

class PadShapePill(ReadOnlyModel):
    width: Final[Length]
    height: Final[Length]

class PadShapeRectangle(ReadOnlyModel):
    width: Final[Length]
    height: Final[Length]
    x_radius: Final[Length]
    y_radius: Final[Length]
PadstackId = NewType('PadstackId', str)

class PageBorderMargin(ReadOnlyModel):
    left: Final[Length]
    right: Final[Length]
    top: Final[Length]
    bottom: Final[Length]

class ParameterSetStyle(OpenEnum):
    UNKNOWN = 'unknown'
    large = 'Large'
    tiny = 'Tiny'
    differential_pair = 'DifferentialPair'
PcbArcId = NewType('PcbArcId', str)

class PcbComponentLibDocumentType(OpenEnum):
    UNKNOWN = 'unknown'
    pcb_component_lib = 'PcbComponentLib'

class PcbDocumentType(OpenEnum):
    UNKNOWN = 'unknown'
    pcb = 'Pcb'
PcbLibComponentId = NewType('PcbLibComponentId', str)
PcbTextId = NewType('PcbTextId', str)

class PinElectricalType(OpenEnum):
    UNKNOWN = 'unknown'
    input = 'Input'
    io = 'Io'
    hi_z = 'HiZ'
    open_collector = 'OpenCollector'
    open_emitter = 'OpenEmitter'
    output = 'Output'
    passive = 'Passive'
    power = 'Power'
    no_connect = 'NoConnect'
    unspecified = 'Unspecified'
    power_in = 'PowerIn'
    power_out = 'PowerOut'
PinId = NewType('PinId', str)

class PinOrientation(OpenEnum):
    UNKNOWN = 'unknown'
    left = 'Left'
    right = 'Right'
    up = 'Up'
    down = 'Down'

class PinTextRelativeTo(OpenEnum):
    UNKNOWN = 'unknown'
    pin = 'Pin'
    component = 'Component'

class Point(ReadOnlyModel):
    x: Final[Length]
    y: Final[Length]
PolygonId = NewType('PolygonId', str)
PolylineId = NewType('PolylineId', str)
PortId = NewType('PortId', str)

class ProjectDocument(ReadOnlyModel):
    id: Final[str]
    path: Final[str]
    'Relative to the project root. Uses forward slashes as path separator.'
    ty: Final[CadDocumentType | None] = None
    'The type of ECAD Document. Omitted if null.'

class ProjectDocumentType(OpenEnum):
    UNKNOWN = 'unknown'
    project = 'Project'
Pt = NewType('Pt', float)
RectangleId = NewType('RectangleId', str)
RegionDirectiveId = NewType('RegionDirectiveId', str)
RegionId = NewType('RegionId', str)

class RegionType(OpenEnum):
    UNKNOWN = 'unknown'
    fill = 'Fill'
    cutout = 'Cutout'
    keep_out = 'KeepOut'
    cavity = 'Cavity'
    board_cutout = 'BoardCutout'

class RelativePinTextOrientation(OpenEnum):
    UNKNOWN = 'unknown'
    parallel = 'Parallel'
    perpendicular = 'Perpendicular'
Overline = tuple[str, bool]

class RichText(ReadOnlyModel):
    display: Final[str]
    overlines: Final[list[Overline] | None] = None
    'null when no overlines.'
    component_links: Final[list[ComponentLink] | None] = None
SchArcId = NewType('SchArcId', str)
SchComponentId = NewType('SchComponentId', str)
SchLibComponentId = NewType('SchLibComponentId', str)
SchTextId = NewType('SchTextId', str)

class SchematicComponentLibDocumentType(OpenEnum):
    UNKNOWN = 'unknown'
    schematic_component_lib = 'SchematicComponentLib'

class SchematicDocumentType(OpenEnum):
    UNKNOWN = 'unknown'
    schematic = 'Schematic'

class SchematicNet(ReadOnlyModel):
    id: Final[NetId]
    name: Final[str]
SchematicPageGroupId = NewType('SchematicPageGroupId', str)

class SchematicPageGroupParentReference(ReadOnlyModel):
    parent_page_id: Final[str]
SchematicPageId = NewType('SchematicPageId', str)
SheetEntryId = NewType('SheetEntryId', str)

class SheetEntryType(OpenEnum):
    UNKNOWN = 'unknown'
    input = 'Input'
    output = 'Output'
    bi_directional = 'BiDirectional'
    tri_state = 'TriState'
    passive = 'Passive'
SheetRefId = NewType('SheetRefId', str)
SymbolId = NewType('SymbolId', int)

class SymbolRef1(OpenEnum):
    UNKNOWN = 'unknown'
    all_symbols = 'AllSymbols'

class SymbolRef2(ReadOnlyModel):
    model_config = ConfigDict(extra='forbid')
    symbol: Final[SymbolId]
SymbolRef = SymbolRef1 | SymbolRef2

class TextDecorations(ReadOnlyModel):
    is_underline: Final[bool]
    is_strikethrough: Final[bool]

class TextFrame(ReadOnlyModel):
    position: Final[Point]
    width: Final[Length]
    height: Final[Length]
    line_width: Final[Length]
    line_style: Final[LineStyle | None] = None
    show_border: Final[bool]
    margin: Final[Length]
    is_filled: Final[bool]
    fill_color: Final[Color]
    border_color: Final[Color]
    clip_to_bounds: Final[bool]
    wrap_width: Final[Meters | None] = None
TitleBlockId = NewType('TitleBlockId', str)

class Track(ReadOnlyModel):
    points: Final[list[Point]]
    line_width: Final[Length]
    layer_id: Final[LayerId]
    net_id: Final[NetId | None] = None
    net_name: Final[str | None] = None
TrackId = NewType('TrackId', str)

class Variant(ReadOnlyModel):
    id: Final[str]
    description: Final[str]
VariantId = NewType('VariantId', str)

class VerticalJustification(OpenEnum):
    UNKNOWN = 'unknown'
    top = 'Top'
    center = 'Center'
    bottom = 'Bottom'

class Via(ReadOnlyModel):
    center: Final[Point]
    rotation: Final[Angle]
    padstack: Final[PadstackId]
    net_id: Final[NetId | None] = None
    net_name: Final[str | None] = None
ViaId = NewType('ViaId', str)

class Warning(ReadOnlyModel):
    file_path: Final[str]
    'Uses forward slashes as path separator.'
    detail: Final[str]
WireAliasId = NewType('WireAliasId', str)
WireId = NewType('WireId', str)

class ContentsResponse(ReadOnlyModel):
    field_links: Final[FileLinksResponse | None] = None
    content: Final[str | None] = None
    '`content` is populated when `type` is `file`, otherwise null'
    download_url: Final[str | None] = None
    encoding: Final[str | None] = None
    '`encoding` is populated when `type` is `file`, otherwise null'
    git_url: Final[str | None] = None
    html_url: Final[str | None] = None
    last_author_date: Final[AwareDatetime]
    last_commit_sha: Final[str]
    last_committer_date: Final[AwareDatetime]
    name: Final[str]
    path: Final[str]
    sha: Final[str]
    size: Final[int]
    submodule_git_url: Final[str | None] = None
    '`submodule_git_url` is populated when `type` is `submodule`, otherwise null'
    target: Final[str | None] = None
    '`target` is populated when `type` is `symlink`, otherwise null'
    type: Final[str]
    '`type` will be `file`, `dir`, `symlink`, or `submodule`'
    url: Final[str | None] = None

class CreateFileOptions(InputModel):
    author: Identity | None = None
    branch: str | None = None
    'branch (optional) to base this file from. if not given, the default branch is used'
    committer: Identity | None = None
    content: str
    'content must be base64 encoded'
    dates: CommitDateOptions | None = None
    message: str | None = None
    'message (optional) for the commit of this file. if not supplied, a default message will be used'
    new_branch: str | None = None
    'new_branch (optional) will make a new branch from `branch` before creating the file'
    signoff: bool | None = None
    'Add a Signed-off-by trailer by the committer at the end of the commit log message.'

class CreateHookOption(InputModel):
    active: bool | None = False
    authorization_header: str | None = None
    branch_filter: str | None = None
    config: CreateHookOptionConfig
    events: list[str] | None = None
    type: Type

class CreateMilestoneOption(InputModel):
    description: str | None = None
    due_on: AwareDatetime | None = None
    state: StateType | None = None
    title: str | None = None

class CreateOrgOption(InputModel):
    description: str | None = None
    email: str | None = None
    full_name: str | None = None
    location: str | None = None
    repo_admin_change_team_access: bool | None = None
    username: str
    visibility: VisibleType | None = None
    website: str | None = None

class CreateDesignReviewReviewOptions(InputModel):
    body: str | None = None
    comments: list[CreateDesignReviewReviewComment] | None = None
    commit_id: str | None = None
    event: ReviewStateType | None = None

class CreateUserOption(InputModel):
    created_at: AwareDatetime | None = None
    'For explicitly setting the user creation timestamp. Useful when users are\nmigrated from other systems. When omitted, the user\'s creation timestamp\nwill be set to "now".'
    email: str
    full_name: str | None = None
    login_name: str | None = None
    must_change_password: bool | None = None
    password: str | None = None
    restricted: bool | None = None
    send_notify: bool | None = None
    source_id: int | None = None
    username: str
    visibility: VisibleType | None = None

class DeleteFileOptions(InputModel):
    author: Identity | None = None
    branch: str | None = None
    'branch (optional) to base this file from. if not given, the default branch is used'
    committer: Identity | None = None
    dates: CommitDateOptions | None = None
    message: str | None = None
    'message (optional) for the commit of this file. if not supplied, a default message will be used'
    new_branch: str | None = None
    'new_branch (optional) will make a new branch from `branch` before creating the file'
    sha: str
    'sha is the SHA for the file that already exists'
    signoff: bool | None = None
    'Add a Signed-off-by trailer by the committer at the end of the commit log message.'

class EditIssueOption(InputModel):
    assignee: str | None = None
    'deprecated'
    assignees: list[str] | None = None
    body: str | None = None
    due_date: AwareDatetime | None = None
    milestone: int | None = None
    ref: str | None = None
    state: StateType | None = None
    title: str | None = None
    unset_due_date: bool | None = None

class EditOrgOption(InputModel):
    description: str | None = None
    email: str | None = None
    full_name: str | None = None
    location: str | None = None
    repo_admin_change_team_access: bool | None = None
    visibility: VisibleType | None = None
    website: str | None = None

class EditDesignReviewOption(InputModel):
    allow_maintainer_edit: bool | None = None
    assignee: str | None = None
    assignees: list[str] | None = None
    base: str | None = None
    body: str | None = None
    due_date: AwareDatetime | None = None
    labels: list[int] | None = None
    milestone: int | None = None
    state: StateType | None = None
    title: str | None = None
    unset_due_date: bool | None = None

class EditRepoOption(InputModel):
    allow_fast_forward_only_merge: bool | None = None
    'either `true` to allow fast-forward-only merging design reviews, or `false` to prevent fast-forward-only merging.'
    allow_manual_merge: bool | None = None
    'either `true` to allow mark pr as merged manually, or `false` to prevent it.'
    allow_merge_commits: bool | None = None
    'either `true` to allow merging design reviews with a merge commit, or `false` to prevent merging design reviews with merge commits.'
    allow_rebase: bool | None = None
    'either `true` to allow rebase-merging design reviews, or `false` to prevent rebase-merging.'
    allow_rebase_explicit: bool | None = None
    'either `true` to allow rebase with explicit merge commits (--no-ff), or `false` to prevent rebase with explicit merge commits.'
    allow_rebase_update: bool | None = None
    'either `true` to allow updating design review branch by rebase, or `false` to prevent it.'
    allow_squash_merge: bool | None = None
    'either `true` to allow squash-merging design reviews, or `false` to prevent squash-merging.'
    archived: bool | None = None
    'set to `true` to archive this repository.'
    autodetect_manual_merge: bool | None = None
    'either `true` to enable AutodetectManualMerge, or `false` to prevent it. Note: In some special cases, misjudgments can occur.'
    default_allow_maintainer_edit: bool | None = None
    'set to `true` to allow edits from maintainers by default'
    default_branch: str | None = None
    'sets the default branch for this repository.'
    default_delete_branch_after_merge: bool | None = None
    'set to `true` to delete pr branch after merge by default'
    default_merge_style: str | None = None
    'set to a merge style to be used by this repository: "merge", "rebase", "rebase-merge", "squash", or "fast-forward-only".'
    description: str | None = None
    'a short description of the repository.'
    enable_prune: bool | None = None
    'enable prune - remove obsolete remote-tracking references when mirroring'
    external_tracker: ExternalTracker | None = None
    external_wiki: ExternalWiki | None = None
    has_actions: bool | None = None
    'either `true` to enable actions unit, or `false` to disable them.'
    has_issues: bool | None = None
    'either `true` to enable issues for this repository or `false` to disable them.'
    has_packages: bool | None = None
    'either `true` to enable packages unit, or `false` to disable them.'
    has_projects: bool | None = None
    'either `true` to enable project unit, or `false` to disable them.'
    has_pull_requests: bool | None = None
    'either `true` to allow design reviews, or `false` to prevent design review.'
    has_releases: bool | None = None
    'either `true` to enable releases unit, or `false` to disable them.'
    has_wiki: bool | None = None
    'either `true` to enable the wiki for this repository or `false` to disable it.'
    ignore_whitespace_conflicts: bool | None = None
    'either `true` to ignore whitespace for conflicts, or `false` to not ignore whitespace.'
    internal_tracker: InternalTracker | None = None
    mirror_interval: str | None = None
    'set to a string like `8h30m0s` to set the mirror interval time'
    name: str | None = None
    'name of the repository'
    private: bool | None = None
    'either `true` to make the repository private or `false` to make it public.\nNote: you will get a 422 error if the organization restricts changing repository visibility to organization\nowners and a non-owner tries to change the value of private.'
    projects_mode: str | None = None
    '`repo` to only allow repo-level projects, `owner` to only allow owner projects, `all` to allow both.'
    template: bool | None = None
    'either `true` to make this repository a template or `false` to make it a normal repository'
    website: str | None = None
    'a URL with more information about the repository.'

class EditUserOption(InputModel):
    active: bool | None = None
    admin: bool | None = None
    allow_create_organization: bool | None = None
    allow_git_hook: bool | None = None
    allow_import_local: bool | None = None
    description: str | None = None
    email: str | None = None
    full_name: str | None = None
    location: str | None = None
    login_name: str
    max_repo_creation: int | None = None
    must_change_password: bool | None = None
    password: str | None = None
    prohibit_login: bool | None = None
    restricted: bool | None = None
    source_id: int | None = None
    visibility: VisibleType | None = None
    website: str | None = None

class Milestone(MilestoneEntity):
    closed_at: Final[AwareDatetime | None] = None
    closed_issues: Final[int]
    created_at: Final[AwareDatetime]
    description: Final[str]
    due_on: Final[AwareDatetime | None] = None
    id: Final[int]
    open_issues: Final[int]
    state: Final[StateType]
    title: Final[str]
    updated_at: Final[AwareDatetime | None] = None

class Organization(OrganizationEntity):
    avatar_url: Final[str]
    description: str
    email: str
    full_name: str
    id: Final[int]
    location: str
    name: Final[str]
    repo_admin_change_team_access: bool
    username: Final[str]
    'deprecated'
    visibility: VisibleType
    website: str

class PayloadCommitVerification(ReadOnlyModel):
    payload: Final[str | None] = None
    reason: Final[str | None] = None
    signature: Final[str | None] = None
    signer: Final[PayloadUser | None] = None
    verified: Final[bool | None] = None

class ProjectData(ReadOnlyModel):
    documents: Final[dict[str, str] | None] = None
    'Mapping of component reference to the document path that defines it.'
    external_design_blocks: Final[dict[str, str] | None] = None
    'Mapping of external design block reference to the HTML URL of its sheet, used to resolve device sheets in submodules.'
    project_path: Final[str | None] = None
    'Path of the project file, relative to the repo root.'
    variants: Final[dict[str, str] | None] = None
    'Mapping of variant id to its human-readable name.'
    warnings: Final[ProjectWarnings | None] = None

class RepoCommit(ReadOnlyModel):
    author: Final[CommitUser | None] = None
    committer: Final[CommitUser | None] = None
    message: Final[str | None] = None
    tree: Final[CommitMeta | None] = None
    url: Final[str | None] = None
    verification: Final[PayloadCommitVerification | None] = None

class Team(TeamEntity):
    can_create_org_repo: bool
    description: str
    id: Final[int]
    includes_all_repositories: bool
    name: str
    organization: Final[Organization | None] = None
    permission: AccessMode
    units: list[str] | None = None
    units_map: dict[str, str]

class User(UserEntity):
    active: bool | None = None
    'Is user active'
    avatar_url: Final[str]
    "URL to the user's avatar"
    created: Final[AwareDatetime]
    description: str
    "the user's description"
    email: str
    followers_count: Final[int]
    'user counts'
    following_count: Final[int]
    full_name: str
    "the user's full name"
    html_url: Final[str]
    "URL to the user's gitea page"
    id: Final[int]
    "the user's id"
    is_admin: Final[bool | None] = None
    'Is the user an administrator'
    language: Final[str | None] = None
    'User locale'
    last_login: Final[AwareDatetime | None] = None
    location: str
    "the user's location"
    login: Final[str]
    "the user's username"
    login_name: str | None = 'empty'
    "the user's authentication sign-in name."
    prohibit_login: bool | None = None
    'Is user login prohibited'
    restricted: bool
    'Is user restricted'
    source_id: int | None = None
    "The ID of the user's Authentication Source"
    starred_repos_count: Final[int]
    visibility: VisibleType
    website: str
    "the user's website"

class Bezier(ReadOnlyModel):
    id: Final[BezierId]
    symbol: Final[SymbolRef]
    is_visible: Final[bool]
    color: Final[Color]
    line_width: Final[Length]
    line_style: Final[LineStyle | None] = None
    points: Final[list[Point]]
    is_filled: Final[bool]
    fill_color: Final[Color]

class Bitmap(ReadOnlyModel):
    id: Final[BitmapId]
    symbol: Final[SymbolRef]
    bottom_left: Final[Point]
    width: Final[Length]
    height: Final[Length]
    is_visible: Final[bool | None] = None

class Border(ReadOnlyModel):
    line_width: Final[Length]
    padding: Final[Length]

class BorderLabelFormat(ReadOnlyModel):
    width: Final[Length]
    count: Final[int]
    numbering: Final[BorderLabelDigits]
    ascending: Final[bool]

class Circular(ReadOnlyModel):
    radius: Final[Meters]

class CornerRadius2(ReadOnlyModel):
    model_config = ConfigDict(extra='forbid')
    circular: Final[Circular]

class Xy(ReadOnlyModel):
    radius_x: Final[Meters]
    radius_y: Final[Meters]

class CornerRadius3(ReadOnlyModel):
    model_config = ConfigDict(extra='forbid')
    xy: Final[Xy]
CornerRadius = CornerRadius1 | CornerRadius2 | CornerRadius3

class Outline(ReadOnlyModel):
    stroke_width: Final[Meters]

class CustomPadDrawingOption2(ReadOnlyModel):
    model_config = ConfigDict(extra='forbid')
    outline: Final[Outline]
CustomPadDrawingOption = CustomPadDrawingOption1 | CustomPadDrawingOption2

class Ellipse(ReadOnlyModel):
    id: Final[EllipseId]
    symbol: Final[SymbolRef]
    is_visible: Final[bool]
    color: Final[Color]
    line_width: Final[Length]
    line_style: Final[LineStyle | None] = None
    is_filled: Final[bool]
    fill_color: Final[Color]
    center: Final[Point]
    radius: Final[Point]
    is_transparent: Final[bool]

class Font(ReadOnlyModel):
    family: Final[str]
    pt: Final[Pt]
    weight: Final[float]
    letter_spacing: Final[Pt | None] = None
    stroke_width: Final[Meters | None] = None
    is_italic: Final[bool]
    is_bold: Final[bool]
    decorations: Final[TextDecorations]
    is_truetype: Final[bool]

class HarnessEntry(ReadOnlyModel):
    id: Final[HarnessEntryId]
    name: Final[str]
    display_name: Final[RichText | None] = None
    distance_from_top: Final[Length]
    text_color: Final[Color]
    font_id: Final[FontId]

class HarnessLabel(ReadOnlyModel):
    text: Final[str]
    position: Final[Point]
    orientation: Final[Angle]
    color: Final[Color]
    font_id: Final[FontId]
    is_visible: Final[bool]

class Junction(ReadOnlyModel):
    id: Final[JunctionId]
    position: Final[Point]
    color: Final[Color]
    diameter: Final[Length]

class Layer(ReadOnlyModel):
    id: Final[LayerId]
    name: Final[str]
    is_visible: Final[bool | None] = False

class Net(ReadOnlyModel):
    id: Final[NetId]
    name: Final[str | None] = None

class NoConnectSymbol(ReadOnlyModel):
    position: Final[Point]
    net_id: Final[NetId | None] = None

class Pad(ReadOnlyModel):
    designator: Final[str]
    center: Final[Point]
    rotation: Final[Angle]
    padstack: Final[PadstackId]
    net_id: Final[NetId | None] = None
    net_name: Final[str | None] = None

class PadHoleShape2(ReadOnlyModel):
    model_config = ConfigDict(extra='forbid')
    slot: Final[PadHoleSlot]
PadHoleShape = PadHoleShape1 | PadHoleShape2 | PadHoleShape3

class PadShape1(ReadOnlyModel):
    model_config = ConfigDict(extra='forbid')
    circle: Final[PadShapeCircle]

class PadShape2(ReadOnlyModel):
    model_config = ConfigDict(extra='forbid')
    pill: Final[PadShapePill]

class PadShape3(ReadOnlyModel):
    model_config = ConfigDict(extra='forbid')
    rectangle: Final[PadShapeRectangle]

class PadShape4(ReadOnlyModel):
    model_config = ConfigDict(extra='forbid')
    octagon: Final[PadShapeOctagon]

class PageBorder(ReadOnlyModel):
    stroke_width: Final[Length]
    margin: Final[PageBorderMargin]
    horizontal_label: Final[BorderLabelFormat]
    vertical_label: Final[BorderLabelFormat]

class Path(ReadOnlyModel):
    start: Final[Point]

class PcbArc(ReadOnlyModel):
    center: Final[Point]
    radius_pair: Final[Point]
    bounds_tag: Final[BoundsTag]
    start_angle: Final[Angle]
    end_angle: Final[Angle]
    start_point: Final[Point]
    end_point: Final[Point]
    line_width: Final[Length]
    layer_id: Final[LayerId]
    net_id: Final[NetId | None] = None
    net_name: Final[str | None] = None

class Polygon(ReadOnlyModel):
    id: Final[PolygonId]
    symbol: Final[SymbolRef]
    is_visible: Final[bool]
    color: Final[Color]
    points: Final[list[Point]]
    line_width: Final[Length]
    is_filled: Final[bool]
    fill_color: Final[Color]

class Polyline(ReadOnlyModel):
    id: Final[PolylineId]
    symbol: Final[SymbolRef]
    is_visible: Final[bool]
    color: Final[Color]
    points: Final[list[Point]]
    line_width: Final[Length]
    is_filled: Final[bool]
    fill_color: Final[Color]
    line_style: Final[LineStyle | None] = None

class Project(ReadOnlyModel):
    documents: Final[list[ProjectDocument]]
    variants: Final[list[Variant]]
    external_design_blocks: Final[list[ExternalDesignBlock]]
    altium_project_pcb_variants_file: Final[str | None] = None
    'The path of the altium `.prjpcbvariants` file relative to the repo root. Omitted if null.'

class ProjectEntryExport(ReadOnlyModel):
    type: Final[ProjectDocumentType]
    path: Final[str]
    'Path relative to the repo root. Uses forward slashes as path separator.'
    project: Final[Project]
    warnings: Final[list[Warning]]
    'Warnings that occurred during the generation of this project'

class Rectangle(ReadOnlyModel):
    id: Final[RectangleId]
    symbol: Final[SymbolRef]
    is_visible: Final[bool]
    color: Final[Color]
    line_width: Final[Length]
    line_style: Final[LineStyle | None] = None
    is_filled: Final[bool]
    fill_color: Final[Color]
    bottom_left: Final[Point]
    width: Final[Length]
    height: Final[Length]
    is_transparent: Final[bool]
    corner_radius: Final[CornerRadius | None] = None

class Region(ReadOnlyModel):
    kind: Final[RegionType]
    start: Final[Point]
    cutouts: Final[list[Path] | None] = None
    layer_id: Final[LayerId]
    net_id: Final[NetId | None] = None
    net_name: Final[str | None] = None

class RegionDirective(ReadOnlyModel):
    id: Final[RegionDirectiveId]
    position: Final[Point]
    outline: Final[Color]
    fill: Final[Color]
    collapsed: Final[bool]
    perimeter: Final[list[Point]]
    line_style: Final[LineStyle]
    line_width: Final[Meters]
    triangle_line_width: Final[Meters]

class SchArc(ReadOnlyModel):
    id: Final[SchArcId]
    symbol: Final[SymbolRef]
    is_visible: Final[bool]
    color: Final[Color]
    line_width: Final[Length]
    is_filled: Final[bool]
    fill_color: Final[Color]
    line_style: Final[LineStyle | None] = None
    center: Final[Point]
    radius_pair: Final[Point]
    bounds_tag: Final[BoundsTag]
    start_angle: Final[Angle]
    end_angle: Final[Angle]
    start_point: Final[Point]
    end_point: Final[Point]

class SchLibSymbol(ReadOnlyModel):
    id: Final[SymbolId]

class SchematicPageGroupParent(ReadOnlyModel):
    id: Final[str]
    reference_in_parent: Final[SchematicPageGroupParentReference | None] = None

class TextJustification(ReadOnlyModel):
    horizontal: Final[HorizontalJustification]
    vertical: Final[VerticalJustification]

class WireAlias(ReadOnlyModel):
    position: Final[Point]
    color: Final[Color]
    rotation: Final[Angle]
    name: Final[str]
    justification: Final[TextJustification]
    font_id: Final[FontId]
    is_visible: Final[bool]

class Comment(CommentEntity):
    assets: Final[list[Attachment]]
    body: str
    created_at: Final[AwareDatetime]
    html_url: Final[str]
    id: Final[int]
    issue_url: Final[str]
    original_author: Final[str]
    original_author_id: Final[int]
    pull_request_url: Final[str]
    updated_at: Final[AwareDatetime]
    user: Final[User | None] = None

class Commit(CommitEntity):
    author: Final[User | None] = None
    commit: Final[RepoCommit | None] = None
    committer: Final[User | None] = None
    created: Final[AwareDatetime]
    files: Final[list[CommitAffectedFiles] | None] = None
    html_url: Final[str]
    parents: Final[list[CommitMeta]]
    sha: Final[str]
    stats: Final[CommitStats | None] = None
    url: Final[str]

class CommitStatus(ReadOnlyModel):
    context: Final[str]
    created_at: Final[AwareDatetime]
    creator: Final[User | None] = None
    description: Final[str]
    id: Final[int]
    status: Final[CommitStatusState]
    target_url: Final[str]
    updated_at: Final[AwareDatetime]
    url: Final[str]
ContentsResponseOrList = ContentsResponse | list[ContentsResponse]

class FileDeleteResponse(ReadOnlyModel):
    commit: Final[FileCommitResponse | None] = None
    verification: Final[PayloadCommitVerification | None] = None

class FileResponse(ReadOnlyModel):
    commit: Final[FileCommitResponse | None] = None
    content: Final[ContentsResponse | None] = None
    verification: Final[PayloadCommitVerification | None] = None

class Issue(IssueEntity):
    assets: Final[list[Attachment]]
    assignee: User | None = None
    assignees: list[User] | None = None
    body: str
    closed_at: Final[AwareDatetime | None] = None
    comments: Final[int]
    created_at: Final[AwareDatetime]
    due_date: AwareDatetime | None = None
    html_url: Final[str]
    id: Final[int]
    is_locked: Final[bool]
    labels: Final[list[Label]]
    milestone: Milestone | None = None
    number: Final[int]
    original_author: Final[str]
    original_author_id: Final[int]
    pin_order: Final[int]
    pull_request: Final[DesignReviewMeta | None] = None
    ref: str
    repository: Final[RepositoryMeta | None] = None
    state: StateType
    title: str
    updated_at: Final[AwareDatetime]
    url: Final[str]
    user: Final[User | None] = None

class PayloadCommit(ReadOnlyModel):
    added: Final[list[str] | None] = None
    author: Final[PayloadUser | None] = None
    committer: Final[PayloadUser | None] = None
    id: Final[str | None] = None
    'sha1 hash of the commit'
    message: Final[str | None] = None
    modified: Final[list[str] | None] = None
    removed: Final[list[str] | None] = None
    timestamp: Final[AwareDatetime | None] = None
    url: Final[str | None] = None
    verification: Final[PayloadCommitVerification | None] = None

class DesignReviewReview(DesignReviewReviewEntity):
    body: Final[str]
    comments_count: Final[int]
    commit_id: Final[str]
    dismissed: Final[bool]
    html_url: Final[str]
    id: Final[int]
    official: Final[bool]
    pull_request_url: Final[str]
    stale: Final[bool]
    state: Final[ReviewStateType]
    submitted_at: Final[AwareDatetime]
    team: Final[Team | None] = None
    updated_at: Final[AwareDatetime]
    user: Final[User | None] = None

class DesignReviewReviewComment(ReadOnlyModel):
    body: Final[str]
    commit_id: Final[str]
    created_at: Final[AwareDatetime]
    diff_hunk: Final[str]
    html_url: Final[str]
    id: Final[int]
    original_commit_id: Final[str]
    original_position: Final[int]
    path: Final[str]
    position: Final[int]
    pull_request_review_id: Final[int]
    pull_request_url: Final[str]
    resolver: Final[User | None] = None
    sub_path: Final[str]
    updated_at: Final[AwareDatetime]
    user: Final[User | None] = None

class Release(ReleaseEntity):
    assets: Final[list[Attachment]]
    author: Final[User | None] = None
    body: str
    created_at: Final[AwareDatetime]
    draft: bool
    html_url: Final[str]
    id: Final[int]
    name: str
    prerelease: bool
    published_at: Final[AwareDatetime]
    tag_name: str
    tarball_url: Final[str]
    target_commitish: str
    upload_url: Final[str]
    url: Final[str]
    zipball_url: Final[str]

class RepoTransfer(ReadOnlyModel):
    doer: Final[User | None] = None
    recipient: Final[User | None] = None
    teams: Final[list[Team] | None] = None

class Repository(RepositoryEntity):
    allow_fast_forward_only_merge: bool
    allow_merge_commits: bool
    allow_rebase: bool
    allow_rebase_explicit: bool
    allow_rebase_update: bool
    allow_squash_merge: bool
    archived: bool
    archived_at: Final[AwareDatetime]
    avatar_url: Final[str]
    clone_url: Final[str]
    created_at: Final[AwareDatetime]
    default_allow_maintainer_edit: bool
    default_branch: str
    default_delete_branch_after_merge: bool
    default_merge_style: str
    description: str
    empty: Final[bool]
    external_tracker: ExternalTracker | None = None
    external_wiki: ExternalWiki | None = None
    fork: Final[bool]
    forks_count: Final[int]
    full_name: Final[str]
    has_actions: bool
    has_issues: bool
    has_packages: bool
    has_projects: bool
    has_pull_requests: bool
    has_releases: bool
    has_wiki: bool
    html_url: Final[str]
    id: Final[int]
    ignore_whitespace_conflicts: bool
    internal: Final[bool]
    internal_tracker: InternalTracker | None = None
    language: Final[str]
    languages_url: Final[str]
    licenses: Final[list[str]]
    link: Final[str]
    mirror: Final[bool]
    mirror_interval: str
    mirror_updated: Final[AwareDatetime]
    name: str
    object_format_name: Final[ObjectFormatName]
    'ObjectFormatName of the underlying git repository'
    open_issues_count: Final[int]
    open_pr_counter: Final[int]
    original_url: Final[str]
    owner: Final[User]
    parent: Final[Repository | None] = None
    permissions: Final[Permission | None] = None
    private: bool
    projects_mode: str
    release_counter: Final[int]
    repo_transfer: Final[RepoTransfer | None] = None
    size: Final[int]
    ssh_url: Final[str]
    stars_count: Final[int]
    template: bool
    topics: Final[list[str]]
    updated_at: Final[AwareDatetime]
    url: Final[str]
    watchers_count: Final[int]
    website: str

class SearchResults(ReadOnlyModel):
    data: Final[list[Repository] | None] = None
    ok: Final[bool | None] = None

class TrackedTime(ReadOnlyModel):
    created: Final[AwareDatetime | None] = None
    id: Final[int | None] = None
    issue: Final[Issue | None] = None
    issue_id: Final[int | None] = None
    'deprecated (only for backwards compatibility)'
    time: Final[int | None] = None
    'Time in seconds'
    user_id: Final[int | None] = None
    'deprecated (only for backwards compatibility)'
    user_name: Final[str | None] = None

class Attribute(ReadOnlyModel):
    name: Final[str]
    value: Final[str | None] = None
    display_text: Final[str | None] = None
    symbol: Final[SymbolRef]
    position: Final[Point]
    is_visible: Final[bool]
    show_name: Final[bool | None] = None
    orientation: Final[Angle]
    justification: Final[TextJustification]
    color: Final[Color]
    font_id: Final[FontId]

class CustomPadShape(ReadOnlyModel):
    geometry: Final[Path]
    drawing_options: Final[CustomPadDrawingOption]

class DirectiveLabel(ReadOnlyModel):
    id: Final[DirectiveLabelId]
    position: Final[Point]
    color: Final[Color]
    orientation: Final[PinOrientation]
    name: Final[str | None] = None
    style: Final[ParameterSetStyle]
    attributes: Final[dict[AttributeId, Attribute] | None] = None

class Harness(ReadOnlyModel):
    id: Final[HarnessId]
    position: Final[Point]
    width: Final[Length]
    height: Final[Length]
    connector_side: Final[HarnessConnectorSide]
    connection_position: Final[Length]
    color: Final[Color]
    area_color: Final[Color]
    line_width: Final[Length]
    name: Final[HarnessLabel | None] = None
    harness_entries: Final[dict[HarnessEntryId, HarnessEntry] | None] = None

class NetLabel(ReadOnlyModel):
    net_id: Final[NetId | None] = None
    position: Final[Point]
    color: Final[Color]
    font_id: Final[FontId]
    justification: Final[TextJustification]
    orientation: Final[Angle]
    name: Final[str]
    display_text: Final[RichText | None] = None
    is_visible: Final[bool]

class PadHole(ReadOnlyModel):
    offset: Final[Point]
    rotation: Final[Angle]
    hole: Final[PadHoleShape]

class PadShape5(ReadOnlyModel):
    model_config = ConfigDict(extra='forbid')
    custom: Final[list[CustomPadShape]]
PadShape = PadShape1 | PadShape2 | PadShape3 | PadShape4 | PadShape5

class PadstackLayer(ReadOnlyModel):
    shape: Final[PadShape]
    offset: Final[Point]

class PcbText(ReadOnlyModel):
    text: Final[str]
    position: Final[Point]
    rotation: Final[Angle | None] = None
    'Absent when zero.'
    width: Final[Length | None] = None
    height: Final[Length]
    border: Final[Border | None] = None
    font_id: Final[FontId]
    justification: Final[TextJustification]
    is_mirrored: Final[bool]
    is_designator: Final[bool]
    is_comment: Final[bool]
    is_hidden: Final[bool]
    layer_id: Final[LayerId]
    net_id: Final[NetId | None] = None
    net_name: Final[str | None] = None

class PinTextPositionInfo(ReadOnlyModel):
    margin: Final[Length]
    orientation: Final[RelativePinTextOrientation]
    relative_to: Final[PinTextRelativeTo]
    justification: Final[TextJustification | None] = None

class SchText(ReadOnlyModel):
    id: Final[SchTextId]
    symbol: Final[SymbolRef]
    is_visible: Final[bool]
    color: Final[Color]
    font_id: Final[FontId]
    position: Final[Point]
    justification: Final[TextJustification]
    orientation: Final[Angle]
    text: Final[str]
    display_text: Final[RichText | None] = None
    variant_text: Final[dict[str, Any] | None] = None
    frame: Final[TextFrame | None] = None

class SchematicPageGroup(ReadOnlyModel):
    id: Final[SchematicPageGroupId]
    display_name: Final[str]
    parent: Final[SchematicPageGroupParent | None] = None

class TitleBlock(ReadOnlyModel):
    id: Final[TitleBlockId]
    name: Final[str]
    position: Final[Point]
    polylines: Final[dict[PolylineId, Polyline]]
    polygons: Final[dict[PolygonId, Polygon]]
    rectangles: Final[dict[RectangleId, Rectangle]]
    arcs: Final[dict[SchArcId, SchArc]]
    ellipses: Final[dict[EllipseId, Ellipse]]
    beziers: Final[dict[BezierId, Bezier]]
    bitmaps: Final[dict[BitmapId, Bitmap]]
    texts: Final[dict[SchTextId, SchText]]
    attributes: Final[dict[AttributeId, Attribute]]

class Wire(ReadOnlyModel):
    id: Final[WireId]
    net_id: Final[NetId | None] = None
    p1: Final[Point]
    p2: Final[Point]
    color: Final[Color]
    width: Final[Length]
    line_style: Final[LineStyle | None] = None
    aliases: Final[dict[WireAliasId, WireAlias] | None] = None

class Branch(BranchEntity):
    commit: Final[PayloadCommit | None] = None
    effective_branch_protection_name: Final[str]
    enable_status_check: Final[bool]
    name: Final[str]
    protected: Final[bool]
    required_approvals: Final[int]
    status_check_contexts: Final[list[str] | None] = None
    user_can_merge: Final[bool]
    user_can_push: Final[bool]

class CombinedStatus(ReadOnlyModel):
    commit_url: Final[str]
    repository: Final[Repository | None] = None
    sha: Final[str]
    state: Final[CommitStatusState]
    statuses: Final[list[CommitStatus]]
    total_count: Final[int]
    url: Final[str]

class PRBranchInfo(ReadOnlyModel):
    label: Final[str | None] = None
    ref: Final[str | None] = None
    repo: Final[Repository | None] = None
    repo_id: Final[int | None] = None
    sha: Final[str | None] = None

class DesignReview(DesignReviewEntity):
    additions: Final[int | None] = None
    allow_maintainer_edit: bool
    assignee: User | None = None
    assignees: list[User]
    base: PRBranchInfo | None = None
    body: str
    changed_files: Final[int | None] = None
    closed_at: Final[AwareDatetime | None] = None
    comments: Final[int]
    created_at: Final[AwareDatetime | None] = None
    deletions: Final[int | None] = None
    diff_url: Final[str]
    draft: Final[bool]
    due_date: AwareDatetime | None = None
    head: Final[PRBranchInfo | None] = None
    html_url: Final[str]
    id: Final[int]
    is_locked: Final[bool]
    labels: list[Label]
    merge_base: Final[str]
    merge_commit_sha: Final[str | None] = None
    mergeable: Final[bool]
    merged: Final[bool]
    merged_at: Final[AwareDatetime | None] = None
    merged_by: Final[User | None] = None
    milestone: Milestone | None = None
    number: Final[int]
    patch_url: Final[str]
    pin_order: Final[int]
    requested_reviewers: Final[list[User]]
    requested_reviewers_teams: Final[list[Team]]
    review_comments: Final[int | None] = None
    'number of review comments made on the diff of a PR review (not including comments on commits or issues in a PR)'
    state: StateType
    title: str
    updated_at: Final[AwareDatetime | None] = None
    url: Final[str]
    user: Final[User | None] = None

class ComponentInstance(ReadOnlyModel):
    id: Final[ComponentId]
    part_id: Final[str | None] = None
    designator: Final[str | None] = None
    schematic_link: Final[str | None] = None
    description: Final[str | None] = None
    position: Final[Point | None] = None
    footprint_lib: Final[str | None] = None
    locked: Final[bool | None] = None
    arcs: Final[dict[PcbArcId, PcbArc]]
    tracks: Final[dict[TrackId, Track]]
    pads: Final[dict[PadId, Pad]]
    vias: Final[dict[ViaId, Via]]
    regions: Final[dict[RegionId, Region]]
    texts: Final[dict[PcbTextId, PcbText]]

class Graphics(ReadOnlyModel):
    polylines: Final[dict[PolylineId, Polyline]]
    polygons: Final[dict[PolygonId, Polygon]]
    rectangles: Final[dict[RectangleId, Rectangle]]
    arcs: Final[dict[SchArcId, SchArc]]
    ellipses: Final[dict[EllipseId, Ellipse]]
    beziers: Final[dict[BezierId, Bezier]]
    bitmaps: Final[dict[BitmapId, Bitmap]]
    texts: Final[dict[SchTextId, SchText]]

class Padstack(ReadOnlyModel):
    name: Final[str | None] = None
    layers: Final[dict[int, PadstackLayer]]
    hole: Final[PadHole | None] = None

class PcbExport(ReadOnlyModel):
    type: Final[PcbDocumentType]
    layers: Final[dict[int, Layer]]
    preset_layers: Final[dict[str, list[LayerId]]]
    component_instances: Final[dict[ComponentId, ComponentInstance]]
    arcs: Final[dict[PcbArcId, PcbArc]]
    tracks: Final[dict[TrackId, Track]]
    pads: Final[dict[PadId, Pad]]
    vias: Final[dict[ViaId, Via]]
    regions: Final[dict[RegionId, Region]]
    texts: Final[dict[PcbTextId, PcbText]]
    padstacks: Final[dict[PadstackId, Padstack]]
    board_size: Final[Point]
    board_offset: Final[Point]
    nets: Final[dict[NetId, Net]]
    length_unit: Final[Millimeter]
    angle_unit: Final[Degree]

class PcbLibraryComponentSchema(ReadOnlyModel):
    id: Final[PcbLibComponentId]
    name: Final[str]
    description: Final[str | None] = None
    arcs: Final[dict[PcbArcId, PcbArc]]
    pads: Final[dict[PadId, Pad]]
    vias: Final[dict[ViaId, Via]]
    tracks: Final[dict[TrackId, Track]]
    texts: Final[dict[PcbTextId, PcbText]]
    regions: Final[dict[RegionId, Region]]
    fonts: Final[dict[FontId, Font]]
    padstacks: Final[dict[PadstackId, Padstack]]

class Pin(ReadOnlyModel):
    is_visible: Final[bool | None] = None
    symbol: Final[SymbolRef]
    name: Final[str]
    display_name: Final[RichText | None] = None
    name_color: Final[Color]
    name_font: Final[FontId | None] = None
    name_position: Final[PinTextPositionInfo]
    is_name_visible: Final[bool]
    description: Final[str]
    designator: Final[str]
    designator_font: Final[FontId | None] = None
    designator_position: Final[PinTextPositionInfo]
    designator_color: Final[Color]
    is_designator_visible: Final[bool]
    electrical_type: Final[PinElectricalType]
    net_id: Final[NetId | None] = None
    position: Final[Point]
    length: Final[Length]
    color: Final[Color | None] = None
    orientation: Final[PinOrientation]

class Port(ReadOnlyModel):
    id: Final[PortId]
    position: Final[Point]
    rotation: Final[Angle]
    mirrored: Final[bool]
    name: Final[str]
    net_id: Final[NetId | None] = None
    description: Final[str | None] = None
    reference: Final[str | None] = None
    attributes: Final[dict[AttributeId, Attribute]]
    pins: Final[dict[PinId, Pin]]
    polylines: Final[dict[PolylineId, Polyline]]
    polygons: Final[dict[PolygonId, Polygon]]
    rectangles: Final[dict[RectangleId, Rectangle]]
    arcs: Final[dict[SchArcId, SchArc]]
    ellipses: Final[dict[EllipseId, Ellipse]]
    beziers: Final[dict[BezierId, Bezier]]
    bitmaps: Final[dict[BitmapId, Bitmap]]
    texts: Final[dict[SchTextId, SchText]]

class SchComponent(ReadOnlyModel):
    id: Final[SchComponentId]
    position: Final[Point]
    rotation: Final[Angle]
    mirrored: Final[bool]
    name: Final[str]
    description: Final[str | None] = None
    reference: Final[str | None] = None
    logical_reference: Final[str | None] = None
    flags: Final[ComponentFlags | None] = None
    attributes: Final[dict[AttributeId, Attribute]]
    pins: Final[dict[PinId, Pin]]
    polylines: Final[dict[PolylineId, Polyline]]
    polygons: Final[dict[PolygonId, Polygon]]
    rectangles: Final[dict[RectangleId, Rectangle]]
    arcs: Final[dict[SchArcId, SchArc]]
    ellipses: Final[dict[EllipseId, Ellipse]]
    beziers: Final[dict[BezierId, Bezier]]
    bitmaps: Final[dict[BitmapId, Bitmap]]
    texts: Final[dict[SchTextId, SchText]]
    variants: Final[dict[VariantId, SchComponent | None] | None] = None

class SchematicLibraryComponentSchema(ReadOnlyModel):
    id: Final[SchLibComponentId]
    name: Final[str]
    comment: Final[str | None] = None
    designator: Final[str | None] = None
    description: Final[str | None] = None
    part_id: Final[str | None] = None
    symbols_map: Final[dict[int, SchLibSymbol]]
    position: Final[Point]
    rotation: Final[Angle]
    attributes: Final[dict[AttributeId, Attribute]]
    pins: Final[dict[PinId, Pin]]
    polylines: Final[dict[PolylineId, Polyline]]
    polygons: Final[dict[PolygonId, Polygon]]
    rectangles: Final[dict[RectangleId, Rectangle]]
    arcs: Final[dict[SchArcId, SchArc]]
    ellipses: Final[dict[EllipseId, Ellipse]]
    beziers: Final[dict[BezierId, Bezier]]
    bitmaps: Final[dict[BitmapId, Bitmap]]
    texts: Final[dict[SchTextId, SchText]]
    fonts: Final[dict[FontId, Font]]

class SheetEntry(ReadOnlyModel):
    id: Final[SheetEntryId]
    name: Final[str]
    display_name: Final[RichText | None] = None
    entry_type: Final[SheetEntryType]
    net_id: Final[NetId | None] = None
    position: Final[Point]
    graphics: Final[Graphics]

class SheetRef(ReadOnlyModel):
    id: Final[SheetRefId]
    sheet_name: Final[str]
    filename: Final[str]
    sheet_entries: Final[dict[SheetEntryId, SheetEntry]]
    position: Final[Point]
    graphics: Final[Graphics]
    external_sheet: Final[bool]

class PcbComponentLibExport(ReadOnlyModel):
    type: Final[PcbComponentLibDocumentType]
    components: Final[list[PcbLibraryComponentSchema]]

class SchematicComponentLibExport(ReadOnlyModel):
    type: Final[SchematicComponentLibDocumentType]
    components: Final[list[SchematicLibraryComponentSchema]]

class SchematicPage(ReadOnlyModel):
    id: Final[SchematicPageId]
    name: Final[str]
    ui_group_id: Final[SchematicPageGroupId]
    ui_group_name: Final[str]
    page_size: Final[Point]
    border: Final[PageBorder | None] = None
    title_blocks: Final[dict[TitleBlockId, TitleBlock]]
    background_color: Final[Color]
    fonts: Final[dict[FontId, Font]]
    wires: Final[dict[WireId, Wire]]
    junctions: Final[dict[JunctionId, Junction]]
    components: Final[dict[SchComponentId, SchComponent]]
    ports: Final[dict[PortId, Port]]
    sheet_refs: Final[dict[SheetRefId, SheetRef]]
    harnesses: Final[dict[HarnessId, Harness] | None] = None
    no_connects: Final[dict[NoConnectSymbolId, NoConnectSymbol] | None] = None
    graphics: Final[Graphics]
    directive_labels: Final[dict[DirectiveLabelId, DirectiveLabel] | None] = None
    region_directives: Final[dict[RegionDirectiveId, RegionDirective] | None] = None
    net_labels: Final[dict[NetLabelId, NetLabel] | None] = None

class SchematicExport(ReadOnlyModel):
    type: Final[SchematicDocumentType]
    variants: Final[dict[VariantId, str] | None] = None
    'Maps variant ID to variant name. Absent when the schematic has no variants.'
    nets: Final[dict[NetId, SchematicNet]]
    pages: Final[list[SchematicPage]]
    page_groups: Final[dict[SchematicPageGroupId, SchematicPageGroup] | None] = None
    'Maps group ID (`pages[].ui_group_id`) to page group, representing a hierarchical structure of groups, each with multiple pages. Absent when hierarchy has not been provided.'
DocumentOutput = PcbComponentLibExport | PcbExport | ProjectEntryExport | SchematicComponentLibExport | SchematicExport
Repository.model_rebuild()
SchComponent.model_rebuild()
Ref = Branch | Commit | str
Content = ContentsResponse

def normalize_ref(ref: Ref) -> str:
    ...
