# @generated by open-api-generator — do not edit by hand

from __future__ import annotations

from typing import Annotated, Any, Literal, NewType

from pydantic import AwareDatetime, ConfigDict, Field

from allspice.base import InputModel, OpenEnum, ReadOnlyModel
from allspice.entities import (
    AttachmentEntity,
    BranchEntity,
    CommentEntity,
    CommitEntity,
    DesignReviewEntity,
    DesignReviewReviewEntity,
    IssueEntity,
    MilestoneEntity,
    OrganizationEntity,
    ReleaseEntity,
    RepositoryEntity,
    TeamEntity,
    UserEntity,
)


class APIError(ReadOnlyModel):
    category: Annotated[
        str | None,
        Field(
            description='Optional error category. "render" indicates a hardware render failure; omitted for uncategorized errors.'
        ),
    ] = None
    message: str | None = None
    url: str | None = None


class AccessMode(OpenEnum):
    UNKNOWN = 'unknown'
    none = 'none'
    read = 'read'
    write = 'write'
    admin = 'admin'
    owner = 'owner'


class AccessModeOption(OpenEnum):
    UNKNOWN = 'unknown'
    read = 'read'
    write = 'write'
    admin = 'admin'


class AddTimeOption(InputModel):
    created: AwareDatetime | None = None
    time: Annotated[int, Field(description='time in seconds')]
    user_name: Annotated[
        str | None, Field(description='User who spent the time (optional)')
    ] = None


class Attachment(AttachmentEntity):
    browser_download_url: str
    created_at: AwareDatetime
    download_count: int
    id: int
    name: str
    size: int
    uuid: str


class CommitAffectedFiles(ReadOnlyModel):
    filename: str | None = None
    status: str | None = None


class CommitDateOptions(InputModel):
    author: AwareDatetime | None = None
    committer: AwareDatetime | None = None


class CommitMeta(ReadOnlyModel):
    created: AwareDatetime | None = None
    sha: str | None = None
    url: str | None = None


class CommitStats(ReadOnlyModel):
    additions: int | None = None
    deletions: int | None = None
    total: int | None = None


class CommitStatusState(OpenEnum):
    UNKNOWN = 'unknown'
    pending = 'pending'
    success = 'success'
    error = 'error'
    failure = 'failure'
    warning = 'warning'


class CommitUser(ReadOnlyModel):
    date: str | None = None
    email: str | None = None
    name: str | None = None


class CreateBranchRepoOption(InputModel):
    new_branch_name: Annotated[str, Field(description='Name of the branch to create')]
    old_branch_name: Annotated[
        str | None,
        Field(description='Deprecated: true\nName of the old branch to create from'),
    ] = None
    old_ref_name: Annotated[
        str | None,
        Field(description='Name of the old branch/tag/commit to create from'),
    ] = None


class Type(OpenEnum):
    UNKNOWN = 'unknown'
    dingtalk = 'dingtalk'
    discord = 'discord'
    gitea = 'gitea'
    gogs = 'gogs'
    msteams = 'msteams'
    slack = 'slack'
    telegram = 'telegram'
    feishu = 'feishu'
    wechatwork = 'wechatwork'
    packagist = 'packagist'


CreateHookOptionConfig = dict[str, str]


class CreateIssueCommentOption(InputModel):
    body: str


class CreateIssueOption(InputModel):
    assignee: Annotated[str | None, Field(description='deprecated')] = None
    assignees: list[str] | None = None
    body: str | None = None
    closed: bool | None = None
    due_date: AwareDatetime | None = None
    labels: Annotated[list[int] | None, Field(description='list of label ids')] = None
    milestone: Annotated[int | None, Field(description='milestone id')] = None
    ref: str | None = None
    title: str


class CreateDesignReviewOption(InputModel):
    assignee: str | None = None
    assignees: list[str] | None = None
    base: str | None = None
    body: str | None = None
    due_date: AwareDatetime | None = None
    head: str | None = None
    labels: list[int] | None = None
    milestone: int | None = None
    reviewers: list[str] | None = None
    team_reviewers: list[str] | None = None
    title: str | None = None


class CreateDesignReviewReviewComment(InputModel):
    body: str | None = None
    new_position: Annotated[
        int | None, Field(description='if comment to new file line or 0')
    ] = None
    old_position: Annotated[
        int | None, Field(description='if comment to old file line or 0')
    ] = None
    path: Annotated[str | None, Field(description='the tree path')] = None
    sub_path: str | None = None


class CreateReleaseOption(InputModel):
    body: str | None = None
    draft: bool | None = None
    name: str | None = None
    prerelease: bool | None = None
    tag_name: str
    target_commitish: str | None = None


class ObjectFormatName(OpenEnum):
    UNKNOWN = 'unknown'
    sha1 = 'sha1'
    sha256 = 'sha256'


class TrustModel(OpenEnum):
    UNKNOWN = 'unknown'
    default = 'default'
    collaborator = 'collaborator'
    committer = 'committer'
    collaboratorcommitter = 'collaboratorcommitter'


class CreateRepoOption(InputModel):
    auto_init: Annotated[
        bool | None,
        Field(description='Whether the repository should be auto-initialized?'),
    ] = None
    create_develop_branch: Annotated[
        bool | None,
        Field(
            description='Whether to initialize the repository with a secondary develop branch'
        ),
    ] = None
    default_branch: Annotated[
        str | None,
        Field(
            description='DefaultBranch of the repository (used when initializes and in template)'
        ),
    ] = None
    description: Annotated[
        str | None, Field(description='Description of the repository to create')
    ] = None
    gitignores: Annotated[str | None, Field(description='Gitignores to use')] = None
    issue_labels: Annotated[str | None, Field(description='Label-Set to use')] = None
    license: Annotated[str | None, Field(description='License to use')] = None
    name: Annotated[str, Field(description='Name of the repository to create')]
    object_format_name: Annotated[
        ObjectFormatName | None,
        Field(description='ObjectFormatName of the underlying git repository'),
    ] = None
    private: Annotated[
        bool | None, Field(description='Whether the repository is private')
    ] = None
    readme: Annotated[
        str | None, Field(description='Readme of the repository to create')
    ] = None
    template: Annotated[
        bool | None, Field(description='Whether the repository is template')
    ] = None
    trust_model: Annotated[
        TrustModel | None, Field(description='TrustModel of the repository')
    ] = None


class CreateStatusOption(InputModel):
    context: str | None = None
    description: str | None = None
    state: CommitStatusState | None = None
    target_url: str | None = None


class CreateTeamOption(InputModel):
    can_create_org_repo: bool | None = None
    description: str | None = None
    includes_all_repositories: bool | None = None
    name: str
    permission: AccessModeOption | None = None
    units: Annotated[
        list[str] | None,
        Field(
            examples=[
                [
                    'repo.actions',
                    'repo.code',
                    'repo.issues',
                    'repo.ext_issues',
                    'repo.wiki',
                    'repo.ext_wiki',
                    'repo.pulls',
                    'repo.releases',
                    'repo.projects',
                    'repo.ext_wiki',
                ]
            ]
        ),
    ] = None
    units_map: Annotated[
        dict[str, str] | None,
        Field(
            examples=[
                {
                    'repo.code': 'read',
                    'repo.issues': 'write',
                    'repo.ext_issues': 'none',
                    'repo.wiki': 'admin',
                    'repo.pulls': 'owner',
                    'repo.releases': 'none',
                    'repo.projects': 'none',
                    'repo.ext_wiki': 'none',
                }
            ]
        ),
    ] = None


class EditAttachmentOptions(InputModel):
    name: str | None = None


class EditIssueCommentOption(InputModel):
    body: str


class EditReleaseOption(InputModel):
    body: str | None = None
    draft: bool | None = None
    name: str | None = None
    prerelease: bool | None = None
    tag_name: str | None = None
    target_commitish: str | None = None


class EditTeamOption(InputModel):
    can_create_org_repo: bool | None = None
    description: str | None = None
    includes_all_repositories: bool | None = None
    name: str | None = None
    permission: AccessModeOption | None = None
    units: Annotated[
        list[str] | None,
        Field(
            examples=[
                [
                    'repo.code',
                    'repo.issues',
                    'repo.ext_issues',
                    'repo.wiki',
                    'repo.pulls',
                    'repo.releases',
                    'repo.projects',
                    'repo.ext_wiki',
                ]
            ]
        ),
    ] = None
    units_map: Annotated[
        dict[str, str] | None,
        Field(
            examples=[
                {
                    'repo.code': 'read',
                    'repo.ext_issues': 'none',
                    'repo.ext_wiki': 'none',
                    'repo.issues': 'write',
                    'repo.projects': 'none',
                    'repo.pulls': 'owner',
                    'repo.releases': 'none',
                    'repo.wiki': 'admin',
                }
            ]
        ),
    ] = None


class Email(ReadOnlyModel):
    email: str | None = None
    primary: bool | None = None
    user_id: int | None = None
    username: str | None = None
    verified: bool | None = None


class ExternalTracker(ReadOnlyModel):
    external_tracker_format: Annotated[
        str | None,
        Field(
            description='External Issue Tracker URL Format. Use the placeholders {user}, {repo} and {index} for the username, repository name and issue index.'
        ),
    ] = None
    external_tracker_regexp_pattern: Annotated[
        str | None, Field(description='External Issue Tracker issue regular expression')
    ] = None
    external_tracker_style: Annotated[
        str | None,
        Field(
            description='External Issue Tracker Number Format, either `numeric`, `alphanumeric`, or `regexp`'
        ),
    ] = None
    external_tracker_url: Annotated[
        str | None, Field(description='URL of external issue tracker.')
    ] = None


class ExternalWiki(ReadOnlyModel):
    external_wiki_url: Annotated[
        str | None, Field(description='URL of external wiki.')
    ] = None


class FileCommitResponse(ReadOnlyModel):
    author: CommitUser | None = None
    committer: CommitUser | None = None
    created: AwareDatetime | None = None
    html_url: str | None = None
    message: str | None = None
    parents: list[CommitMeta] | None = None
    sha: str | None = None
    tree: CommitMeta | None = None
    url: str | None = None


class FileLinksResponse(ReadOnlyModel):
    git: str | None = None
    html: str | None = None
    self: str | None = None


class GitEntry(ReadOnlyModel):
    mode: str
    path: str
    sha: str
    size: int
    type: str
    url: str


class GitTreeResponse(ReadOnlyModel):
    page: int | None = None
    sha: str | None = None
    total_count: int | None = None
    tree: list[GitEntry] | None = None
    truncated: bool | None = None
    url: str | None = None


class Hook(ReadOnlyModel):
    active: bool | None = None
    authorization_header: str | None = None
    branch_filter: str | None = None
    config: dict[str, str] | None = None
    created_at: AwareDatetime | None = None
    events: list[str] | None = None
    id: int | None = None
    type: str | None = None
    updated_at: AwareDatetime | None = None


class Identity(InputModel):
    email: str | None = None
    name: str | None = None


class InternalTracker(ReadOnlyModel):
    allow_only_contributors_to_track_time: Annotated[
        bool | None,
        Field(description='Let only contributors track time (Built-in issue tracker)'),
    ] = None
    enable_issue_dependencies: Annotated[
        bool | None,
        Field(
            description='Enable dependencies for issues and design reviews (Built-in issue tracker)'
        ),
    ] = None
    enable_time_tracker: Annotated[
        bool | None, Field(description='Enable time tracking (Built-in issue tracker)')
    ] = None


class Label(ReadOnlyModel):
    color: Annotated[str | None, Field(examples=['00aabb'])] = None
    description: str | None = None
    exclusive: Annotated[bool | None, Field(examples=[False])] = None
    id: int | None = None
    is_archived: Annotated[bool | None, Field(examples=[False])] = None
    name: str | None = None
    url: str | None = None


class Do(OpenEnum):
    UNKNOWN = 'unknown'
    merge = 'merge'
    rebase = 'rebase'
    rebase_merge = 'rebase-merge'
    squash = 'squash'
    fast_forward_only = 'fast-forward-only'
    manually_merged = 'manually-merged'


class MergeDesignReviewOption(InputModel):
    do: Annotated[Do, Field(alias='Do')]
    merge_commit_id: Annotated[str | None, Field(alias='MergeCommitID')] = None
    merge_message_field: Annotated[str | None, Field(alias='MergeMessageField')] = None
    merge_title_field: Annotated[str | None, Field(alias='MergeTitleField')] = None
    delete_branch_after_merge: bool | None = None
    force_merge: bool | None = None
    head_commit_id: str | None = None
    merge_when_checks_succeed: bool | None = None


class PayloadUser(ReadOnlyModel):
    email: str | None = None
    name: Annotated[str | None, Field(description='Full name of the commit author')] = (
        None
    )
    username: str | None = None


class Permission(ReadOnlyModel):
    admin: bool | None = None
    pull: bool | None = None
    push: bool | None = None


class ProjectWarning(ReadOnlyModel):
    detail: str | None = None
    file_path: str | None = None


ProjectWarnings = list[ProjectWarning]


class DesignReviewMeta(ReadOnlyModel):
    draft: bool | None = None
    html_url: str | None = None
    merged: bool | None = None
    merged_at: AwareDatetime | None = None


class RepositoryMeta(ReadOnlyModel):
    full_name: str | None = None
    id: int | None = None
    name: str | None = None
    owner: str | None = None


class ReviewStateType(OpenEnum):
    UNKNOWN = 'unknown'
    approved = 'APPROVED'
    pending = 'PENDING'
    comment = 'COMMENT'
    request_changes = 'REQUEST_CHANGES'
    request_review = 'REQUEST_REVIEW'


class ServerVersion(ReadOnlyModel):
    version: str | None = None


class StateType(OpenEnum):
    UNKNOWN = 'unknown'
    open = 'open'
    closed = 'closed'


class StateTypeFilter(OpenEnum):
    UNKNOWN = 'unknown'
    open = 'open'
    closed = 'closed'
    all = 'all'


class SubmitDesignReviewReviewOptions(InputModel):
    body: str | None = None
    event: ReviewStateType | None = None


TimeStamp = NewType("TimeStamp", int)


class TopicNamesResponse(ReadOnlyModel):
    topics: list[str] | None = None


class TransferRepoOption(InputModel):
    new_owner: str
    team_ids: Annotated[
        list[int] | None,
        Field(
            description='ID of the team or teams to add to the repository. Teams can only be added to organization-owned repositories.'
        ),
    ] = None


class UpdateFileOptions(InputModel):
    author: Identity | None = None
    branch: Annotated[
        str | None,
        Field(
            description='branch (optional) to base this file from. if not given, the default branch is used'
        ),
    ] = None
    committer: Identity | None = None
    content: Annotated[str, Field(description='content must be base64 encoded')]
    dates: CommitDateOptions | None = None
    from_path: Annotated[
        str | None,
        Field(
            description='from_path (optional) is the path of the original file which will be moved/renamed to the path in the URL'
        ),
    ] = None
    message: Annotated[
        str | None,
        Field(
            description='message (optional) for the commit of this file. if not supplied, a default message will be used'
        ),
    ] = None
    new_branch: Annotated[
        str | None,
        Field(
            description='new_branch (optional) will make a new branch from `branch` before creating the file'
        ),
    ] = None
    sha: Annotated[
        str, Field(description='sha is the SHA for the file that already exists')
    ]
    signoff: Annotated[
        bool | None,
        Field(
            description='Add a Signed-off-by trailer by the committer at the end of the commit log message.'
        ),
    ] = None


class UserHeatmapData(ReadOnlyModel):
    contributions: int | None = None
    timestamp: TimeStamp | None = None


class VisibleType(OpenEnum):
    UNKNOWN = 'unknown'
    public = 'public'
    limited = 'limited'
    private = 'private'


Angle = NewType("Angle", float)


AttributeId = NewType("AttributeId", str)


BezierId = NewType("BezierId", str)


BitmapId = NewType("BitmapId", str)


class BorderLabelDigits(OpenEnum):
    UNKNOWN = 'unknown'
    uppercase_alphabet = 'UppercaseAlphabet'
    arabic_numeral = 'ArabicNumeral'


class BoundsTag(OpenEnum):
    UNKNOWN = 'unknown'
    angle = 'angle'
    point = 'point'


class CadDocumentType(OpenEnum):
    UNKNOWN = 'unknown'
    project = 'Project'
    pcb = 'Pcb'
    pcb_component_library = 'PcbComponentLibrary'
    schematic = 'Schematic'
    schematic_component_library = 'SchematicComponentLibrary'


Color = NewType("Color", str)


class ComponentFlags(ReadOnlyModel):
    exclude_from_bom: bool | None = None


ComponentId = NewType("ComponentId", str)


class ComponentLink(ReadOnlyModel):
    path: str
    display_text: str


class CornerRadius1(OpenEnum):
    UNKNOWN = 'unknown'
    none = 'None'


class CustomPadDrawingOption1(OpenEnum):
    UNKNOWN = 'unknown'
    filled = 'Filled'


Degree = Literal['degree']


DirectiveLabelId = NewType("DirectiveLabelId", str)


EllipseId = NewType("EllipseId", str)


class ExternalDesignBlock(ReadOnlyModel):
    id: str
    path: Annotated[
        str,
        Field(
            description='Relative to the project root. Uses forward slashes as path separator.'
        ),
    ]


FontId = NewType("FontId", str)


class HarnessConnectorSide(OpenEnum):
    UNKNOWN = 'unknown'
    right = 'Right'
    left = 'Left'
    up = 'Up'
    down = 'Down'


HarnessEntryId = NewType("HarnessEntryId", str)


HarnessId = NewType("HarnessId", str)


class HorizontalJustification(OpenEnum):
    UNKNOWN = 'unknown'
    left = 'Left'
    center = 'Center'
    right = 'Right'


JunctionId = NewType("JunctionId", str)


LayerId = NewType("LayerId", int)


Length = NewType("Length", float)


class LineStyle(OpenEnum):
    UNKNOWN = 'unknown'
    solid = 'solid'
    dashed = 'dashed'
    dotted = 'dotted'
    dash_dot = 'dash_dot'
    dash_dot_dot = 'dash_dot_dot'
    dense_dot = 'dense_dot'


Meters = NewType("Meters", float)


Millimeter = Literal['mm']


NetId = NewType("NetId", str)


NetLabelId = NewType("NetLabelId", str)


NoConnectSymbolId = NewType("NoConnectSymbolId", str)


class PadHoleCircle(ReadOnlyModel):
    radius: Length


class PadHoleRectangle(ReadOnlyModel):
    width: Length
    height: Length


class PadHoleShape1(ReadOnlyModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    circle: Annotated[PadHoleCircle, Field(alias='Circle')]


class PadHoleShape3(ReadOnlyModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rectangle: Annotated[PadHoleRectangle, Field(alias='Rectangle')]


class PadHoleSlot(ReadOnlyModel):
    width: Length
    height: Length


PadId = NewType("PadId", str)


class PadShapeCircle(ReadOnlyModel):
    radius: Length


class PadShapeOctagon(ReadOnlyModel):
    width: Length
    height: Length


class PadShapePill(ReadOnlyModel):
    width: Length
    height: Length


class PadShapeRectangle(ReadOnlyModel):
    width: Length
    height: Length
    x_radius: Length
    y_radius: Length


PadstackId = NewType("PadstackId", str)


class PageBorderMargin(ReadOnlyModel):
    left: Length
    right: Length
    top: Length
    bottom: Length


class ParameterSetStyle(OpenEnum):
    UNKNOWN = 'unknown'
    large = 'Large'
    tiny = 'Tiny'
    differential_pair = 'DifferentialPair'


PcbArcId = NewType("PcbArcId", str)


class PcbComponentLibDocumentType(OpenEnum):
    UNKNOWN = 'unknown'
    pcb_component_lib = 'PcbComponentLib'


class PcbDocumentType(OpenEnum):
    UNKNOWN = 'unknown'
    pcb = 'Pcb'


PcbLibComponentId = NewType("PcbLibComponentId", str)


PcbTextId = NewType("PcbTextId", str)


class PinElectricalType(OpenEnum):
    UNKNOWN = 'unknown'
    input = 'Input'
    io = 'Io'
    hi_z = 'HiZ'
    open_collector = 'OpenCollector'
    open_emitter = 'OpenEmitter'
    output = 'Output'
    passive = 'Passive'
    power = 'Power'
    no_connect = 'NoConnect'
    unspecified = 'Unspecified'
    power_in = 'PowerIn'
    power_out = 'PowerOut'


PinId = NewType("PinId", str)


class PinOrientation(OpenEnum):
    UNKNOWN = 'unknown'
    left = 'Left'
    right = 'Right'
    up = 'Up'
    down = 'Down'


class PinTextRelativeTo(OpenEnum):
    UNKNOWN = 'unknown'
    pin = 'Pin'
    component = 'Component'


class Point(ReadOnlyModel):
    x: Length
    y: Length


PolygonId = NewType("PolygonId", str)


PolylineId = NewType("PolylineId", str)


PortId = NewType("PortId", str)


class ProjectDocument(ReadOnlyModel):
    id: str
    path: Annotated[
        str,
        Field(
            description='Relative to the project root. Uses forward slashes as path separator.'
        ),
    ]
    ty: Annotated[
        CadDocumentType | None,
        Field(description='The type of ECAD Document. Omitted if null.'),
    ] = None


class ProjectDocumentType(OpenEnum):
    UNKNOWN = 'unknown'
    project = 'Project'


Pt = NewType("Pt", float)


RectangleId = NewType("RectangleId", str)


RegionDirectiveId = NewType("RegionDirectiveId", str)


RegionId = NewType("RegionId", str)


class RegionType(OpenEnum):
    UNKNOWN = 'unknown'
    fill = 'Fill'
    cutout = 'Cutout'
    keep_out = 'KeepOut'
    cavity = 'Cavity'
    board_cutout = 'BoardCutout'


class RelativePinTextOrientation(OpenEnum):
    UNKNOWN = 'unknown'
    parallel = 'Parallel'
    perpendicular = 'Perpendicular'


Overline = tuple[str, bool]


class RichText(ReadOnlyModel):
    display: str
    overlines: Annotated[
        list[Overline] | None, Field(description='null when no overlines.')
    ] = None
    component_links: list[ComponentLink] | None = None


SchArcId = NewType("SchArcId", str)


SchComponentId = NewType("SchComponentId", str)


SchLibComponentId = NewType("SchLibComponentId", str)


SchTextId = NewType("SchTextId", str)


class SchematicComponentLibDocumentType(OpenEnum):
    UNKNOWN = 'unknown'
    schematic_component_lib = 'SchematicComponentLib'


class SchematicDocumentType(OpenEnum):
    UNKNOWN = 'unknown'
    schematic = 'Schematic'


class SchematicNet(ReadOnlyModel):
    id: NetId
    name: str


SchematicPageGroupId = NewType("SchematicPageGroupId", str)


class SchematicPageGroupParentReference(ReadOnlyModel):
    parent_page_id: str


SchematicPageId = NewType("SchematicPageId", str)


SheetEntryId = NewType("SheetEntryId", str)


class SheetEntryType(OpenEnum):
    UNKNOWN = 'unknown'
    input = 'Input'
    output = 'Output'
    bi_directional = 'BiDirectional'
    tri_state = 'TriState'
    passive = 'Passive'


SheetRefId = NewType("SheetRefId", str)


SymbolId = NewType("SymbolId", int)


class SymbolRef1(OpenEnum):
    UNKNOWN = 'unknown'
    all_symbols = 'AllSymbols'


class SymbolRef2(ReadOnlyModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    symbol: Annotated[SymbolId, Field(alias='Symbol')]


SymbolRef = SymbolRef1 | SymbolRef2


class TextDecorations(ReadOnlyModel):
    is_underline: bool
    is_strikethrough: bool


class TextFrame(ReadOnlyModel):
    position: Point
    width: Length
    height: Length
    line_width: Length
    line_style: LineStyle | None = None
    show_border: bool
    margin: Length
    is_filled: bool
    fill_color: Color
    border_color: Color
    clip_to_bounds: bool
    wrap_width: Meters | None = None


TitleBlockId = NewType("TitleBlockId", str)


class Track(ReadOnlyModel):
    points: list[Point]
    line_width: Length
    layer_id: LayerId
    net_id: NetId | None = None
    net_name: str | None = None


TrackId = NewType("TrackId", str)


class Variant(ReadOnlyModel):
    id: str
    description: str


VariantId = NewType("VariantId", str)


class VerticalJustification(OpenEnum):
    UNKNOWN = 'unknown'
    top = 'Top'
    center = 'Center'
    bottom = 'Bottom'


class Via(ReadOnlyModel):
    center: Point
    rotation: Angle
    padstack: PadstackId
    net_id: NetId | None = None
    net_name: str | None = None


ViaId = NewType("ViaId", str)


class Warning(ReadOnlyModel):
    file_path: Annotated[
        str, Field(description='Uses forward slashes as path separator.')
    ]
    detail: str


WireAliasId = NewType("WireAliasId", str)


WireId = NewType("WireId", str)


class ContentsResponse(ReadOnlyModel):
    field_links: Annotated[FileLinksResponse | None, Field(alias='_links')] = None
    content: Annotated[
        str | None,
        Field(
            description='`content` is populated when `type` is `file`, otherwise null'
        ),
    ] = None
    download_url: str | None = None
    encoding: Annotated[
        str | None,
        Field(
            description='`encoding` is populated when `type` is `file`, otherwise null'
        ),
    ] = None
    git_url: str | None = None
    html_url: str | None = None
    last_author_date: AwareDatetime
    last_commit_sha: str
    last_committer_date: AwareDatetime
    name: str
    path: str
    sha: str
    size: int
    submodule_git_url: Annotated[
        str | None,
        Field(
            description='`submodule_git_url` is populated when `type` is `submodule`, otherwise null'
        ),
    ] = None
    target: Annotated[
        str | None,
        Field(
            description='`target` is populated when `type` is `symlink`, otherwise null'
        ),
    ] = None
    type: Annotated[
        str,
        Field(description='`type` will be `file`, `dir`, `symlink`, or `submodule`'),
    ]
    url: str | None = None


class CreateFileOptions(InputModel):
    author: Identity | None = None
    branch: Annotated[
        str | None,
        Field(
            description='branch (optional) to base this file from. if not given, the default branch is used'
        ),
    ] = None
    committer: Identity | None = None
    content: Annotated[str, Field(description='content must be base64 encoded')]
    dates: CommitDateOptions | None = None
    message: Annotated[
        str | None,
        Field(
            description='message (optional) for the commit of this file. if not supplied, a default message will be used'
        ),
    ] = None
    new_branch: Annotated[
        str | None,
        Field(
            description='new_branch (optional) will make a new branch from `branch` before creating the file'
        ),
    ] = None
    signoff: Annotated[
        bool | None,
        Field(
            description='Add a Signed-off-by trailer by the committer at the end of the commit log message.'
        ),
    ] = None


class CreateHookOption(InputModel):
    active: bool | None = False
    authorization_header: str | None = None
    branch_filter: str | None = None
    config: CreateHookOptionConfig
    events: list[str] | None = None
    type: Type


class CreateMilestoneOption(InputModel):
    description: str | None = None
    due_on: AwareDatetime | None = None
    state: StateType | None = None
    title: str | None = None


class CreateOrgOption(InputModel):
    description: str | None = None
    email: str | None = None
    full_name: str | None = None
    location: str | None = None
    repo_admin_change_team_access: bool | None = None
    username: str
    visibility: VisibleType | None = None
    website: str | None = None


class CreateDesignReviewReviewOptions(InputModel):
    body: str | None = None
    comments: list[CreateDesignReviewReviewComment] | None = None
    commit_id: str | None = None
    event: ReviewStateType | None = None


class CreateUserOption(InputModel):
    created_at: Annotated[
        AwareDatetime | None,
        Field(
            description='For explicitly setting the user creation timestamp. Useful when users are\nmigrated from other systems. When omitted, the user\'s creation timestamp\nwill be set to "now".'
        ),
    ] = None
    email: str
    full_name: str | None = None
    login_name: str | None = None
    must_change_password: bool | None = None
    password: str | None = None
    restricted: bool | None = None
    send_notify: bool | None = None
    source_id: int | None = None
    username: str
    visibility: VisibleType | None = None


class DeleteFileOptions(InputModel):
    author: Identity | None = None
    branch: Annotated[
        str | None,
        Field(
            description='branch (optional) to base this file from. if not given, the default branch is used'
        ),
    ] = None
    committer: Identity | None = None
    dates: CommitDateOptions | None = None
    message: Annotated[
        str | None,
        Field(
            description='message (optional) for the commit of this file. if not supplied, a default message will be used'
        ),
    ] = None
    new_branch: Annotated[
        str | None,
        Field(
            description='new_branch (optional) will make a new branch from `branch` before creating the file'
        ),
    ] = None
    sha: Annotated[
        str, Field(description='sha is the SHA for the file that already exists')
    ]
    signoff: Annotated[
        bool | None,
        Field(
            description='Add a Signed-off-by trailer by the committer at the end of the commit log message.'
        ),
    ] = None


class EditIssueOption(InputModel):
    assignee: Annotated[str | None, Field(description='deprecated')] = None
    assignees: list[str] | None = None
    body: str | None = None
    due_date: AwareDatetime | None = None
    milestone: int | None = None
    ref: str | None = None
    state: StateType | None = None
    title: str | None = None
    unset_due_date: bool | None = None


class EditOrgOption(InputModel):
    description: str | None = None
    email: str | None = None
    full_name: str | None = None
    location: str | None = None
    repo_admin_change_team_access: bool | None = None
    visibility: VisibleType | None = None
    website: str | None = None


class EditDesignReviewOption(InputModel):
    allow_maintainer_edit: bool | None = None
    assignee: str | None = None
    assignees: list[str] | None = None
    base: str | None = None
    body: str | None = None
    due_date: AwareDatetime | None = None
    labels: list[int] | None = None
    milestone: int | None = None
    state: StateType | None = None
    title: str | None = None
    unset_due_date: bool | None = None


class EditRepoOption(InputModel):
    allow_fast_forward_only_merge: Annotated[
        bool | None,
        Field(
            description='either `true` to allow fast-forward-only merging design reviews, or `false` to prevent fast-forward-only merging.'
        ),
    ] = None
    allow_manual_merge: Annotated[
        bool | None,
        Field(
            description='either `true` to allow mark pr as merged manually, or `false` to prevent it.'
        ),
    ] = None
    allow_merge_commits: Annotated[
        bool | None,
        Field(
            description='either `true` to allow merging design reviews with a merge commit, or `false` to prevent merging design reviews with merge commits.'
        ),
    ] = None
    allow_rebase: Annotated[
        bool | None,
        Field(
            description='either `true` to allow rebase-merging design reviews, or `false` to prevent rebase-merging.'
        ),
    ] = None
    allow_rebase_explicit: Annotated[
        bool | None,
        Field(
            description='either `true` to allow rebase with explicit merge commits (--no-ff), or `false` to prevent rebase with explicit merge commits.'
        ),
    ] = None
    allow_rebase_update: Annotated[
        bool | None,
        Field(
            description='either `true` to allow updating design review branch by rebase, or `false` to prevent it.'
        ),
    ] = None
    allow_squash_merge: Annotated[
        bool | None,
        Field(
            description='either `true` to allow squash-merging design reviews, or `false` to prevent squash-merging.'
        ),
    ] = None
    archived: Annotated[
        bool | None, Field(description='set to `true` to archive this repository.')
    ] = None
    autodetect_manual_merge: Annotated[
        bool | None,
        Field(
            description='either `true` to enable AutodetectManualMerge, or `false` to prevent it. Note: In some special cases, misjudgments can occur.'
        ),
    ] = None
    default_allow_maintainer_edit: Annotated[
        bool | None,
        Field(description='set to `true` to allow edits from maintainers by default'),
    ] = None
    default_branch: Annotated[
        str | None, Field(description='sets the default branch for this repository.')
    ] = None
    default_delete_branch_after_merge: Annotated[
        bool | None,
        Field(description='set to `true` to delete pr branch after merge by default'),
    ] = None
    default_merge_style: Annotated[
        str | None,
        Field(
            description='set to a merge style to be used by this repository: "merge", "rebase", "rebase-merge", "squash", or "fast-forward-only".'
        ),
    ] = None
    description: Annotated[
        str | None, Field(description='a short description of the repository.')
    ] = None
    enable_prune: Annotated[
        bool | None,
        Field(
            description='enable prune - remove obsolete remote-tracking references when mirroring'
        ),
    ] = None
    external_tracker: ExternalTracker | None = None
    external_wiki: ExternalWiki | None = None
    has_actions: Annotated[
        bool | None,
        Field(
            description='either `true` to enable actions unit, or `false` to disable them.'
        ),
    ] = None
    has_issues: Annotated[
        bool | None,
        Field(
            description='either `true` to enable issues for this repository or `false` to disable them.'
        ),
    ] = None
    has_packages: Annotated[
        bool | None,
        Field(
            description='either `true` to enable packages unit, or `false` to disable them.'
        ),
    ] = None
    has_projects: Annotated[
        bool | None,
        Field(
            description='either `true` to enable project unit, or `false` to disable them.'
        ),
    ] = None
    has_pull_requests: Annotated[
        bool | None,
        Field(
            description='either `true` to allow design reviews, or `false` to prevent design review.'
        ),
    ] = None
    has_releases: Annotated[
        bool | None,
        Field(
            description='either `true` to enable releases unit, or `false` to disable them.'
        ),
    ] = None
    has_wiki: Annotated[
        bool | None,
        Field(
            description='either `true` to enable the wiki for this repository or `false` to disable it.'
        ),
    ] = None
    ignore_whitespace_conflicts: Annotated[
        bool | None,
        Field(
            description='either `true` to ignore whitespace for conflicts, or `false` to not ignore whitespace.'
        ),
    ] = None
    internal_tracker: InternalTracker | None = None
    mirror_interval: Annotated[
        str | None,
        Field(
            description='set to a string like `8h30m0s` to set the mirror interval time'
        ),
    ] = None
    name: Annotated[str | None, Field(description='name of the repository')] = None
    private: Annotated[
        bool | None,
        Field(
            description='either `true` to make the repository private or `false` to make it public.\nNote: you will get a 422 error if the organization restricts changing repository visibility to organization\nowners and a non-owner tries to change the value of private.'
        ),
    ] = None
    projects_mode: Annotated[
        str | None,
        Field(
            description='`repo` to only allow repo-level projects, `owner` to only allow owner projects, `all` to allow both.'
        ),
    ] = None
    template: Annotated[
        bool | None,
        Field(
            description='either `true` to make this repository a template or `false` to make it a normal repository'
        ),
    ] = None
    website: Annotated[
        str | None,
        Field(description='a URL with more information about the repository.'),
    ] = None


class EditUserOption(InputModel):
    active: bool | None = None
    admin: bool | None = None
    allow_create_organization: bool | None = None
    allow_git_hook: bool | None = None
    allow_import_local: bool | None = None
    description: str | None = None
    email: str | None = None
    full_name: str | None = None
    location: str | None = None
    login_name: str
    max_repo_creation: int | None = None
    must_change_password: bool | None = None
    password: str | None = None
    prohibit_login: bool | None = None
    restricted: bool | None = None
    source_id: int | None = None
    visibility: VisibleType | None = None
    website: str | None = None


class Milestone(MilestoneEntity):
    closed_at: AwareDatetime | None = None
    closed_issues: int
    created_at: AwareDatetime
    description: str
    due_on: AwareDatetime | None = None
    id: int
    open_issues: int
    state: StateType
    title: str
    updated_at: AwareDatetime | None = None


class Organization(OrganizationEntity):
    avatar_url: str
    description: str
    email: str
    full_name: str
    id: int
    location: str
    name: str
    repo_admin_change_team_access: bool
    username: Annotated[str, Field(deprecated=True, description='deprecated')]
    visibility: VisibleType
    website: str


class PayloadCommitVerification(ReadOnlyModel):
    payload: str | None = None
    reason: str | None = None
    signature: str | None = None
    signer: PayloadUser | None = None
    verified: bool | None = None


class ProjectData(ReadOnlyModel):
    documents: Annotated[
        dict[str, str] | None,
        Field(
            description='Mapping of component reference to the document path that defines it.'
        ),
    ] = None
    external_design_blocks: Annotated[
        dict[str, str] | None,
        Field(
            description='Mapping of external design block reference to the HTML URL of its sheet, used to resolve device sheets in submodules.'
        ),
    ] = None
    project_path: Annotated[
        str | None,
        Field(description='Path of the project file, relative to the repo root.'),
    ] = None
    variants: Annotated[
        dict[str, str] | None,
        Field(description='Mapping of variant id to its human-readable name.'),
    ] = None
    warnings: ProjectWarnings | None = None


class RepoCommit(ReadOnlyModel):
    author: CommitUser | None = None
    committer: CommitUser | None = None
    message: str | None = None
    tree: CommitMeta | None = None
    url: str | None = None
    verification: PayloadCommitVerification | None = None


class Team(TeamEntity):
    can_create_org_repo: bool
    description: str
    id: int
    includes_all_repositories: bool
    name: str
    organization: Organization | None = None
    permission: AccessMode
    units: Annotated[
        list[str] | None,
        Field(
            deprecated=True,
            examples=[
                [
                    'repo.code',
                    'repo.issues',
                    'repo.ext_issues',
                    'repo.wiki',
                    'repo.pulls',
                    'repo.releases',
                    'repo.projects',
                    'repo.ext_wiki',
                ]
            ],
        ),
    ] = None
    units_map: Annotated[
        dict[str, str],
        Field(
            examples=[
                {
                    'repo.code': 'read',
                    'repo.ext_issues': 'none',
                    'repo.ext_wiki': 'none',
                    'repo.issues': 'write',
                    'repo.projects': 'none',
                    'repo.pulls': 'owner',
                    'repo.releases': 'none',
                    'repo.wiki': 'admin',
                }
            ]
        ),
    ]


class User(UserEntity):
    active: Annotated[bool | None, Field(description='Is user active')] = None
    avatar_url: Annotated[str, Field(description="URL to the user's avatar")]
    created: AwareDatetime
    description: Annotated[str, Field(description="the user's description")]
    email: str
    followers_count: Annotated[int, Field(description='user counts')]
    following_count: int
    full_name: Annotated[str, Field(description="the user's full name")]
    html_url: Annotated[str, Field(description="URL to the user's gitea page")]
    id: Annotated[int, Field(description="the user's id")]
    is_admin: Annotated[
        bool | None, Field(description='Is the user an administrator')
    ] = None
    language: Annotated[str | None, Field(description='User locale')] = None
    last_login: AwareDatetime | None = None
    location: Annotated[str, Field(description="the user's location")]
    login: Annotated[str, Field(description="the user's username")]
    login_name: Annotated[
        str | None, Field(description="the user's authentication sign-in name.")
    ] = 'empty'
    prohibit_login: Annotated[
        bool | None, Field(description='Is user login prohibited')
    ] = None
    restricted: Annotated[bool, Field(description='Is user restricted')]
    source_id: Annotated[
        int | None, Field(description="The ID of the user's Authentication Source")
    ] = None
    starred_repos_count: int
    visibility: VisibleType
    website: Annotated[str, Field(description="the user's website")]


class Bezier(ReadOnlyModel):
    id: BezierId
    symbol: SymbolRef
    is_visible: bool
    color: Color
    line_width: Length
    line_style: LineStyle | None = None
    points: list[Point]
    is_filled: bool
    fill_color: Color


class Bitmap(ReadOnlyModel):
    id: BitmapId
    symbol: SymbolRef
    bottom_left: Point
    width: Length
    height: Length
    is_visible: bool | None = None


class Border(ReadOnlyModel):
    line_width: Length
    padding: Length


class BorderLabelFormat(ReadOnlyModel):
    width: Length
    count: Annotated[int, Field(ge=0)]
    numbering: BorderLabelDigits
    ascending: bool


class Circular(ReadOnlyModel):
    radius: Meters


class CornerRadius2(ReadOnlyModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    circular: Annotated[Circular, Field(alias='Circular')]


class Xy(ReadOnlyModel):
    radius_x: Meters
    radius_y: Meters


class CornerRadius3(ReadOnlyModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    xy: Annotated[Xy, Field(alias='Xy')]


CornerRadius = CornerRadius1 | CornerRadius2 | CornerRadius3


class Outline(ReadOnlyModel):
    stroke_width: Meters


class CustomPadDrawingOption2(ReadOnlyModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outline: Annotated[Outline, Field(alias='Outline')]


CustomPadDrawingOption = CustomPadDrawingOption1 | CustomPadDrawingOption2


class Ellipse(ReadOnlyModel):
    id: EllipseId
    symbol: SymbolRef
    is_visible: bool
    color: Color
    line_width: Length
    line_style: LineStyle | None = None
    is_filled: bool
    fill_color: Color
    center: Point
    radius: Point
    is_transparent: bool


class Font(ReadOnlyModel):
    family: str
    pt: Pt
    weight: float
    letter_spacing: Pt | None = None
    stroke_width: Meters | None = None
    is_italic: bool
    is_bold: bool
    decorations: TextDecorations
    is_truetype: bool


class HarnessEntry(ReadOnlyModel):
    id: HarnessEntryId
    name: str
    display_name: RichText | None = None
    distance_from_top: Length
    text_color: Color
    font_id: FontId


class HarnessLabel(ReadOnlyModel):
    text: str
    position: Point
    orientation: Angle
    color: Color
    font_id: FontId
    is_visible: bool


class Junction(ReadOnlyModel):
    id: JunctionId
    position: Point
    color: Color
    diameter: Length


class Layer(ReadOnlyModel):
    id: LayerId
    name: str
    is_visible: bool | None = False


class Net(ReadOnlyModel):
    id: NetId
    name: str | None = None


class NoConnectSymbol(ReadOnlyModel):
    position: Point
    net_id: NetId | None = None


class Pad(ReadOnlyModel):
    designator: str
    center: Point
    rotation: Angle
    padstack: PadstackId
    net_id: NetId | None = None
    net_name: str | None = None


class PadHoleShape2(ReadOnlyModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    slot: Annotated[PadHoleSlot, Field(alias='Slot')]


PadHoleShape = PadHoleShape1 | PadHoleShape2 | PadHoleShape3


class PadShape1(ReadOnlyModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    circle: Annotated[PadShapeCircle, Field(alias='Circle')]


class PadShape2(ReadOnlyModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pill: Annotated[PadShapePill, Field(alias='Pill')]


class PadShape3(ReadOnlyModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rectangle: Annotated[PadShapeRectangle, Field(alias='Rectangle')]


class PadShape4(ReadOnlyModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    octagon: Annotated[PadShapeOctagon, Field(alias='Octagon')]


class PageBorder(ReadOnlyModel):
    stroke_width: Length
    margin: PageBorderMargin
    horizontal_label: BorderLabelFormat
    vertical_label: BorderLabelFormat


class Path(ReadOnlyModel):
    start: Point


class PcbArc(ReadOnlyModel):
    center: Point
    radius_pair: Point
    bounds_tag: BoundsTag
    start_angle: Angle
    end_angle: Angle
    start_point: Point
    end_point: Point
    line_width: Length
    layer_id: LayerId
    net_id: NetId | None = None
    net_name: str | None = None


class Polygon(ReadOnlyModel):
    id: PolygonId
    symbol: SymbolRef
    is_visible: bool
    color: Color
    points: list[Point]
    line_width: Length
    is_filled: bool
    fill_color: Color


class Polyline(ReadOnlyModel):
    id: PolylineId
    symbol: SymbolRef
    is_visible: bool
    color: Color
    points: list[Point]
    line_width: Length
    is_filled: bool
    fill_color: Color
    line_style: LineStyle | None = None


class Project(ReadOnlyModel):
    documents: list[ProjectDocument]
    variants: list[Variant]
    external_design_blocks: list[ExternalDesignBlock]
    altium_project_pcb_variants_file: Annotated[
        str | None,
        Field(
            description='The path of the altium `.prjpcbvariants` file relative to the repo root. Omitted if null.'
        ),
    ] = None


class ProjectEntryExport(ReadOnlyModel):
    type: ProjectDocumentType
    path: Annotated[
        str,
        Field(
            description='Path relative to the repo root. Uses forward slashes as path separator.'
        ),
    ]
    project: Project
    warnings: Annotated[
        list[Warning],
        Field(
            description='Warnings that occurred during the generation of this project'
        ),
    ]


class Rectangle(ReadOnlyModel):
    id: RectangleId
    symbol: SymbolRef
    is_visible: bool
    color: Color
    line_width: Length
    line_style: LineStyle | None = None
    is_filled: bool
    fill_color: Color
    bottom_left: Point
    width: Length
    height: Length
    is_transparent: bool
    corner_radius: CornerRadius | None = None


class Region(ReadOnlyModel):
    kind: RegionType
    start: Point
    cutouts: list[Path] | None = None
    layer_id: LayerId
    net_id: NetId | None = None
    net_name: str | None = None


class RegionDirective(ReadOnlyModel):
    id: RegionDirectiveId
    position: Point
    outline: Color
    fill: Color
    collapsed: bool
    perimeter: list[Point]
    line_style: LineStyle
    line_width: Meters
    triangle_line_width: Meters


class SchArc(ReadOnlyModel):
    id: SchArcId
    symbol: SymbolRef
    is_visible: bool
    color: Color
    line_width: Length
    is_filled: bool
    fill_color: Color
    line_style: LineStyle | None = None
    center: Point
    radius_pair: Point
    bounds_tag: BoundsTag
    start_angle: Angle
    end_angle: Angle
    start_point: Point
    end_point: Point


class SchLibSymbol(ReadOnlyModel):
    id: SymbolId


class SchematicPageGroupParent(ReadOnlyModel):
    id: str
    reference_in_parent: SchematicPageGroupParentReference | None = None


class TextJustification(ReadOnlyModel):
    horizontal: HorizontalJustification
    vertical: VerticalJustification


class WireAlias(ReadOnlyModel):
    position: Point
    color: Color
    rotation: Angle
    name: str
    justification: TextJustification
    font_id: FontId
    is_visible: bool


class Comment(CommentEntity):
    assets: list[Attachment]
    body: str
    created_at: AwareDatetime
    html_url: str
    id: int
    issue_url: str
    original_author: str
    original_author_id: int
    pull_request_url: str
    updated_at: AwareDatetime
    user: User | None = None


class Commit(CommitEntity):
    author: User | None = None
    commit: RepoCommit | None = None
    committer: User | None = None
    created: AwareDatetime
    files: list[CommitAffectedFiles] | None = None
    html_url: str
    parents: list[CommitMeta]
    sha: str
    stats: CommitStats | None = None
    url: str


class CommitStatus(ReadOnlyModel):
    context: str
    created_at: AwareDatetime
    creator: User | None = None
    description: str
    id: int
    status: CommitStatusState
    target_url: str
    updated_at: AwareDatetime
    url: str


ContentsResponseOrList = ContentsResponse | list[ContentsResponse]


class FileDeleteResponse(ReadOnlyModel):
    commit: FileCommitResponse | None = None
    verification: PayloadCommitVerification | None = None


class FileResponse(ReadOnlyModel):
    commit: FileCommitResponse | None = None
    content: ContentsResponse | None = None
    verification: PayloadCommitVerification | None = None


class Issue(IssueEntity):
    assets: list[Attachment]
    assignee: Annotated[User | None, Field(deprecated=True)] = None
    assignees: list[User] | None = None
    body: str
    closed_at: AwareDatetime | None = None
    comments: int
    created_at: AwareDatetime
    due_date: AwareDatetime | None = None
    html_url: str
    id: int
    is_locked: bool
    labels: list[Label]
    milestone: Milestone | None = None
    number: int
    original_author: str
    original_author_id: int
    pin_order: int
    pull_request: DesignReviewMeta | None = None
    ref: str
    repository: RepositoryMeta | None = None
    state: StateType
    title: str
    updated_at: AwareDatetime
    url: str
    user: User | None = None


class PayloadCommit(ReadOnlyModel):
    added: list[str] | None = None
    author: PayloadUser | None = None
    committer: PayloadUser | None = None
    id: Annotated[str | None, Field(description='sha1 hash of the commit')] = None
    message: str | None = None
    modified: list[str] | None = None
    removed: list[str] | None = None
    timestamp: AwareDatetime | None = None
    url: str | None = None
    verification: PayloadCommitVerification | None = None


class DesignReviewReview(DesignReviewReviewEntity):
    body: str
    comments_count: int
    commit_id: str
    dismissed: bool
    html_url: str
    id: int
    official: bool
    pull_request_url: str
    stale: bool
    state: ReviewStateType
    submitted_at: AwareDatetime
    team: Team | None = None
    updated_at: AwareDatetime
    user: User | None = None


class DesignReviewReviewComment(ReadOnlyModel):
    body: str
    commit_id: str
    created_at: AwareDatetime
    diff_hunk: str
    html_url: str
    id: int
    original_commit_id: str
    original_position: int
    path: str
    position: int
    pull_request_review_id: int
    pull_request_url: str
    resolver: User | None = None
    sub_path: str
    updated_at: AwareDatetime
    user: User | None = None


class Release(ReleaseEntity):
    assets: list[Attachment]
    author: User | None = None
    body: str
    created_at: AwareDatetime
    draft: bool
    html_url: str
    id: int
    name: str
    prerelease: bool
    published_at: AwareDatetime
    tag_name: str
    tarball_url: str
    target_commitish: str
    upload_url: str
    url: str
    zipball_url: str


class RepoTransfer(ReadOnlyModel):
    doer: User | None = None
    recipient: User | None = None
    teams: list[Team] | None = None


class Repository(RepositoryEntity):
    allow_fast_forward_only_merge: bool
    allow_merge_commits: bool
    allow_rebase: bool
    allow_rebase_explicit: bool
    allow_rebase_update: bool
    allow_squash_merge: bool
    archived: bool
    archived_at: AwareDatetime
    avatar_url: str
    clone_url: str
    created_at: AwareDatetime
    default_allow_maintainer_edit: bool
    default_branch: str
    default_delete_branch_after_merge: bool
    default_merge_style: str
    description: str
    empty: bool
    external_tracker: ExternalTracker | None = None
    external_wiki: ExternalWiki | None = None
    fork: bool
    forks_count: int
    full_name: str
    has_actions: bool
    has_issues: bool
    has_packages: bool
    has_projects: bool
    has_pull_requests: bool
    has_releases: bool
    has_wiki: bool
    html_url: str
    id: int
    ignore_whitespace_conflicts: bool
    internal: bool
    internal_tracker: InternalTracker | None = None
    language: str
    languages_url: str
    licenses: list[str]
    link: str
    mirror: bool
    mirror_interval: str
    mirror_updated: AwareDatetime
    name: str
    object_format_name: Annotated[
        ObjectFormatName,
        Field(description='ObjectFormatName of the underlying git repository'),
    ]
    open_issues_count: int
    open_pr_counter: int
    original_url: str
    owner: User
    parent: Repository | None = None
    permissions: Permission | None = None
    private: bool
    projects_mode: str
    release_counter: int
    repo_transfer: RepoTransfer | None = None
    size: int
    ssh_url: str
    stars_count: int
    template: bool
    topics: list[str]
    updated_at: AwareDatetime
    url: str
    watchers_count: int
    website: str


class SearchResults(ReadOnlyModel):
    data: list[Repository] | None = None
    ok: bool | None = None


class TrackedTime(ReadOnlyModel):
    created: AwareDatetime | None = None
    id: int | None = None
    issue: Issue | None = None
    issue_id: Annotated[
        int | None, Field(description='deprecated (only for backwards compatibility)')
    ] = None
    time: Annotated[int | None, Field(description='Time in seconds')] = None
    user_id: Annotated[
        int | None, Field(description='deprecated (only for backwards compatibility)')
    ] = None
    user_name: str | None = None


class Attribute(ReadOnlyModel):
    name: str
    value: str | None = None
    display_text: str | None = None
    symbol: SymbolRef
    position: Point
    is_visible: bool
    show_name: bool | None = None
    orientation: Angle
    justification: TextJustification
    color: Color
    font_id: FontId


class CustomPadShape(ReadOnlyModel):
    geometry: Path
    drawing_options: CustomPadDrawingOption


class DirectiveLabel(ReadOnlyModel):
    id: DirectiveLabelId
    position: Point
    color: Color
    orientation: PinOrientation
    name: str | None = None
    style: ParameterSetStyle
    attributes: dict[AttributeId, Attribute] | None = None


class Harness(ReadOnlyModel):
    id: HarnessId
    position: Point
    width: Length
    height: Length
    connector_side: HarnessConnectorSide
    connection_position: Length
    color: Color
    area_color: Color
    line_width: Length
    name: HarnessLabel | None = None
    harness_entries: dict[HarnessEntryId, HarnessEntry] | None = None


class NetLabel(ReadOnlyModel):
    net_id: NetId | None = None
    position: Point
    color: Color
    font_id: FontId
    justification: TextJustification
    orientation: Angle
    name: str
    display_text: RichText | None = None
    is_visible: bool


class PadHole(ReadOnlyModel):
    offset: Point
    rotation: Angle
    hole: PadHoleShape


class PadShape5(ReadOnlyModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    custom: Annotated[list[CustomPadShape], Field(alias='Custom')]


PadShape = PadShape1 | PadShape2 | PadShape3 | PadShape4 | PadShape5


class PadstackLayer(ReadOnlyModel):
    shape: PadShape
    offset: Point


class PcbText(ReadOnlyModel):
    text: str
    position: Point
    rotation: Annotated[Angle | None, Field(description='Absent when zero.')] = None
    width: Length | None = None
    height: Length
    border: Border | None = None
    font_id: FontId
    justification: TextJustification
    is_mirrored: bool
    is_designator: bool
    is_comment: bool
    is_hidden: bool
    layer_id: LayerId
    net_id: NetId | None = None
    net_name: str | None = None


class PinTextPositionInfo(ReadOnlyModel):
    margin: Length
    orientation: RelativePinTextOrientation
    relative_to: PinTextRelativeTo
    justification: TextJustification | None = None


class SchText(ReadOnlyModel):
    id: SchTextId
    symbol: SymbolRef
    is_visible: bool
    color: Color
    font_id: FontId
    position: Point
    justification: TextJustification
    orientation: Angle
    text: str
    display_text: RichText | None = None
    variant_text: dict[str, Any] | None = None
    frame: TextFrame | None = None


class SchematicPageGroup(ReadOnlyModel):
    id: SchematicPageGroupId
    display_name: str
    parent: SchematicPageGroupParent | None = None


class TitleBlock(ReadOnlyModel):
    id: TitleBlockId
    name: str
    position: Point
    polylines: dict[PolylineId, Polyline]
    polygons: dict[PolygonId, Polygon]
    rectangles: dict[RectangleId, Rectangle]
    arcs: dict[SchArcId, SchArc]
    ellipses: dict[EllipseId, Ellipse]
    beziers: dict[BezierId, Bezier]
    bitmaps: dict[BitmapId, Bitmap]
    texts: dict[SchTextId, SchText]
    attributes: dict[AttributeId, Attribute]


class Wire(ReadOnlyModel):
    id: WireId
    net_id: NetId | None = None
    p1: Point
    p2: Point
    color: Color
    width: Length
    line_style: LineStyle | None = None
    aliases: dict[WireAliasId, WireAlias] | None = None


class Branch(BranchEntity):
    commit: PayloadCommit | None = None
    effective_branch_protection_name: str
    enable_status_check: bool
    name: str
    protected: bool
    required_approvals: int
    status_check_contexts: list[str] | None = None
    user_can_merge: bool
    user_can_push: bool


class CombinedStatus(ReadOnlyModel):
    commit_url: str
    repository: Repository | None = None
    sha: str
    state: CommitStatusState
    statuses: list[CommitStatus]
    total_count: int
    url: str


class PRBranchInfo(ReadOnlyModel):
    label: str | None = None
    ref: str | None = None
    repo: Repository | None = None
    repo_id: int | None = None
    sha: str | None = None


class DesignReview(DesignReviewEntity):
    additions: int | None = None
    allow_maintainer_edit: bool
    assignee: User | None = None
    assignees: list[User]
    base: PRBranchInfo | None = None
    body: str
    changed_files: int | None = None
    closed_at: AwareDatetime | None = None
    comments: int
    created_at: AwareDatetime | None = None
    deletions: int | None = None
    diff_url: str
    draft: bool
    due_date: AwareDatetime | None = None
    head: PRBranchInfo | None = None
    html_url: str
    id: int
    is_locked: bool
    labels: list[Label]
    merge_base: str
    merge_commit_sha: str | None = None
    mergeable: bool
    merged: bool
    merged_at: AwareDatetime | None = None
    merged_by: User | None = None
    milestone: Milestone | None = None
    number: int
    patch_url: str
    pin_order: int
    requested_reviewers: list[User]
    requested_reviewers_teams: list[Team]
    review_comments: Annotated[
        int | None,
        Field(
            description='number of review comments made on the diff of a PR review (not including comments on commits or issues in a PR)'
        ),
    ] = None
    state: StateType
    title: str
    updated_at: AwareDatetime | None = None
    url: str
    user: User | None = None


class ComponentInstance(ReadOnlyModel):
    id: ComponentId
    part_id: str | None = None
    designator: str | None = None
    schematic_link: str | None = None
    description: str | None = None
    position: Point | None = None
    footprint_lib: str | None = None
    locked: bool | None = None
    arcs: dict[PcbArcId, PcbArc]
    tracks: dict[TrackId, Track]
    pads: dict[PadId, Pad]
    vias: dict[ViaId, Via]
    regions: dict[RegionId, Region]
    texts: dict[PcbTextId, PcbText]


class Graphics(ReadOnlyModel):
    polylines: dict[PolylineId, Polyline]
    polygons: dict[PolygonId, Polygon]
    rectangles: dict[RectangleId, Rectangle]
    arcs: dict[SchArcId, SchArc]
    ellipses: dict[EllipseId, Ellipse]
    beziers: dict[BezierId, Bezier]
    bitmaps: dict[BitmapId, Bitmap]
    texts: dict[SchTextId, SchText]


class Padstack(ReadOnlyModel):
    name: str | None = None
    layers: dict[int, PadstackLayer]
    hole: PadHole | None = None


class PcbExport(ReadOnlyModel):
    type: PcbDocumentType
    layers: dict[int, Layer]
    preset_layers: dict[str, list[LayerId]]
    component_instances: dict[ComponentId, ComponentInstance]
    arcs: dict[PcbArcId, PcbArc]
    tracks: dict[TrackId, Track]
    pads: dict[PadId, Pad]
    vias: dict[ViaId, Via]
    regions: dict[RegionId, Region]
    texts: dict[PcbTextId, PcbText]
    padstacks: dict[PadstackId, Padstack]
    board_size: Point
    board_offset: Point
    nets: dict[NetId, Net]
    length_unit: Millimeter
    angle_unit: Degree


class PcbLibraryComponentSchema(ReadOnlyModel):
    id: PcbLibComponentId
    name: str
    description: str | None = None
    arcs: dict[PcbArcId, PcbArc]
    pads: dict[PadId, Pad]
    vias: dict[ViaId, Via]
    tracks: dict[TrackId, Track]
    texts: dict[PcbTextId, PcbText]
    regions: dict[RegionId, Region]
    fonts: dict[FontId, Font]
    padstacks: dict[PadstackId, Padstack]


class Pin(ReadOnlyModel):
    is_visible: bool | None = None
    symbol: SymbolRef
    name: str
    display_name: RichText | None = None
    name_color: Color
    name_font: FontId | None = None
    name_position: PinTextPositionInfo
    is_name_visible: bool
    description: str
    designator: str
    designator_font: FontId | None = None
    designator_position: PinTextPositionInfo
    designator_color: Color
    is_designator_visible: bool
    electrical_type: PinElectricalType
    net_id: NetId | None = None
    position: Point
    length: Length
    color: Color | None = None
    orientation: PinOrientation


class Port(ReadOnlyModel):
    id: PortId
    position: Point
    rotation: Angle
    mirrored: bool
    name: str
    net_id: NetId | None = None
    description: str | None = None
    reference: str | None = None
    attributes: dict[AttributeId, Attribute]
    pins: dict[PinId, Pin]
    polylines: dict[PolylineId, Polyline]
    polygons: dict[PolygonId, Polygon]
    rectangles: dict[RectangleId, Rectangle]
    arcs: dict[SchArcId, SchArc]
    ellipses: dict[EllipseId, Ellipse]
    beziers: dict[BezierId, Bezier]
    bitmaps: dict[BitmapId, Bitmap]
    texts: dict[SchTextId, SchText]


class SchComponent(ReadOnlyModel):
    id: SchComponentId
    position: Point
    rotation: Angle
    mirrored: bool
    name: str
    description: str | None = None
    reference: str | None = None
    logical_reference: str | None = None
    flags: ComponentFlags | None = None
    attributes: dict[AttributeId, Attribute]
    pins: dict[PinId, Pin]
    polylines: dict[PolylineId, Polyline]
    polygons: dict[PolygonId, Polygon]
    rectangles: dict[RectangleId, Rectangle]
    arcs: dict[SchArcId, SchArc]
    ellipses: dict[EllipseId, Ellipse]
    beziers: dict[BezierId, Bezier]
    bitmaps: dict[BitmapId, Bitmap]
    texts: dict[SchTextId, SchText]
    variants: dict[VariantId, SchComponent | None] | None = None


class SchematicLibraryComponentSchema(ReadOnlyModel):
    id: SchLibComponentId
    name: str
    comment: str | None = None
    designator: str | None = None
    description: str | None = None
    part_id: str | None = None
    symbols_map: dict[int, SchLibSymbol]
    position: Point
    rotation: Angle
    attributes: dict[AttributeId, Attribute]
    pins: dict[PinId, Pin]
    polylines: dict[PolylineId, Polyline]
    polygons: dict[PolygonId, Polygon]
    rectangles: dict[RectangleId, Rectangle]
    arcs: dict[SchArcId, SchArc]
    ellipses: dict[EllipseId, Ellipse]
    beziers: dict[BezierId, Bezier]
    bitmaps: dict[BitmapId, Bitmap]
    texts: dict[SchTextId, SchText]
    fonts: dict[FontId, Font]


class SheetEntry(ReadOnlyModel):
    id: SheetEntryId
    name: str
    display_name: RichText | None = None
    entry_type: SheetEntryType
    net_id: NetId | None = None
    position: Point
    graphics: Graphics


class SheetRef(ReadOnlyModel):
    id: SheetRefId
    sheet_name: str
    filename: str
    sheet_entries: dict[SheetEntryId, SheetEntry]
    position: Point
    graphics: Graphics
    external_sheet: bool


class PcbComponentLibExport(ReadOnlyModel):
    type: PcbComponentLibDocumentType
    components: list[PcbLibraryComponentSchema]


class SchematicComponentLibExport(ReadOnlyModel):
    type: SchematicComponentLibDocumentType
    components: list[SchematicLibraryComponentSchema]


class SchematicPage(ReadOnlyModel):
    id: SchematicPageId
    name: str
    ui_group_id: SchematicPageGroupId
    ui_group_name: str
    page_size: Point
    border: PageBorder | None = None
    title_blocks: dict[TitleBlockId, TitleBlock]
    background_color: Color
    fonts: dict[FontId, Font]
    wires: dict[WireId, Wire]
    junctions: dict[JunctionId, Junction]
    components: dict[SchComponentId, SchComponent]
    ports: dict[PortId, Port]
    sheet_refs: dict[SheetRefId, SheetRef]
    harnesses: dict[HarnessId, Harness] | None = None
    no_connects: dict[NoConnectSymbolId, NoConnectSymbol] | None = None
    graphics: Graphics
    directive_labels: dict[DirectiveLabelId, DirectiveLabel] | None = None
    region_directives: dict[RegionDirectiveId, RegionDirective] | None = None
    net_labels: dict[NetLabelId, NetLabel] | None = None


class SchematicExport(ReadOnlyModel):
    type: SchematicDocumentType
    variants: Annotated[
        dict[VariantId, str] | None,
        Field(
            description='Maps variant ID to variant name. Absent when the schematic has no variants.'
        ),
    ] = None
    nets: dict[NetId, SchematicNet]
    pages: list[SchematicPage]
    page_groups: Annotated[
        dict[SchematicPageGroupId, SchematicPageGroup] | None,
        Field(
            description='Maps group ID (`pages[].ui_group_id`) to page group, representing a hierarchical structure of groups, each with multiple pages. Absent when hierarchy has not been provided.'
        ),
    ] = None


DocumentOutput = PcbComponentLibExport | PcbExport | ProjectEntryExport | SchematicComponentLibExport | SchematicExport


Repository.model_rebuild()
SchComponent.model_rebuild()


# py-allspice types that are not part of the OpenAPI spec, defined here because they compose the
# generated Branch, Commit, and ContentsResponse classes above.

# A git ref: a Branch or Commit object, or a branch / tag / commit name.
Ref = Branch | Commit | str

# Public alias for the spec's file / directory entry type.
Content = ContentsResponse


def normalize_ref(ref: Ref) -> str:
    """Reduce a Ref to the branch name or commit sha the API's `ref` parameters expect."""
    if isinstance(ref, Branch):
        return ref.name
    if isinstance(ref, Commit):
        return ref.sha
    return ref
