# coding: utf-8

"""
    AllSpice API.

    This documentation describes the AllSpice API.  # noqa: E501

    OpenAPI spec version: gitea+v1.19.2-52-gc95a358b1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import allspice_client
from allspice_client.models.migrate_repo_options import MigrateRepoOptions  # noqa: E501
from allspice_client.rest import ApiException


class TestMigrateRepoOptions(unittest.TestCase):
    """MigrateRepoOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMigrateRepoOptions(self):
        """Test MigrateRepoOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = allspice_client.models.migrate_repo_options.MigrateRepoOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
