# coding: utf-8

"""
    AllSpice API.

    This documentation describes the AllSpice API.  # noqa: E501

    OpenAPI spec version: gitea+v1.19.2-52-gc95a358b1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import allspice_client
from allspice_client.models.general_repo_settings import GeneralRepoSettings  # noqa: E501
from allspice_client.rest import ApiException


class TestGeneralRepoSettings(unittest.TestCase):
    """GeneralRepoSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeneralRepoSettings(self):
        """Test GeneralRepoSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = allspice_client.models.general_repo_settings.GeneralRepoSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
