# coding: utf-8

"""
    AllSpice API.

    This documentation describes the AllSpice API.  # noqa: E501

    OpenAPI spec version: gitea+v1.19.2-52-gc95a358b1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import allspice_client
from allspice_client.models.o_auth2_application import OAuth2Application  # noqa: E501
from allspice_client.rest import ApiException


class TestOAuth2Application(unittest.TestCase):
    """OAuth2Application unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOAuth2Application(self):
        """Test OAuth2Application"""
        # FIXME: construct object with mandatory attributes with example values
        # model = allspice_client.models.o_auth2_application.OAuth2Application()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
