# coding: utf-8

"""
    AllSpice API.

    This documentation describes the AllSpice API.  # noqa: E501

    The version of the OpenAPI document: gitea+v1.19.2-52-gc95a358b1
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from allspice_client import schemas  # noqa: F401


class PullRequestMeta(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    PullRequestMeta PR info if an issue is a PR
    """


    class MetaOapg:
        
        class properties:
            merged = schemas.BoolSchema
            merged_at = schemas.DateTimeSchema
            __annotations__ = {
                "merged": merged,
                "merged_at": merged_at,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merged"]) -> MetaOapg.properties.merged: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merged_at"]) -> MetaOapg.properties.merged_at: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["merged", "merged_at", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merged"]) -> typing.Union[MetaOapg.properties.merged, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merged_at"]) -> typing.Union[MetaOapg.properties.merged_at, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["merged", "merged_at", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        merged: typing.Union[MetaOapg.properties.merged, bool, schemas.Unset] = schemas.unset,
        merged_at: typing.Union[MetaOapg.properties.merged_at, str, datetime, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PullRequestMeta':
        return super().__new__(
            cls,
            *_args,
            merged=merged,
            merged_at=merged_at,
            _configuration=_configuration,
            **kwargs,
        )
