"""Tests for the request-class generator.

Each test builds a minimal OpenAPI document and tests against the final generated source
to avoid needing tests to get tangled with schema generation also. The request generation
is custom built so comparing against pure strings doesn't run into false positives around
formatting changes from other tools.
"""

from open_api_generator.requests import generate_requests


def test_basic_get() -> None:
    # Tests that
    #   - The right imports are generated
    #   - The request is named using the operation ID
    #   - Summary is used to generate a doc string
    #   - There is a documentation link generated by tag and operation ID
    #   - Response schema is linked up, as a generic type and a class var for runtime lookup
    #   - GET requests are handled
    document = {
        "paths": {
            "/users/lookup": {
                "get": {
                    "operationId": "lookupUsers",
                    "summary": "Look up users",
                    "tags": ["user"],
                    "responses": {
                        "200": {
                            "content": {
                                "application/json": {
                                    "schema": {"$ref": "#/components/schemas/SampleUser"}
                                }
                            }
                        }
                    },
                }
            }
        },
        "components": {"schemas": {}},
    }

    assert (
        generate_requests(document)
        == '''# @generated by open-api-generator — do not edit by hand

from typing import Annotated

from allspice.base import ApiRequest
from allspice.schemas import (
    SampleUser,
)


class LookupUsersRequest(ApiRequest[SampleUser]):
    """
    Look up users

    https://hub.allspice.io/api/swagger#/user/lookupUsers
    """
    method = "GET"
    request_path = "/users/lookup"
    response_model = SampleUser
'''
    )


def test_paginated_list_response() -> None:
    # Tests that:
    #   - Query params are generated as annotated properties on the request
    #   - Operations with a page param and an array response are generated as PaginatedRequest for paging conveniences
    document = {
        "paths": {
            "/users": {
                "get": {
                    "operationId": "listUsers",
                    "summary": "List users",
                    "tags": ["user"],
                    "parameters": [
                        {"name": "page", "in": "query", "schema": {"type": "integer"}},
                        {"name": "limit", "in": "query", "schema": {"type": "integer"}},
                    ],
                    "responses": {
                        "200": {
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "type": "array",
                                        "items": {"$ref": "#/components/schemas/SampleUser"},
                                    }
                                }
                            }
                        }
                    },
                }
            }
        },
        "components": {"schemas": {}},
    }

    assert (
        generate_requests(document)
        == '''# @generated by open-api-generator — do not edit by hand

from typing import Annotated

from allspice.base import PaginatedRequest, QueryParam
from allspice.schemas import (
    SampleUser,
)


class ListUsersRequest(PaginatedRequest[list[SampleUser], SampleUser]):
    """
    List users

    https://hub.allspice.io/api/swagger#/user/listUsers
    """
    method = "GET"
    request_path = "/users"
    response_model = list[SampleUser]

    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None
'''
    )


def test_paginated_wrapped_list() -> None:
    # Tests that:
    #   - Requests with page param and top level object with arbitrary key with list can also be generated as PaginatedRequest
    document = {
        "paths": {
            "/users/search": {
                "get": {
                    "operationId": "searchUsers",
                    "summary": "Search users",
                    "tags": ["user"],
                    "parameters": [
                        {"name": "page", "in": "query", "schema": {"type": "integer"}},
                        {"name": "limit", "in": "query", "schema": {"type": "integer"}},
                    ],
                    "responses": {
                        "200": {
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": "#/components/schemas/SampleUserSearchResults"
                                    }
                                }
                            }
                        }
                    },
                }
            }
        },
        "components": {
            "schemas": {
                "SampleUserSearchResults": {
                    "type": "object",
                    "properties": {
                        "total_count": {"type": "integer"},
                        "results": {
                            "type": "array",
                            "items": {"$ref": "#/components/schemas/SampleUser"},
                        },
                    },
                }
            }
        },
    }

    assert (
        generate_requests(document)
        == '''# @generated by open-api-generator — do not edit by hand

from typing import Annotated

from allspice.base import PaginatedRequest, QueryParam
from allspice.schemas import (
    SampleUser,
    SampleUserSearchResults,
)


class SearchUsersRequest(PaginatedRequest[SampleUserSearchResults, SampleUser]):
    """
    Search users

    https://hub.allspice.io/api/swagger#/user/searchUsers
    """
    method = "GET"
    request_path = "/users/search"
    response_model = SampleUserSearchResults
    _page_items_attr = "results"

    page: Annotated[int | None, QueryParam()] = None
    limit: Annotated[int | None, QueryParam()] = None
'''
    )


def test_mutation_with_body() -> None:
    # Tests that:
    #   - PATCH operations are handled
    #   - Request body are generated as annotated properties with the correct schema
    #   - Path params are generated as annotated properties on the request
    document = {
        "paths": {
            "/users/{login}": {
                "patch": {
                    "operationId": "updateUser",
                    "summary": "Update a user",
                    "tags": ["user"],
                    "parameters": [
                        {
                            "name": "login",
                            "in": "path",
                            "required": True,
                            "schema": {"type": "string"},
                        },
                    ],
                    "requestBody": {
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/SampleUserOptions"}
                            }
                        }
                    },
                    "responses": {
                        "200": {
                            "content": {
                                "application/json": {
                                    "schema": {"$ref": "#/components/schemas/SampleUser"}
                                }
                            }
                        }
                    },
                }
            }
        },
        "components": {"schemas": {}},
    }

    assert (
        generate_requests(document)
        == '''# @generated by open-api-generator — do not edit by hand

from typing import Annotated

from allspice.base import ApiRequest, JSONBody, PathParam
from allspice.schemas import (
    SampleUser,
    SampleUserOptions,
)


class UpdateUserRequest(ApiRequest[SampleUser]):
    """
    Update a user

    https://hub.allspice.io/api/swagger#/user/updateUser
    """
    method = "PATCH"
    request_path = "/users/{login}"
    response_model = SampleUser

    login: Annotated[str, PathParam()]
    body: Annotated[SampleUserOptions, JSONBody()]
'''
    )


def test_delete_empty_response() -> None:
    # Tests that:
    #   - Empty responses are generated as None for the response type
    #   - DELETE requests are handled
    document = {
        "paths": {
            "/users/{login}": {
                "delete": {
                    "operationId": "deleteUser",
                    "summary": "Delete a user",
                    "tags": ["user"],
                    "parameters": [
                        {
                            "name": "login",
                            "in": "path",
                            "required": True,
                            "schema": {"type": "string"},
                        },
                    ],
                    "responses": {"204": {"description": "user deleted"}},
                }
            }
        },
        "components": {"schemas": {}},
    }

    assert (
        generate_requests(document)
        == '''# @generated by open-api-generator — do not edit by hand

from typing import Annotated

from allspice.base import ApiRequest, PathParam


class DeleteUserRequest(ApiRequest[None]):
    """
    Delete a user

    https://hub.allspice.io/api/swagger#/user/deleteUser
    """
    method = "DELETE"
    request_path = "/users/{login}"
    response_model = None

    login: Annotated[str, PathParam()]
'''
    )


def test_multipart_body_and_binary_response() -> None:
    # Tests that:
    #   - Multipart form data request bodies are annotated as FileBody
    #   - Binary responses are generated as bytes
    #   - POST requests are handled
    document = {
        "paths": {
            "/convert": {
                "post": {
                    "operationId": "convertFile",
                    "summary": "Convert an uploaded file",
                    "tags": ["conversion"],
                    "requestBody": {
                        "content": {
                            "multipart/form-data": {
                                "schema": {
                                    "type": "object",
                                    "properties": {"file": {"type": "string", "format": "binary"}},
                                }
                            }
                        }
                    },
                    "responses": {
                        "200": {
                            "content": {
                                "application/octet-stream": {
                                    "schema": {"type": "string", "format": "binary"}
                                }
                            }
                        }
                    },
                }
            }
        },
        "components": {"schemas": {}},
    }

    assert (
        generate_requests(document)
        == '''# @generated by open-api-generator — do not edit by hand

from typing import Annotated

from allspice.base import ApiRequest, FileBody


class ConvertFileRequest(ApiRequest[bytes]):
    """
    Convert an uploaded file

    https://hub.allspice.io/api/swagger#/conversion/convertFile
    """
    method = "POST"
    request_path = "/convert"
    response_model = bytes

    file: Annotated[bytes, FileBody(api_name="file")]
'''
    )


def test_param_edge_cases() -> None:
    # Tests that:
    #   - Params that collide with our framework are renamed with _ suffix
    #   - Params that collide with python keywords are renamed with _ suffix
    #   - Non-snake case params are renamed in generated request for consistency (while saving the actual value for when making request)
    #   - Header params are generated as annotated properties on the request
    document = {
        "paths": {
            "/repos/{owner}/{repo}/commits": {
                "get": {
                    "operationId": "listCommits",
                    "summary": "List commits",
                    "tags": ["repository"],
                    "parameters": [
                        {
                            "name": "owner",
                            "in": "path",
                            "required": True,
                            "schema": {"type": "string"},
                        },
                        {
                            "name": "repo",
                            "in": "path",
                            "required": True,
                            "schema": {"type": "string"},
                        },
                        {"name": "request_path", "in": "query", "schema": {"type": "string"}},
                        {"name": "not", "in": "query", "schema": {"type": "string"}},
                        {"name": "pre-release", "in": "query", "schema": {"type": "boolean"}},
                        {"name": "Prefer", "in": "header", "schema": {"type": "string"}},
                    ],
                    "responses": {
                        "200": {
                            "content": {
                                "application/json": {
                                    "schema": {"$ref": "#/components/schemas/SampleCommit"}
                                }
                            }
                        }
                    },
                }
            }
        },
        "components": {"schemas": {}},
    }

    assert (
        generate_requests(document)
        == '''# @generated by open-api-generator — do not edit by hand

from typing import Annotated

from allspice.base import ApiRequest, HeaderParam, PathParam, QueryParam
from allspice.schemas import (
    SampleCommit,
)


class ListCommitsRequest(ApiRequest[SampleCommit]):
    """
    List commits

    https://hub.allspice.io/api/swagger#/repository/listCommits
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/commits"
    response_model = SampleCommit

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    request_path_: Annotated[str | None, QueryParam(api_name="request_path")] = None
    not_: Annotated[str | None, QueryParam(api_name="not")] = None
    pre_release: Annotated[bool | None, QueryParam(api_name="pre-release")] = None
    Prefer: Annotated[str | None, HeaderParam()] = None
'''
    )


def test_multiple_operations() -> None:
    # Tests that:
    #   - Multiple operations are generated and batched correct (all imports together and not duplicated)
    #   - PUT requests are handled
    document = {
        "paths": {
            "/repos/{owner}/{repo}/topics": {
                "get": {
                    "operationId": "listTopics",
                    "summary": "List a repository's topics",
                    "tags": ["repository"],
                    "parameters": [
                        {
                            "name": "owner",
                            "in": "path",
                            "required": True,
                            "schema": {"type": "string"},
                            "description": "owner of the repo",
                        },
                        {
                            "name": "repo",
                            "in": "path",
                            "required": True,
                            "schema": {"type": "string"},
                        },
                    ],
                    "responses": {
                        "200": {
                            "content": {
                                "application/json": {
                                    "schema": {"$ref": "#/components/schemas/SampleTopicList"}
                                }
                            }
                        }
                    },
                },
                "put": {
                    "operationId": "replaceTopics",
                    "summary": "Replace a repository's topics",
                    "tags": ["repository"],
                    "parameters": [
                        {
                            "name": "owner",
                            "in": "path",
                            "required": True,
                            "schema": {"type": "string"},
                            "description": "owner of the repo",
                        },
                        {
                            "name": "repo",
                            "in": "path",
                            "required": True,
                            "schema": {"type": "string"},
                        },
                    ],
                    "requestBody": {
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/SampleTopicOptions"}
                            }
                        }
                    },
                    "responses": {
                        "200": {
                            "content": {
                                "application/json": {
                                    "schema": {"$ref": "#/components/schemas/SampleTopicList"}
                                }
                            }
                        }
                    },
                },
            }
        },
        "components": {"schemas": {}},
    }

    assert (
        generate_requests(document)
        == '''# @generated by open-api-generator — do not edit by hand

from typing import Annotated

from allspice.base import ApiRequest, JSONBody, PathParam
from allspice.schemas import (
    SampleTopicList,
    SampleTopicOptions,
)


class ListTopicsRequest(ApiRequest[SampleTopicList]):
    """
    List a repository's topics

    https://hub.allspice.io/api/swagger#/repository/listTopics

    :param owner: owner of the repo
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/topics"
    response_model = SampleTopicList

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]


class ReplaceTopicsRequest(ApiRequest[SampleTopicList]):
    """
    Replace a repository's topics

    https://hub.allspice.io/api/swagger#/repository/replaceTopics

    :param owner: owner of the repo
    """
    method = "PUT"
    request_path = "/repos/{owner}/{repo}/topics"
    response_model = SampleTopicList

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    body: Annotated[SampleTopicOptions, JSONBody()]
'''
    )


def test_html_response_ignored() -> None:
    # Tests that:
    #   - A text/html response is skipped in favour of the JSON one beside it, even though its schema
    #     would otherwise generate (the spec pairs an error page with almost every JSON response)
    document = {
        "paths": {
            "/users/{login}": {
                "get": {
                    "operationId": "getUser",
                    "summary": "Get a user",
                    "tags": ["user"],
                    "parameters": [
                        {
                            "name": "login",
                            "in": "path",
                            "required": True,
                            "schema": {"type": "string"},
                        },
                    ],
                    "responses": {
                        "200": {
                            "content": {
                                "text/html": {
                                    "schema": {"$ref": "#/components/schemas/SampleErrorPage"}
                                },
                                "application/json": {
                                    "schema": {"$ref": "#/components/schemas/SampleUser"}
                                },
                            }
                        }
                    },
                }
            }
        },
        "components": {"schemas": {}},
    }

    assert (
        generate_requests(document)
        == '''# @generated by open-api-generator — do not edit by hand

from typing import Annotated

from allspice.base import ApiRequest, PathParam
from allspice.schemas import (
    SampleUser,
)


class GetUserRequest(ApiRequest[SampleUser]):
    """
    Get a user

    https://hub.allspice.io/api/swagger#/user/getUser
    """
    method = "GET"
    request_path = "/users/{login}"
    response_model = SampleUser

    login: Annotated[str, PathParam()]
'''
    )


def test_parameter_with_schema_reference() -> None:
    # Tests that:
    #   - A param whose schema is a $ref is typed as the referenced schema and imported alongside the
    #     response schemas (the real case is the shared enums on list filters)
    document = {
        "paths": {
            "/repos/{owner}/{repo}/issues": {
                "get": {
                    "operationId": "listIssues",
                    "summary": "List a repository's issues",
                    "tags": ["issue"],
                    "parameters": [
                        {
                            "name": "owner",
                            "in": "path",
                            "required": True,
                            "schema": {"type": "string"},
                        },
                        {
                            "name": "repo",
                            "in": "path",
                            "required": True,
                            "schema": {"type": "string"},
                        },
                        {
                            "name": "state",
                            "in": "query",
                            "schema": {"$ref": "#/components/schemas/SampleStateFilter"},
                        },
                    ],
                    "responses": {
                        "200": {
                            "content": {
                                "application/json": {
                                    "schema": {"$ref": "#/components/schemas/SampleIssue"}
                                }
                            }
                        }
                    },
                }
            }
        },
        "components": {"schemas": {}},
    }

    assert (
        generate_requests(document)
        == '''# @generated by open-api-generator — do not edit by hand

from typing import Annotated

from allspice.base import ApiRequest, PathParam, QueryParam
from allspice.schemas import (
    SampleIssue,
    SampleStateFilter,
)


class ListIssuesRequest(ApiRequest[SampleIssue]):
    """
    List a repository's issues

    https://hub.allspice.io/api/swagger#/issue/listIssues
    """
    method = "GET"
    request_path = "/repos/{owner}/{repo}/issues"
    response_model = SampleIssue

    owner: Annotated[str, PathParam()]
    repo: Annotated[str, PathParam()]
    state: Annotated[SampleStateFilter | None, QueryParam()] = None
'''
    )
