# coding: utf-8

"""
    AllSpice API.

    This documentation describes the AllSpice API.  # noqa: E501

    The version of the OpenAPI document: gitea+v1.19.2-52-gc95a358b1
    Generated by: https://openapi-generator.tech
"""

from allspice_client.paths.activitypub_user_id_user_id.get import ActivitypubPerson
from allspice_client.paths.activitypub_user_id_user_id_inbox.post import ActivitypubPersonInbox


class ActivitypubApi(
    ActivitypubPerson,
    ActivitypubPersonInbox,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
