# coding: utf-8

"""
    AllSpice API.

    This documentation describes the AllSpice API.  # noqa: E501

    The version of the OpenAPI document: gitea+v1.19.2-52-gc95a358b1
    Generated by: https://openapi-generator.tech
"""

from allspice_client.paths.admin_unadopted_owner_repo.post import AdminAdoptRepository
from allspice_client.paths.admin_hooks.post import AdminCreateHook
from allspice_client.paths.admin_users_username_orgs.post import AdminCreateOrg
from allspice_client.paths.admin_users_username_keys.post import AdminCreatePublicKey
from allspice_client.paths.admin_users_username_repos.post import AdminCreateRepo
from allspice_client.paths.admin_users.post import AdminCreateUser
from allspice_client.paths.admin_cron.get import AdminCronList
from allspice_client.paths.admin_cron_task.post import AdminCronRun
from allspice_client.paths.admin_hooks_id.delete import AdminDeleteHook
from allspice_client.paths.admin_unadopted_owner_repo.delete import AdminDeleteUnadoptedRepository
from allspice_client.paths.admin_users_username.delete import AdminDeleteUser
from allspice_client.paths.admin_users_username_keys_id.delete import AdminDeleteUserPublicKey
from allspice_client.paths.admin_hooks_id.patch import AdminEditHook
from allspice_client.paths.admin_users_username.patch import AdminEditUser
from allspice_client.paths.admin_orgs.get import AdminGetAllOrgs
from allspice_client.paths.admin_users.get import AdminGetAllUsers
from allspice_client.paths.admin_hooks_id.get import AdminGetHook
from allspice_client.paths.admin_hooks.get import AdminListHooks
from allspice_client.paths.admin_unadopted.get import AdminUnadoptedList


class AdminApi(
    AdminAdoptRepository,
    AdminCreateHook,
    AdminCreateOrg,
    AdminCreatePublicKey,
    AdminCreateRepo,
    AdminCreateUser,
    AdminCronList,
    AdminCronRun,
    AdminDeleteHook,
    AdminDeleteUnadoptedRepository,
    AdminDeleteUser,
    AdminDeleteUserPublicKey,
    AdminEditHook,
    AdminEditUser,
    AdminGetAllOrgs,
    AdminGetAllUsers,
    AdminGetHook,
    AdminListHooks,
    AdminUnadoptedList,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
