# coding: utf-8

"""
    AllSpice API.

    This documentation describes the AllSpice API.  # noqa: E501

    The version of the OpenAPI document: gitea+v1.19.2-52-gc95a358b1
    Generated by: https://openapi-generator.tech
"""

from allspice_client.paths.repos_owner_repo_issues_index_labels.post import IssueAddLabel
from allspice_client.paths.repos_owner_repo_issues_index_subscriptions_user.put import IssueAddSubscription
from allspice_client.paths.repos_owner_repo_issues_index_times.post import IssueAddTime
from allspice_client.paths.repos_owner_repo_issues_index_subscriptions_check.get import IssueCheckSubscription
from allspice_client.paths.repos_owner_repo_issues_index_labels.delete import IssueClearLabels
from allspice_client.paths.repos_owner_repo_issues_index_comments.post import IssueCreateComment
from allspice_client.paths.repos_owner_repo_issues.post import IssueCreateIssue
from allspice_client.paths.repos_owner_repo_issues_index_assets.post import IssueCreateIssueAttachment
from allspice_client.paths.repos_owner_repo_issues_comments_id_assets.post import IssueCreateIssueCommentAttachment
from allspice_client.paths.repos_owner_repo_labels.post import IssueCreateLabel
from allspice_client.paths.repos_owner_repo_milestones.post import IssueCreateMilestone
from allspice_client.paths.repos_owner_repo_issues_index.delete import IssueDelete
from allspice_client.paths.repos_owner_repo_issues_comments_id.delete import IssueDeleteComment
from allspice_client.paths.repos_owner_repo_issues_index_comments_id.delete import IssueDeleteCommentDeprecated
from allspice_client.paths.repos_owner_repo_issues_comments_id_reactions.delete import IssueDeleteCommentReaction
from allspice_client.paths.repos_owner_repo_issues_index_assets_attachment_id.delete import IssueDeleteIssueAttachment
from allspice_client.paths.repos_owner_repo_issues_comments_id_assets_attachment_id.delete import IssueDeleteIssueCommentAttachment
from allspice_client.paths.repos_owner_repo_issues_index_reactions.delete import IssueDeleteIssueReaction
from allspice_client.paths.repos_owner_repo_labels_id.delete import IssueDeleteLabel
from allspice_client.paths.repos_owner_repo_milestones_id.delete import IssueDeleteMilestone
from allspice_client.paths.repos_owner_repo_issues_index_stopwatch_delete.delete import IssueDeleteStopWatch
from allspice_client.paths.repos_owner_repo_issues_index_subscriptions_user.delete import IssueDeleteSubscription
from allspice_client.paths.repos_owner_repo_issues_index_times_id.delete import IssueDeleteTime
from allspice_client.paths.repos_owner_repo_issues_comments_id.patch import IssueEditComment
from allspice_client.paths.repos_owner_repo_issues_index_comments_id.patch import IssueEditCommentDeprecated
from allspice_client.paths.repos_owner_repo_issues_index.patch import IssueEditIssue
from allspice_client.paths.repos_owner_repo_issues_index_assets_attachment_id.patch import IssueEditIssueAttachment
from allspice_client.paths.repos_owner_repo_issues_comments_id_assets_attachment_id.patch import IssueEditIssueCommentAttachment
from allspice_client.paths.repos_owner_repo_issues_index_deadline.post import IssueEditIssueDeadline
from allspice_client.paths.repos_owner_repo_labels_id.patch import IssueEditLabel
from allspice_client.paths.repos_owner_repo_milestones_id.patch import IssueEditMilestone
from allspice_client.paths.repos_owner_repo_issues_comments_id.get import IssueGetComment
from allspice_client.paths.repos_owner_repo_issues_comments_id_reactions.get import IssueGetCommentReactions
from allspice_client.paths.repos_owner_repo_issues_index_comments.get import IssueGetComments
from allspice_client.paths.repos_owner_repo_issues_index_timeline.get import IssueGetCommentsAndTimeline
from allspice_client.paths.repos_owner_repo_issues_index.get import IssueGetIssue
from allspice_client.paths.repos_owner_repo_issues_index_assets_attachment_id.get import IssueGetIssueAttachment
from allspice_client.paths.repos_owner_repo_issues_comments_id_assets_attachment_id.get import IssueGetIssueCommentAttachment
from allspice_client.paths.repos_owner_repo_issues_index_reactions.get import IssueGetIssueReactions
from allspice_client.paths.repos_owner_repo_labels_id.get import IssueGetLabel
from allspice_client.paths.repos_owner_repo_issues_index_labels.get import IssueGetLabels
from allspice_client.paths.repos_owner_repo_milestones_id.get import IssueGetMilestone
from allspice_client.paths.repos_owner_repo_milestones.get import IssueGetMilestonesList
from allspice_client.paths.repos_owner_repo_issues_comments.get import IssueGetRepoComments
from allspice_client.paths.repos_owner_repo_issues_index_assets.get import IssueListIssueAttachments
from allspice_client.paths.repos_owner_repo_issues_comments_id_assets.get import IssueListIssueCommentAttachments
from allspice_client.paths.repos_owner_repo_issues.get import IssueListIssues
from allspice_client.paths.repos_owner_repo_labels.get import IssueListLabels
from allspice_client.paths.repos_owner_repo_issues_comments_id_reactions.post import IssuePostCommentReaction
from allspice_client.paths.repos_owner_repo_issues_index_reactions.post import IssuePostIssueReaction
from allspice_client.paths.repos_owner_repo_issues_index_labels_id.delete import IssueRemoveLabel
from allspice_client.paths.repos_owner_repo_issues_index_labels.put import IssueReplaceLabels
from allspice_client.paths.repos_owner_repo_issues_index_times.delete import IssueResetTime
from allspice_client.paths.repos_issues_search.get import IssueSearchIssues
from allspice_client.paths.repos_owner_repo_issues_index_stopwatch_start.post import IssueStartStopWatch
from allspice_client.paths.repos_owner_repo_issues_index_stopwatch_stop.post import IssueStopStopWatch
from allspice_client.paths.repos_owner_repo_issues_index_subscriptions.get import IssueSubscriptions
from allspice_client.paths.repos_owner_repo_issues_index_times.get import IssueTrackedTimes


class IssueApi(
    IssueAddLabel,
    IssueAddSubscription,
    IssueAddTime,
    IssueCheckSubscription,
    IssueClearLabels,
    IssueCreateComment,
    IssueCreateIssue,
    IssueCreateIssueAttachment,
    IssueCreateIssueCommentAttachment,
    IssueCreateLabel,
    IssueCreateMilestone,
    IssueDelete,
    IssueDeleteComment,
    IssueDeleteCommentDeprecated,
    IssueDeleteCommentReaction,
    IssueDeleteIssueAttachment,
    IssueDeleteIssueCommentAttachment,
    IssueDeleteIssueReaction,
    IssueDeleteLabel,
    IssueDeleteMilestone,
    IssueDeleteStopWatch,
    IssueDeleteSubscription,
    IssueDeleteTime,
    IssueEditComment,
    IssueEditCommentDeprecated,
    IssueEditIssue,
    IssueEditIssueAttachment,
    IssueEditIssueCommentAttachment,
    IssueEditIssueDeadline,
    IssueEditLabel,
    IssueEditMilestone,
    IssueGetComment,
    IssueGetCommentReactions,
    IssueGetComments,
    IssueGetCommentsAndTimeline,
    IssueGetIssue,
    IssueGetIssueAttachment,
    IssueGetIssueCommentAttachment,
    IssueGetIssueReactions,
    IssueGetLabel,
    IssueGetLabels,
    IssueGetMilestone,
    IssueGetMilestonesList,
    IssueGetRepoComments,
    IssueListIssueAttachments,
    IssueListIssueCommentAttachments,
    IssueListIssues,
    IssueListLabels,
    IssuePostCommentReaction,
    IssuePostIssueReaction,
    IssueRemoveLabel,
    IssueReplaceLabels,
    IssueResetTime,
    IssueSearchIssues,
    IssueStartStopWatch,
    IssueStopStopWatch,
    IssueSubscriptions,
    IssueTrackedTimes,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
