# coding: utf-8

"""
    AllSpice API.

    This documentation describes the AllSpice API.  # noqa: E501

    The version of the OpenAPI document: gitea+v1.19.2-52-gc95a358b1
    Generated by: https://openapi-generator.tech
"""

from allspice_client.paths.nodeinfo.get import GetNodeInfo
from allspice_client.paths.signing_key_gpg.get import GetSigningKey
from allspice_client.paths.version.get import GetVersion
from allspice_client.paths.markdown.post import RenderMarkdown
from allspice_client.paths.markdown_raw.post import RenderMarkdownRaw


class MiscellaneousApi(
    GetNodeInfo,
    GetSigningKey,
    GetVersion,
    RenderMarkdown,
    RenderMarkdownRaw,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
