# coding: utf-8

"""
    AllSpice API.

    This documentation describes the AllSpice API.  # noqa: E501

    The version of the OpenAPI document: gitea+v1.19.2-52-gc95a358b1
    Generated by: https://openapi-generator.tech
"""

from allspice_client.paths.notifications.get import NotifyGetList
from allspice_client.paths.repos_owner_repo_notifications.get import NotifyGetRepoList
from allspice_client.paths.notifications_threads_id.get import NotifyGetThread
from allspice_client.paths.notifications_new.get import NotifyNewAvailable
from allspice_client.paths.notifications.put import NotifyReadList
from allspice_client.paths.repos_owner_repo_notifications.put import NotifyReadRepoList
from allspice_client.paths.notifications_threads_id.patch import NotifyReadThread


class NotificationApi(
    NotifyGetList,
    NotifyGetRepoList,
    NotifyGetThread,
    NotifyNewAvailable,
    NotifyReadList,
    NotifyReadRepoList,
    NotifyReadThread,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
