# coding: utf-8

"""
    AllSpice API.

    This documentation describes the AllSpice API.  # noqa: E501

    The version of the OpenAPI document: gitea+v1.19.2-52-gc95a358b1
    Generated by: https://openapi-generator.tech
"""

from allspice_client.paths.orgs_org_repos.post import CreateOrgRepo
from allspice_client.paths.org_org_repos.post import CreateOrgRepoDeprecated
from allspice_client.paths.teams_id_members_username.put import OrgAddTeamMember
from allspice_client.paths.teams_id_repos_org_repo.put import OrgAddTeamRepository
from allspice_client.paths.orgs_org_public_members_username.delete import OrgConcealMember
from allspice_client.paths.orgs.post import OrgCreate
from allspice_client.paths.orgs_org_hooks.post import OrgCreateHook
from allspice_client.paths.orgs_org_labels.post import OrgCreateLabel
from allspice_client.paths.orgs_org_teams.post import OrgCreateTeam
from allspice_client.paths.orgs_org.delete import OrgDelete
from allspice_client.paths.orgs_org_hooks_id.delete import OrgDeleteHook
from allspice_client.paths.orgs_org_labels_id.delete import OrgDeleteLabel
from allspice_client.paths.orgs_org_members_username.delete import OrgDeleteMember
from allspice_client.paths.teams_id.delete import OrgDeleteTeam
from allspice_client.paths.orgs_org.patch import OrgEdit
from allspice_client.paths.orgs_org_hooks_id.patch import OrgEditHook
from allspice_client.paths.orgs_org_labels_id.patch import OrgEditLabel
from allspice_client.paths.teams_id.patch import OrgEditTeam
from allspice_client.paths.orgs_org.get import OrgGet
from allspice_client.paths.orgs.get import OrgGetAll
from allspice_client.paths.orgs_org_hooks_id.get import OrgGetHook
from allspice_client.paths.orgs_org_labels_id.get import OrgGetLabel
from allspice_client.paths.teams_id.get import OrgGetTeam
from allspice_client.paths.users_username_orgs_org_permissions.get import OrgGetUserPermissions
from allspice_client.paths.orgs_org_members_username.get import OrgIsMember
from allspice_client.paths.orgs_org_public_members_username.get import OrgIsPublicMember
from allspice_client.paths.user_orgs.get import OrgListCurrentUserOrgs
from allspice_client.paths.orgs_org_hooks.get import OrgListHooks
from allspice_client.paths.orgs_org_labels.get import OrgListLabels
from allspice_client.paths.orgs_org_members.get import OrgListMembers
from allspice_client.paths.orgs_org_public_members.get import OrgListPublicMembers
from allspice_client.paths.orgs_org_repos.get import OrgListRepos
from allspice_client.paths.teams_id_members_username.get import OrgListTeamMember
from allspice_client.paths.teams_id_members.get import OrgListTeamMembers
from allspice_client.paths.teams_id_repos_org_repo.get import OrgListTeamRepo
from allspice_client.paths.teams_id_repos.get import OrgListTeamRepos
from allspice_client.paths.orgs_org_teams.get import OrgListTeams
from allspice_client.paths.users_username_orgs.get import OrgListUserOrgs
from allspice_client.paths.orgs_org_public_members_username.put import OrgPublicizeMember
from allspice_client.paths.teams_id_members_username.delete import OrgRemoveTeamMember
from allspice_client.paths.teams_id_repos_org_repo.delete import OrgRemoveTeamRepository
from allspice_client.paths.orgs_org_teams_search.get import TeamSearch


class OrganizationApi(
    CreateOrgRepo,
    CreateOrgRepoDeprecated,
    OrgAddTeamMember,
    OrgAddTeamRepository,
    OrgConcealMember,
    OrgCreate,
    OrgCreateHook,
    OrgCreateLabel,
    OrgCreateTeam,
    OrgDelete,
    OrgDeleteHook,
    OrgDeleteLabel,
    OrgDeleteMember,
    OrgDeleteTeam,
    OrgEdit,
    OrgEditHook,
    OrgEditLabel,
    OrgEditTeam,
    OrgGet,
    OrgGetAll,
    OrgGetHook,
    OrgGetLabel,
    OrgGetTeam,
    OrgGetUserPermissions,
    OrgIsMember,
    OrgIsPublicMember,
    OrgListCurrentUserOrgs,
    OrgListHooks,
    OrgListLabels,
    OrgListMembers,
    OrgListPublicMembers,
    OrgListRepos,
    OrgListTeamMember,
    OrgListTeamMembers,
    OrgListTeamRepo,
    OrgListTeamRepos,
    OrgListTeams,
    OrgListUserOrgs,
    OrgPublicizeMember,
    OrgRemoveTeamMember,
    OrgRemoveTeamRepository,
    TeamSearch,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
