# coding: utf-8

"""
    AllSpice API.

    This documentation describes the AllSpice API.  # noqa: E501

    The version of the OpenAPI document: gitea+v1.19.2-52-gc95a358b1
    Generated by: https://openapi-generator.tech
"""

from allspice_client.paths.packages_owner_type_name_version.delete import DeletePackage
from allspice_client.paths.packages_owner_type_name_version.get import GetPackage
from allspice_client.paths.packages_owner_type_name_version_files.get import ListPackageFiles
from allspice_client.paths.packages_owner.get import ListPackages


class PackageApi(
    DeletePackage,
    GetPackage,
    ListPackageFiles,
    ListPackages,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
