# coding: utf-8

"""
    AllSpice API.

    This documentation describes the AllSpice API.  # noqa: E501

    The version of the OpenAPI document: gitea+v1.19.2-52-gc95a358b1
    Generated by: https://openapi-generator.tech
"""

from allspice_client.paths.repos_owner_repo_transfer_accept.post import AcceptRepoTransfer
from allspice_client.paths.user_repos.post import CreateCurrentUserRepo
from allspice_client.paths.repos_owner_repo_forks.post import CreateFork
from allspice_client.paths.repos_template_owner_template_repo_generate.post import GenerateRepo
from allspice_client.paths.repos_owner_repo_git_tags_sha.get import GetAnnotatedTag
from allspice_client.paths.repos_owner_repo_git_blobs_sha.get import GetBlob
from allspice_client.paths.repos_owner_repo_git_trees_sha.get import GetTree
from allspice_client.paths.repos_owner_repo_forks.get import ListForks
from allspice_client.paths.repos_owner_repo_transfer_reject.post import RejectRepoTransfer
from allspice_client.paths.repos_owner_repo_collaborators_collaborator.put import RepoAddCollaborator
from allspice_client.paths.repos_owner_repo_push_mirrors.post import RepoAddPushMirror
from allspice_client.paths.repos_owner_repo_teams_team.put import RepoAddTeam
from allspice_client.paths.repos_owner_repo_topics_topic.put import RepoAddTopic
from allspice_client.paths.repos_owner_repo_diffpatch.post import RepoApplyDiffPatch
from allspice_client.paths.repos_owner_repo_pulls_index_merge.delete import RepoCancelScheduledAutoMerge
from allspice_client.paths.repos_owner_repo_collaborators_collaborator.get import RepoCheckCollaborator
from allspice_client.paths.repos_owner_repo_teams_team.get import RepoCheckTeam
from allspice_client.paths.repos_owner_repo_branches.post import RepoCreateBranch
from allspice_client.paths.repos_owner_repo_branch_protections.post import RepoCreateBranchProtection
from allspice_client.paths.repos_owner_repo_contents_filepath.post import RepoCreateFile
from allspice_client.paths.repos_owner_repo_hooks.post import RepoCreateHook
from allspice_client.paths.repos_owner_repo_keys.post import RepoCreateKey
from allspice_client.paths.repos_owner_repo_pulls.post import RepoCreatePullRequest
from allspice_client.paths.repos_owner_repo_pulls_index_reviews.post import RepoCreatePullReview
from allspice_client.paths.repos_owner_repo_pulls_index_requested_reviewers.post import RepoCreatePullReviewRequests
from allspice_client.paths.repos_owner_repo_releases.post import RepoCreateRelease
from allspice_client.paths.repos_owner_repo_releases_id_assets.post import RepoCreateReleaseAttachment
from allspice_client.paths.repos_owner_repo_statuses_sha.post import RepoCreateStatus
from allspice_client.paths.repos_owner_repo_tags.post import RepoCreateTag
from allspice_client.paths.repos_owner_repo_wiki_new.post import RepoCreateWikiPage
from allspice_client.paths.repos_owner_repo.delete import RepoDelete
from allspice_client.paths.repos_owner_repo_branches_branch.delete import RepoDeleteBranch
from allspice_client.paths.repos_owner_repo_branch_protections_name.delete import RepoDeleteBranchProtection
from allspice_client.paths.repos_owner_repo_collaborators_collaborator.delete import RepoDeleteCollaborator
from allspice_client.paths.repos_owner_repo_contents_filepath.delete import RepoDeleteFile
from allspice_client.paths.repos_owner_repo_hooks_git_id.delete import RepoDeleteGitHook
from allspice_client.paths.repos_owner_repo_hooks_id.delete import RepoDeleteHook
from allspice_client.paths.repos_owner_repo_keys_id.delete import RepoDeleteKey
from allspice_client.paths.repos_owner_repo_pulls_index_reviews_id.delete import RepoDeletePullReview
from allspice_client.paths.repos_owner_repo_pulls_index_requested_reviewers.delete import RepoDeletePullReviewRequests
from allspice_client.paths.repos_owner_repo_push_mirrors_name.delete import RepoDeletePushMirror
from allspice_client.paths.repos_owner_repo_releases_id.delete import RepoDeleteRelease
from allspice_client.paths.repos_owner_repo_releases_id_assets_attachment_id.delete import RepoDeleteReleaseAttachment
from allspice_client.paths.repos_owner_repo_releases_tags_tag.delete import RepoDeleteReleaseByTag
from allspice_client.paths.repos_owner_repo_tags_tag.delete import RepoDeleteTag
from allspice_client.paths.repos_owner_repo_teams_team.delete import RepoDeleteTeam
from allspice_client.paths.repos_owner_repo_topics_topic.delete import RepoDeleteTopic
from allspice_client.paths.repos_owner_repo_wiki_page_page_name.delete import RepoDeleteWikiPage
from allspice_client.paths.repos_owner_repo_pulls_index_reviews_id_dismissals.post import RepoDismissPullReview
from allspice_client.paths.repos_owner_repo_git_commits_sha_diff_type.get import RepoDownloadCommitDiffOrPatch
from allspice_client.paths.repos_owner_repo_pulls_index_diff_type.get import RepoDownloadPullDiffOrPatch
from allspice_client.paths.repos_owner_repo.patch import RepoEdit
from allspice_client.paths.repos_owner_repo_branch_protections_name.patch import RepoEditBranchProtection
from allspice_client.paths.repos_owner_repo_hooks_git_id.patch import RepoEditGitHook
from allspice_client.paths.repos_owner_repo_hooks_id.patch import RepoEditHook
from allspice_client.paths.repos_owner_repo_pulls_index.patch import RepoEditPullRequest
from allspice_client.paths.repos_owner_repo_releases_id.patch import RepoEditRelease
from allspice_client.paths.repos_owner_repo_releases_id_assets_attachment_id.patch import RepoEditReleaseAttachment
from allspice_client.paths.repos_owner_repo_wiki_page_page_name.patch import RepoEditWikiPage
from allspice_client.paths.repos_owner_repo.get import RepoGet
from allspice_client.paths.repos_owner_repo_commits.get import RepoGetAllCommits
from allspice_client.paths.repos_owner_repo_allspice_generated_json_filepath.get import RepoGetAllSpiceJson
from allspice_client.paths.repos_owner_repo_allspice_generated_svg_filepath.get import RepoGetAllSpiceSvg
from allspice_client.paths.repos_owner_repo_archive_archive.get import RepoGetArchive
from allspice_client.paths.repos_owner_repo_assignees.get import RepoGetAssignees
from allspice_client.paths.repos_owner_repo_branches_branch.get import RepoGetBranch
from allspice_client.paths.repos_owner_repo_branch_protections_name.get import RepoGetBranchProtection
from allspice_client.paths.repositories_id.get import RepoGetById
from allspice_client.paths.repos_owner_repo_commits_ref_status.get import RepoGetCombinedStatusByRef
from allspice_client.paths.repos_owner_repo_contents_filepath.get import RepoGetContents
from allspice_client.paths.repos_owner_repo_contents.get import RepoGetContentsList
from allspice_client.paths.repos_owner_repo_editorconfig_filepath.get import RepoGetEditorConfig
from allspice_client.paths.repos_owner_repo_hooks_git_id.get import RepoGetGitHook
from allspice_client.paths.repos_owner_repo_hooks_id.get import RepoGetHook
from allspice_client.paths.repos_owner_repo_issue_templates.get import RepoGetIssueTemplates
from allspice_client.paths.repos_owner_repo_keys_id.get import RepoGetKey
from allspice_client.paths.repos_owner_repo_languages.get import RepoGetLanguages
from allspice_client.paths.repos_owner_repo_releases_latest.get import RepoGetLatestRelease
from allspice_client.paths.repos_owner_repo_git_notes_sha.get import RepoGetNote
from allspice_client.paths.repos_owner_repo_pulls_index.get import RepoGetPullRequest
from allspice_client.paths.repos_owner_repo_pulls_index_commits.get import RepoGetPullRequestCommits
from allspice_client.paths.repos_owner_repo_pulls_index_files.get import RepoGetPullRequestFiles
from allspice_client.paths.repos_owner_repo_pulls_index_reviews_id.get import RepoGetPullReview
from allspice_client.paths.repos_owner_repo_pulls_index_reviews_id_comments.get import RepoGetPullReviewComments
from allspice_client.paths.repos_owner_repo_push_mirrors_name.get import RepoGetPushMirrorByRemoteName
from allspice_client.paths.repos_owner_repo_raw_filepath.get import RepoGetRawFile
from allspice_client.paths.repos_owner_repo_media_filepath.get import RepoGetRawFileOrLfs
from allspice_client.paths.repos_owner_repo_releases_id.get import RepoGetRelease
from allspice_client.paths.repos_owner_repo_releases_id_assets_attachment_id.get import RepoGetReleaseAttachment
from allspice_client.paths.repos_owner_repo_releases_tags_tag.get import RepoGetReleaseByTag
from allspice_client.paths.repos_owner_repo_collaborators_collaborator_permission.get import RepoGetRepoPermissions
from allspice_client.paths.repos_owner_repo_reviewers.get import RepoGetReviewers
from allspice_client.paths.repos_owner_repo_git_commits_sha.get import RepoGetSingleCommit
from allspice_client.paths.repos_owner_repo_tags_tag.get import RepoGetTag
from allspice_client.paths.repos_owner_repo_wiki_page_page_name.get import RepoGetWikiPage
from allspice_client.paths.repos_owner_repo_wiki_revisions_page_name.get import RepoGetWikiPageRevisions
from allspice_client.paths.repos_owner_repo_wiki_pages.get import RepoGetWikiPages
from allspice_client.paths.repos_owner_repo_git_refs.get import RepoListAllGitRefs
from allspice_client.paths.repos_owner_repo_branch_protections.get import RepoListBranchProtection
from allspice_client.paths.repos_owner_repo_branches.get import RepoListBranches
from allspice_client.paths.repos_owner_repo_collaborators.get import RepoListCollaborators
from allspice_client.paths.repos_owner_repo_hooks_git.get import RepoListGitHooks
from allspice_client.paths.repos_owner_repo_git_refs_ref.get import RepoListGitRefs
from allspice_client.paths.repos_owner_repo_hooks.get import RepoListHooks
from allspice_client.paths.repos_owner_repo_keys.get import RepoListKeys
from allspice_client.paths.repos_owner_repo_pulls.get import RepoListPullRequests
from allspice_client.paths.repos_owner_repo_pulls_index_reviews.get import RepoListPullReviews
from allspice_client.paths.repos_owner_repo_push_mirrors.get import RepoListPushMirrors
from allspice_client.paths.repos_owner_repo_releases_id_assets.get import RepoListReleaseAttachments
from allspice_client.paths.repos_owner_repo_releases.get import RepoListReleases
from allspice_client.paths.repos_owner_repo_stargazers.get import RepoListStargazers
from allspice_client.paths.repos_owner_repo_statuses_sha.get import RepoListStatuses
from allspice_client.paths.repos_owner_repo_commits_ref_statuses.get import RepoListStatusesByRef
from allspice_client.paths.repos_owner_repo_subscribers.get import RepoListSubscribers
from allspice_client.paths.repos_owner_repo_tags.get import RepoListTags
from allspice_client.paths.repos_owner_repo_teams.get import RepoListTeams
from allspice_client.paths.repos_owner_repo_topics.get import RepoListTopics
from allspice_client.paths.repos_owner_repo_pulls_index_merge.post import RepoMergePullRequest
from allspice_client.paths.repos_migrate.post import RepoMigrate
from allspice_client.paths.repos_owner_repo_mirror_sync.post import RepoMirrorSync
from allspice_client.paths.repos_owner_repo_pulls_index_merge.get import RepoPullRequestIsMerged
from allspice_client.paths.repos_owner_repo_push_mirrors_sync.post import RepoPushMirrorSync
from allspice_client.paths.repos_search.get import RepoSearch
from allspice_client.paths.repos_owner_repo_signing_key_gpg.get import RepoSigningKey
from allspice_client.paths.repos_owner_repo_pulls_index_reviews_id.post import RepoSubmitPullReview
from allspice_client.paths.repos_owner_repo_hooks_id_tests.post import RepoTestHook
from allspice_client.paths.repos_owner_repo_times.get import RepoTrackedTimes
from allspice_client.paths.repos_owner_repo_transfer.post import RepoTransfer
from allspice_client.paths.repos_owner_repo_pulls_index_reviews_id_undismissals.post import RepoUnDismissPullReview
from allspice_client.paths.repos_owner_repo_contents_filepath.put import RepoUpdateFile
from allspice_client.paths.repos_owner_repo_pulls_index_update.post import RepoUpdatePullRequest
from allspice_client.paths.repos_owner_repo_topics.put import RepoUpdateTopics
from allspice_client.paths.topics_search.get import TopicSearch
from allspice_client.paths.repos_owner_repo_subscription.get import UserCurrentCheckSubscription
from allspice_client.paths.repos_owner_repo_subscription.delete import UserCurrentDeleteSubscription
from allspice_client.paths.repos_owner_repo_subscription.put import UserCurrentPutSubscription
from allspice_client.paths.repos_owner_repo_times_user.get import UserTrackedTimes


class RepositoryApi(
    AcceptRepoTransfer,
    CreateCurrentUserRepo,
    CreateFork,
    GenerateRepo,
    GetAnnotatedTag,
    GetBlob,
    GetTree,
    ListForks,
    RejectRepoTransfer,
    RepoAddCollaborator,
    RepoAddPushMirror,
    RepoAddTeam,
    RepoAddTopic,
    RepoApplyDiffPatch,
    RepoCancelScheduledAutoMerge,
    RepoCheckCollaborator,
    RepoCheckTeam,
    RepoCreateBranch,
    RepoCreateBranchProtection,
    RepoCreateFile,
    RepoCreateHook,
    RepoCreateKey,
    RepoCreatePullRequest,
    RepoCreatePullReview,
    RepoCreatePullReviewRequests,
    RepoCreateRelease,
    RepoCreateReleaseAttachment,
    RepoCreateStatus,
    RepoCreateTag,
    RepoCreateWikiPage,
    RepoDelete,
    RepoDeleteBranch,
    RepoDeleteBranchProtection,
    RepoDeleteCollaborator,
    RepoDeleteFile,
    RepoDeleteGitHook,
    RepoDeleteHook,
    RepoDeleteKey,
    RepoDeletePullReview,
    RepoDeletePullReviewRequests,
    RepoDeletePushMirror,
    RepoDeleteRelease,
    RepoDeleteReleaseAttachment,
    RepoDeleteReleaseByTag,
    RepoDeleteTag,
    RepoDeleteTeam,
    RepoDeleteTopic,
    RepoDeleteWikiPage,
    RepoDismissPullReview,
    RepoDownloadCommitDiffOrPatch,
    RepoDownloadPullDiffOrPatch,
    RepoEdit,
    RepoEditBranchProtection,
    RepoEditGitHook,
    RepoEditHook,
    RepoEditPullRequest,
    RepoEditRelease,
    RepoEditReleaseAttachment,
    RepoEditWikiPage,
    RepoGet,
    RepoGetAllCommits,
    RepoGetAllSpiceJson,
    RepoGetAllSpiceSvg,
    RepoGetArchive,
    RepoGetAssignees,
    RepoGetBranch,
    RepoGetBranchProtection,
    RepoGetById,
    RepoGetCombinedStatusByRef,
    RepoGetContents,
    RepoGetContentsList,
    RepoGetEditorConfig,
    RepoGetGitHook,
    RepoGetHook,
    RepoGetIssueTemplates,
    RepoGetKey,
    RepoGetLanguages,
    RepoGetLatestRelease,
    RepoGetNote,
    RepoGetPullRequest,
    RepoGetPullRequestCommits,
    RepoGetPullRequestFiles,
    RepoGetPullReview,
    RepoGetPullReviewComments,
    RepoGetPushMirrorByRemoteName,
    RepoGetRawFile,
    RepoGetRawFileOrLfs,
    RepoGetRelease,
    RepoGetReleaseAttachment,
    RepoGetReleaseByTag,
    RepoGetRepoPermissions,
    RepoGetReviewers,
    RepoGetSingleCommit,
    RepoGetTag,
    RepoGetWikiPage,
    RepoGetWikiPageRevisions,
    RepoGetWikiPages,
    RepoListAllGitRefs,
    RepoListBranchProtection,
    RepoListBranches,
    RepoListCollaborators,
    RepoListGitHooks,
    RepoListGitRefs,
    RepoListHooks,
    RepoListKeys,
    RepoListPullRequests,
    RepoListPullReviews,
    RepoListPushMirrors,
    RepoListReleaseAttachments,
    RepoListReleases,
    RepoListStargazers,
    RepoListStatuses,
    RepoListStatusesByRef,
    RepoListSubscribers,
    RepoListTags,
    RepoListTeams,
    RepoListTopics,
    RepoMergePullRequest,
    RepoMigrate,
    RepoMirrorSync,
    RepoPullRequestIsMerged,
    RepoPushMirrorSync,
    RepoSearch,
    RepoSigningKey,
    RepoSubmitPullReview,
    RepoTestHook,
    RepoTrackedTimes,
    RepoTransfer,
    RepoUnDismissPullReview,
    RepoUpdateFile,
    RepoUpdatePullRequest,
    RepoUpdateTopics,
    TopicSearch,
    UserCurrentCheckSubscription,
    UserCurrentDeleteSubscription,
    UserCurrentPutSubscription,
    UserTrackedTimes,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
