# coding: utf-8

"""
    AllSpice API.

    This documentation describes the AllSpice API.  # noqa: E501

    The version of the OpenAPI document: gitea+v1.19.2-52-gc95a358b1
    Generated by: https://openapi-generator.tech
"""

from allspice_client.paths.settings_api.get import GetGeneralApiSettings
from allspice_client.paths.settings_attachment.get import GetGeneralAttachmentSettings
from allspice_client.paths.settings_repository.get import GetGeneralRepositorySettings
from allspice_client.paths.settings_ui.get import GetGeneralUiSettings


class SettingsApi(
    GetGeneralApiSettings,
    GetGeneralAttachmentSettings,
    GetGeneralRepositorySettings,
    GetGeneralUiSettings,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
