# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import allspice_client
from allspice_client.paths.user_following_username import get  # noqa: E501
from allspice_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestUserFollowingUsername(ApiTestMixin, unittest.TestCase):
    """
    UserFollowingUsername unit test stubs
        Check whether a user is followed by the authenticated user  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 204
    response_body = ''


if __name__ == '__main__':
    unittest.main()
