name: Release
on:
  workflow_run:
    workflows: ["Test py-allspice in CI"]
    branches: ["**"]
    types: 
      - completed

jobs:
  notifications:
    name: Notifications
    runs-on: ubuntu-22.04
    steps:
      - name: Slack Notification       
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "${{ github.event.workflow_run.conclusion == 'success' && 'good' || github.event.workflow_run.conclusion == 'cancelled' && 'warning' || 'danger' }}",
                  "fields": [
                    {
                      "title": "py-allspice CI: ${{ github.event.workflow_run.conclusion }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                      "value": "GitHub Action build result: ${{ github.event.workflow_run.conclusion }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEV_CI }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
